### ISSUE TITLE
Feature Request: EPANET demand multiplier support in WNTR solver

### ISSUE THREAD

**Issue by pshassett** [USEPA/WNTR#100]
What would it take to have support for this option in the wntr solver?

Its inclusion in the calculation of [`wntr.metrics.expected_demand`](https://wntr.readthedocs.io/en/latest/_modules/wntr/metrics/hydraulic.html#expected_demand) can result in unexpected values from [`wntr.metrics.water_service_availability`](https://wntr.readthedocs.io/en/latest/_modules/wntr/metrics/hydraulic.html#water_service_availability) when using the wntr simulator.

**Comment by kaklise** [comment]
This is listed as a known limitation of the WNTRSimulator.  I think it is an easy fix, I'll try to get this resolved soon.

**Comment by pshassett** [comment]
Great to hear!
