### ISSUE TITLE
run_sim() error

### ISSUE THREAD

**Issue by GalPerelman** [USEPA/WNTR#102]
Hello,
I'm trying to run the Getting Started [example](https://wntr.readthedocs.io/en/latest/getting_started.html) and get the following error:

`OSError: [WinError 126] The specified module could not be found`

**Comment by michaelbynum** [comment]
Can you provide any more details? What version of WNTR are you using? Can you provide the full stack trace?

**Comment by GalPerelman** [comment]
I'm using wntr 0.1.7

![run_sim error](https://user-images.githubusercontent.com/53649764/62624100-016a8080-b92b-11e9-8c11-52e28428b01f.PNG)

**Comment by michaelbynum** [comment]
Thanks. One more question. What version of Python are you using?

**Comment by GalPerelman** [comment]
Python 3.7 with Anaconda

**Comment by michaelbynum** [comment]
When you installed python with anaconda, did you use the 32-bit or the 64-bit installer?

**Comment by GalPerelman** [comment]
64 bit

**Comment by michaelbynum** [comment]
And how did you install winter?

**Comment by GalPerelman** [comment]
I'm working on an offline system
For that reason, I downloaded whl file, delivered it to the offline system,
and then installed it with pip install

**Comment by GalPerelman** [comment]
I figured out what was the problem, Apparently, one of the DLL files was missing.
I think that during the transference of the whl file to the offline system, the specific file was dropped.
To solve this, I downloaded the missing DLL separately and saved it in the directory according to the error. Now it's works

**Comment by dbhart** [comment]
Can you tell us which one? It would be good to know if this comes up again. TIA

- Dave Hart, Sent from my iPhone

On Aug 12, 2019, at 4:16 AM, GalPerelman <notifications@github.com<mailto:notifications@github.com>> wrote:


I figured out what was the problem, Apparently, one of the DLL files was missing.
I think that during the transference of the whl file to the offline system, the specific file was dropped.
To solve this, I downloaded the missing DLL separately and saved it in the directory according to the error. Now it's works

**Comment by GalPerelman** [comment]
The missing file was 'epanet2_amd64.dll'
Need to be located in 'C:\ProgramData\Anaconda3\Lib\site-packages\wntr\epanet\Windows'

**Comment by dbhart** [comment]
Thank you! We’ve had problems before on DLLs not getting in (2 vs 3 method differences) so we will look to make sure it’s included in the right places.
