### ISSUE TITLE
Error in units change HeadLoss

### ISSUE THREAD

**Issue by gandresr** [USEPA/WNTR#104]
HeadLoss units are not properly converted when using the epanet package

**Comment by michaelbynum** [comment]
@gandresr Can you provide any more details on the problem you are having?

**Comment by kaklise** [comment]
Currently, WNTR reports headloss only when the EpanetSimulator is used.  The units are as follows:

- Per unit pipe length for pipes (note, EPANET reports headloss per 1000 ft or m of pipe length)
- Negative of head gain for pumps (same as EPANET)
- Total head loss for valves (same as EPANET)

WNTR results could be updated to report the total head loss for pipes.
