### ISSUE TITLE
Run extended simulation with WNTR

### ISSUE THREAD

**Issue by emmaliulu** [USEPA/WNTR#108]
I have no trouble running WNTRSimulator with the default 24-hour setting in my model. But when I tried to run extended simulation of 48 hours, the simulation cannot solve. Here's what I did.

inp_file = 'AvgDay_460MGD_March2018_original.inp'
wn_0 = wntr.network.WaterNetworkModel(inp_file)
wn_0.options.time.duration = 48*3600 
sim_0 = wntr.sim.WNTRSimulator(wn_0, mode = 'PDD')
results_0 = sim_0.run_sim()

The error I received is "RuntimeError: Exceeded maximum number of trials." I don't know if it's because my water network has issues or it has something to do with WNTRSimulator.

My WNTR version is 2.0.1.

**Comment by emmaliulu** [comment]
@michaelbynum OK. thank you for pointing this out. I'll try adding a pipe between tank and pump to see if this will solve the problem.

**Comment by emmaliulu** [comment]
@michaelbynum I added a pipe between all tanks and all connecting pumps. The model runs smoothly with EpanetSimulator, but not with WNTRSimulator. I guess the solution may be more complicated than simply adding pipes. Would you like to take a look at the modified network?

**Comment by kaklise** [comment]
This issue was resolved with #206
