### ISSUE TITLE
EPANET Error 200: On Ubuntu with example network (getting_started.py)

### ISSUE THREAD

**Issue by 4flixt** [USEPA/WNTR#112]
We setup WNTR in an Anaconda Python 3.7 environment on Ubuntu 19.04 with only WNTR package (and its dependencies) installed. The ```getting_started.py``` is throwing a 
```wntr.epanet.toolkit.EpanetException: EPANET Error 200``` which means **"one or more errors in input file."** We have not changed the input file. Running the simulation with
```python
sim = wntr.sim.WNTRSimulator(wn)
```
is successful. The report file is attached and shows that error 202, 213, 209 which all refer to illegal numerical values/options are present. Again: We have not changed the input file. We were able to successfully run the ```getting_started.py``` on a Mac with an identical setup (Anaconda Python 3.7 ...). We observed the same problem on two different Ubuntu 19.04 PCs.

[Report file (temp.rpt)](https://github.com/USEPA/WNTR/files/3771990/temp.txt)

**Comment by 4flixt** [comment]
A dirty fix for this bug seems to be to uncomment:
```python
# Graph the network
#wntr.graphics.plot_network(wn, title=wn.name)
```
Without this plot prior to the simulation everything works like a charm. 
Even just opening an empty figure with 
```python
plt.figure()
```
will throw EPANET Error 200.

**Comment by dbhart** [comment]
I would say that perhaps there is a problem with the EPANET .so library, but if that were the case, it shouldn't be running at all. I know unicode characters will break EPANET, but this should not be the case because you are right, there shouldn't be anything changing in the input file...

**Comment by 4flixt** [comment]
It was difficult to diff the original .inp file to the temp.inp file since the formating is not identical and comments are removed. I instead compared the temp.inp from a working simulation (not calling matplotlib prior to simulation) to a failed simulation (adding ```plt.figure()``` at the head of the script). Those two are identical (apart from the time stamp). I only tested Net6.inp from the examples. The resulting .inp files are appended:
[temp.txt](https://github.com/USEPA/WNTR/files/3787653/temp.txt)
[temp_fail.txt](https://github.com/USEPA/WNTR/files/3787654/temp_fail.txt)

**Comment by theh2oweb** [comment]
Hi ! First post on Github (be indulgent, let me know I did anything wrong).
Looks like locale setting is the source of the errors (at least for me).
Using **LC_NUMERIC=fr_FR.UTF-8**, I get "EPANET Error 200" when running the Getting Started demonstration.
Switching to **LC_NUMERIC=en_US.UTF-8**, no more errors.
To be accurate, I switched the Settings>Region & Language>Formats to United States on Ubuntu 20.04.
Let me know if this helps !

**Comment by dbhart** [comment]
This is correct, and I appreciate that you commented. EPANET does not work with European numeric conventions (i.e., it does not recognize 14,200 as fourteen-point-two). It only works with US representations (i.e., 14.2). This is a limitation of EPANET’s internal processing. If this can be changed, I’m not aware of it, but you could post an issue/request/question on https://github.com/OpenWaterAnalytics/EPANET. There may also be a way to do this via Python using locale settings internally.

Thank you!
