### ISSUE TITLE
Hydraulic metrics -Todini Index

### ISSUE THREAD

**Issue by jeongsoo0908** [USEPA/WNTR#114]
Hi, I have a question about hydrological metrics.

According to the source code(wntr.metrics.hydraulic), there are five factors that are calculated to calculate the Todini index, but PInRes in particular contains (-)negative values.

I don't understand this part, so please explain it.

**Comment by kaklise** [comment]
The Todini index uses reservoir discharge, which is positive when water enters the system.  Reservoir discharge is included in the simulation results as a node demand, but demand is positive when water leaves the system.  The negative value switches demand to discharge.
