### ISSUE TITLE
Pipe Vertices Setting

### ISSUE THREAD

**Issue by HaozhiTan** [USEPA/WNTR#116]
Set the vertices of the pipe like below is not working.
wntr.network.elements.Pipe('P1', 'N1', 'N2', wn).vertices = [(1,1), (2,2)]

**Comment by kaklise** [comment]
`wntr.network.elements.Pipe('P1', 'N1', 'N2', wn)` creates a new pipe object, which you can add to a water network model.  We suggest using the water network model directly and adding pipes using `wn.add_pipe`.  Once the pipe has been added to the water network model, you can set pipe vertices as follows:
```
pipe = wn.get_link('P1')
pipe.vertices = [(1,1),(2,2)]
```
Note that pipe vertices are not currently used in WNTR network graphics.
