### ISSUE TITLE
wntr Simulator issue (SI units?)

### ISSUE THREAD

**Issue by Jvss** [USEPA/WNTR#117]
I am having trouble with the wntrSimulator. My EPANET model is quite simpel containing only pipes, nodes and 1 reservoir feeding the network. The model is in SI units (with flow units CMH), which gives no problem when running the epanetSimulator, but when trying to run the wntrSimulator it gives an error: 

  File ".....\lib\site-packages\wntr\sim\core.py", line 890, in run_sim
    raise RuntimeError('Simulation did not converge. ' + mesg)
RuntimeError: Simulation did not converge. Reached maximum number of iterations: 2999

I tried to modify the flow units in WNTR directly but this could not fix the problem. I eventually find out that if I changed the units in EPANET to GPM, saved the inp file, and loaded it in wntr, the wntrSimulator was able to run it properly. I have added a figure of the inflow of the network through time when running the epanetSim and the two variants of wntrSim (DD and PDD). Though by changing the units in EPANET, the pressure throughout the network does not seem to be changing anymore in time in epanet (the pressure now changed from meters to psi). But I guess the PDD does not seem to have any problem with that?

![Figure_14(1)](https://user-images.githubusercontent.com/15999476/69977797-bc96d500-152b-11ea-8edb-0ebd39f6497e.png)

So my main question is, is the wntrSimulator not able to run properly if the INP file is in SI units? And if so, what would be a smart way of correctly changing this in my model or in wntr? Or am I doing something completely wrong? Please let me know if more details are needed.

**Comment by kaklise** [comment]
Thanks for sending in this issue.  Could you send a short example and the INP file?  If you'd rather not upload the INP file into GitHub, you can send it to kaklise@sandia.gov.

**Comment by BlomTbl** [comment]
I am running into the same problem with my hydraulic model. So I used the Net1.inp example,  changed the units from GPM to CMH, after which the problem of not converging also occurred.

**Comment by Jvss** [comment]
Yes, I compared it as well to the examples, which is how I figured out that I needed to change my model to GPM in Epanet. But indeed, the examples are having the same issues when changing the units. I have send you an email kaklise.

**Comment by kaklise** [comment]
When you change the units in the INP file, are you changing demand values?  Demand units follow flow units in EPANET INP files.  I'll look into the convergence issue.

**Comment by Jvss** [comment]
I only changed the flow units in the Hydraulics options and exported it as a new INP file. So I did not yet change any demands values, hence they are all the same as before. (but I suppose in different units now) The system flows are exactly the same, with the only difference being the label on the y-axis. But when checking the pressure through time at an arbitrary node, it shows a horizontal line in the GPM model.

**Comment by Jvss** [comment]
I believe it has something to do with the units conversion during change CMH -> GPM. 
When modifying the model in WNTR and changing to GPM (and creating a temp file to look at the results) causes a change in diameter units millimeters -> inch.
When solely changing to GPM in EPANET (saving and exporting it to a new file) and importing with WNTR yields in a conversion factor for diameter units inch -> millimeters. The same goes for length conversion factor meter -> feet (which is also used for the change of meters pressure, hence it gives you pressure in feet).
So perhaps unknowingly (drastically) changing the parameter values like this causes the conversion error?

**Comment by edalopezga** [comment]
is This problem solved? otherwise this model does not solve PDD equations.

**Comment by dbhart** [comment]
Hi @edalopezga this is resolved. We're trying to go through past issues and close them. Also, the most recent version has been completed and will be tagged as a release this week, which contains both the WNTR simulator and the new EPANET 2.2 PDD simulator as well.

**Comment by kaklise** [comment]
I believe we did not close this issue because this demonstrates cases where models are not well scaled which can cause convergence errors.  The cases described above change units conventions in the INP file without changing the actual model values.  This can create models that are very difficult to solve and we're using these to test edge cases.  Now that WNTR includes EPANET2.2, we can test out these models by comparing both simulators using DD and PDD.  I was able to recreate the figure above using the model in GPM units.  
![toyproblem_gpm](https://user-images.githubusercontent.com/17935331/97893814-00bbc800-1cef-11eb-9918-887aa1dab34e.png)

**Comment by Jvss** [comment]
Although I was working on this problem quite a while back (the epanet 2.2 not yet released), I found out that if I changed the headloss formula from DW to HW (hence I needed to change all my pipe roughness as well), this solved the issue. I hope this helps.

**Comment by kaklise** [comment]
Thanks @Jvss, I'll go ahead and close this issue.
