### ISSUE TITLE
update version number

### ISSUE THREAD

**Issue by pareyesv** [USEPA/WNTR#118]
I think the version number is not up-to-date in [`wntr/__init__.py`](https://github.com/USEPA/WNTR/blob/08e54350406117862361e71f4ec0b691e0fa9b98/wntr/__init__.py):

https://github.com/USEPA/WNTR/blob/6f08835a929498ff66a57d595ef355a469a2d73d/setup.py#L62

https://github.com/USEPA/WNTR/blob/6f08835a929498ff66a57d595ef355a469a2d73d/wntr/__init__.py#L10

See https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by kaklise** [comment]
Thanks for pointing this out.  We'll get that fixed.
