### ISSUE TITLE
changing the attribute value of a node or link in a step by step simulation

### ISSUE THREAD

**Issue by afmurillo** [USEPA/WNTR#121]
I am trying to run a step by step simulation in which an external element can change the control actions taken in the simulation. To test this, we want to see if it's possible how to change the status of a pump. 
This is the code we are using to try that, but we are not sure it is working properly. Is it possible to accomplish what we are trying to do?

import wntr

inp_file = 'minitown_map.inp'
wn = wntr.network.WaterNetworkModel(inp_file)

wn.options.time.duration=3600
wn.options.time.hydraulic_timestep=3600
wn.options.time.pattern_timestep=7200
sim = wntr.sim.WNTRSimulator(wn)

# START STEP BY STEP SIMULATION
for hour in range (0,32):
	print("HOUR: %d ------------------------" %hour)
        # We use hour 5 just to see if our changes have impact in the simulation
	if hour > 5:
		wn.get_link("PUMP1").status = wntr.network.base.LinkStatus.Closed
		wn.get_link("PUMP2").status = wntr.network.base.LinkStatus.Open

                # We guess that after chaning an attribute in wn object, we need to build the sim object 
                # again
		sim = wntr.sim.WNTRSimulator(wn)

	results = sim.run_sim(convergence_error=True)
	tank = wn.get_node("TANK")

        # We print the "new" value of the pumps to see if our changes had effect
	pump1 = wn.get_link("PUMP1")  # WNTR PUMP OBJECT
	pump2 = wn.get_link("PUMP2")  # WNTR PUMP OBJECT
	print ("TANK =", tank.level)
	print ("PUMP1 =",pump1.status)
	print ("PUMP2 =", pump2.status)

**Comment by michaelbynum** [comment]
@afmurillo What you are trying to do is definitely possible. However, to verify that you are getting the behavior you expect, you should be checking the status field of the results.link data frame rather than the status attribute on the pump object. The one caveat I should mention is that there may be interactions between the changes you are trying to make and the controls in your network. If you need to see what the controls are doing, just decrease the logging level to `logging.DEBUG`. If you have more questions on this topic, let us know.

**Comment by afmurillo** [comment]
Hello  @michaelbynum I would like to ask if this line is neccesary, after we change the pump values
sim = wntr.sim.WNTRSimulator(wn)

I do not know if I have to build a new WNTRSimulator object after I change the attribute of wn. Is the line above neccessary? Or can I just change the value of the pumps and simply call "sim.run_sim" ?

**Comment by afmurillo** [comment]
Sorry, forgot to comment again on this. What worked for us was removing and adding a new control each time the actuator state should be changed. Thank you for the great work!
