### ISSUE TITLE
Problem running the PDD simulation 

### ISSUE THREAD

**Issue by blackmamba33** [USEPA/WNTR#122]
Hello, I'm trying to run some PDD simulation with wntr. Some network work, but in some cases I've got this traceback:
"ValueError: The number of constraints and variables must be equal."
I'm using python 3.7 64 bit and anaconda.
Can someone help me?
Thanks
![Cattura](https://user-images.githubusercontent.com/60220509/72990323-40fd2a00-3df0-11ea-9f62-7a09a147651f.JPG)

**Comment by blackdiamond-max** [comment]
Hello, can you share the code you are using for **PDD**

**Comment by blackmamba33** [comment]
This is the code:

import wntr

import numpy

inp_file = 'Helmond_originalDD2.inp'

wn = wntr.network.WaterNetworkModel(inp_file)

sim = wntr.sim.WNTRSimulator(wn, mode='PDD')

results = sim.run_sim()

**Comment by kaklise** [comment]
Can you email me the inp file?  kaklise@sandia.gov
