### ISSUE TITLE
Link name mismatch between wn and results objects

### ISSUE THREAD

**Issue by bouziot** [USEPA/WNTR#123]
I have received an EPANET file that features complex alphanumeric combinations for link names. This is probably due to an import from third-party software, likely Infoworks. Links are a combination of alphanumeric characters and dots, e.g. a link name might be:
`'Xyz_VA_Sample_AB005TN04.Aanj_NY.1'`

When I try to run the model in WNTR, the simulation (using `EpanetSimulator`) finished without errors. However, in the `results` object the link names are altered and their end is truncated up to the second dot, so the previous link name example becomes: 
`'Xyz_VA_Sample_AB005TN04.Aanj_NY'`

This happens to some of the link names, perhaps the ones that feature two dots. It seems like a `rstrip()` error somewhere, or it could be a truncation from within EPANET, because the results are there and the simulation finished without errors.

As a results you cannot plot link network graphs, since the plot results in `KeyError` for the links that have this naming mismatch.

Note: Unfortunately the original epanet file cannot be shared, but the error can be reproduced if you make the link names in a topology complex enough.

**Comment by bouziot** [comment]
Edit: upon closer inspection of the mismatch it seems that the problem doesn't have to do with the character content but the **length**  - link names with length larger than 32 characters appear to be truncated to 31.

**Comment by dbhart** [comment]
Yes, this is an EPANET restriction. However, there may be ways to work around this by remapping the names on the results objects after the fact. The ordering of nodes and links should be consistent.

- Dave Hart, Sent from my iPhone

On Feb 11, 2020, at 7:18 AM, bouziot <notifications@github.com> wrote:

﻿

Edit: upon closer inspection of the mismatch it seems that the problem doesn't have to do with the character content but the length - link names with length larger than 32 characters appear to be truncated to 31.

**Comment by bouziot** [comment]
Can you point me at the easiest way to map/re-index the `results` object link names? If it behaves like a dictionary, I could try the following strategy to clone the entries and then delete the old ones. 

```
dictionary[new_key] = dictionary[old_key]
del dictionary[old_key]
```

**Comment by kaklise** [comment]
I believe that when using the EPANET simulator, the truncation can override an existing component (node or link) and have unexpected consequences beyond naming in the results object.  If this is the case, we should throw an error if component names exceed the allowable length from EPANET.

**Comment by bouziot** [comment]
I have managed to remap the names of the `results` object and plot link results as well but as @kaklise has stated, there are other implications from the truncation that render this solution not universal. For instance, there could be name clashes. Maybe another solution would be to expose a  `truncate` set of functions to the user for the `wn` object through the `utils` package, where the user would be able to see long names, get their proposed truncations (with a `wn` object update), and identify potential naming clashes.

**Comment by kaklise** [comment]
The latest update to WNTR (#218) includes basic error checking when adding components to a water network model, this includes a check to make sure the length of component names do not exceed the EPANET character limit.
