### ISSUE TITLE
Add check to enforce string for names in add_pipe

### ISSUE THREAD

**Issue by TimothyVD** [USEPA/WNTR#124]
I had a small network of 7 junctions, 1 reservoir, and 8 pipes (2 pipes are parallel), which I constructed myself based on CSV files and using the wntr commands add_junction, add_reservoir, and add_pipe.

I was able to run simulation using the epanet engine, but the WNTR engine did not work. My problem was that I did not properly convert my node IDs (which were just numbers) to strings in the add_pipe function. 

Incorrect code (3 is written as `int` and not as `str`):
`wn.add_pipe('2_3', '2', 3)`
Correct code:
`wn.add_pipe('2_3', '2', '3')`

I was wondering whether there is already functionality to check whether all nodes are connected? And whether the system check if you are trying to add a pipe to an unknown node? Since it took me some time to discover the origin of my issue, because I only received an error during running the simulation (Jacobian was singular).

Thanks!
Timothy

**Comment by kaklise** [comment]
I was not exactly able to replicate this error.  When adding a node, the ``NodeRegistry`` checks to make sure the node name is a string and when adding a pipe, the start and end node must already exist.  That said, we should include additional assert statements to check argument types.  

The network does not need to be fully connected to use the ``WNTRSimulator``, but you can check if the network is fully connected using the NetworkX graph (``G = wn.get_graph()``) and the NetworkX method ``connected_components``.

**Comment by TimothyVD** [comment]
Thanks for your input. Sorry for the delay, but I compiled a small working example to further clarify the issue above.

```
import wntr
import networkx

def make_model(node_ref_type):
    # WNTR container
    wn = wntr.network.WaterNetworkModel()
    
    # Add nodes
    wn.add_reservoir('FH_1', base_head=50., coordinates=(0,0))
    wn.add_junction('1', base_demand=4./3600.,# demand_pattern='pat1',
                    elevation=18.0, coordinates=(0,100))
    
    # Define the type of node 1 (str or int)
    node_ref = node_ref_type(1)
    # Add pipe between nodes
    wn.add_pipe('FH1_1', 'FH_1', node_ref,
                length=100., diameter=0.200, roughness=60.,
                minor_loss=0.0, status='OPEN')
    
    return wn

def run_model(simulator_type, node_ref_type):
    wn = make_model(node_ref_type)
    sim = simulator_type(wn)
    results = sim.run_sim()
    return wn, results

results = None
simulator_types = [wntr.sim.EpanetSimulator, wntr.sim.WNTRSimulator]
for simulator_type in simulator_types:
    try:
        node_ref_type = int
        wn, results = run_model(simulator_type, node_ref_type)
    except:
        node_ref_type = str
        wn, results = run_model(simulator_type, node_ref_type)
    G = wn.get_graph().to_undirected()
    conn_components = list(networkx.connected_components(G))
    print('{} was run using {} with connected comp: {}'.format(simulator_type, node_ref_type, conn_components))
```

Which yields the following output:
```
<class 'wntr.sim.epanet.EpanetSimulator'> was run using <class 'int'> with connected comp: [{'1', 'FH_1'}]
<class 'wntr.sim.core.WNTRSimulator'> was run using <class 'str'> with connected comp: [{'1', 'FH_1'}]
```
The above indicates that EpanetSimulator is successfully running, while the WNTRsimulator cannot handle the integer (which makes sense I think). However, the errors which pop up are:
`RuntimeError: Simulation did not converge. Line search failed at iteration ...` or `TypeError: 'NoneType' object is not iterable`.

Probably a property setter decorator would be the forward or what is your thought about this?

**Comment by kaklise** [comment]
Thanks for posting an example.  We certainly need to add assert statements to check data types.  I would also expect an error when adding a pipe using an end node that doesn't exist (using a node named int(1)).  I believe that the EpanetSimulator runs successfully because it writes the water network model to a file, and at that point, the name is a string.  The WNTRSimulator uses the water network model directly and fails when the node name is an integer.  We'll work on these updates.

**Comment by kaklise** [comment]
The latest update to WNTR (#218) includes basic error checking when adding components to a water network model, this includes checking that names are strings
