### ISSUE TITLE
Skeletonization

### ISSUE THREAD

**Issue by bahadurr** [USEPA/WNTR#128]
I am using WNTRMorphSkel.py script for Skeletonization. The issue is with the aggregation of nodal base demands. Total aggregated base demand for all nodes should remain same even after Skeletonization. But in my test example, the script captures only 10% of the demand. The demands after Skeletonization do not get aggregated and assigned to nodes correctly. I I am using 16 inch pipe diameter for Skeletonization. 

Total   Demand MGD (aggregate of all nodal base demands) - 
All pipe model 271.49 MGD
Skeltonized Model 30.29 MGD

Thanks for your help

**Comment by kaklise** [comment]
Are you able to share your script and network model?  You can email the files to kaklise@sandia.gov if you would rather not post the files here.

**Comment by bahadurr** [comment]
Katherine

I can share the script (attached) but the network model I cannot because of obvious reasons. The model input file was given to me by Robert Janke from EPA Cincinnati.

I tried the same script with NET6.inp file that is packaged with WNTR and getting the same results. The script can be tested on NET6.inp file if it helps

Rakesh Bahadur, Ph.D., PMP | Leidos
MS FS 1-5-1
11951 Freedom Drive
Reston, VA 20190
phone: 571.526.7120
bahadurr@leidos.com<mailto:bahadurr@leidos.com>  |  leidos.com

[cid:image001.png@01CF9B6D.2D0979D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by bahadurr** [comment]
Katherine

You may not get the attachment as Outlook sometimes strips the python scripts. If that is case then let me know if I can upload the script for you

Rakesh Bahadur, Ph.D., PMP | Leidos
MS FS 1-5-1
11951 Freedom Drive
Reston, VA 20190
phone: 571.526.7120
bahadurr@leidos.com<mailto:bahadurr@leidos.com>  |  leidos.com

[cid:image001.png@01CF9B6D.2D0979D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by kaklise** [comment]
I don't see the attached file, but I can provide an example using Net6 to start the discussion.

The issue might be explained by how demands are extracted from the original and skeletonized model.  Within the skeletonization process, base demands and demand patterns are moved to remaining nodes. We can compute total demand at each junction and time using base demands, demand patterns, and the demand multiplier to make sure demands are conserved (using `wntr.metrics.expected_demand`).  If we just extract the base demand (using `query_node_attribute`), the results will be different because this does not account for the multiple demands and patterns on each junction.

In the following example, Net 6 is skeletonized using a 16 inch pipe diameter threshold.  The total expected demand is conserved (130.42 m3/s) but the base demands differ.  Does this explain the issue you are seeing?

```
import wntr

# Create a water network model
orig_wn = wntr.network.WaterNetworkModel('networks/Net6.inp')
print(orig_wn.describe())

# Skeletonize the model using a 16 inch pipe diameter threshold
skel_wn = wntr.morph.skeletonize(orig_wn, 16*0.0254)
print(skel_wn.describe())

# Extract the expected demand for each water network model
# This uses base demand, demand pattern, and the demand multiplier
# Expected demand for both models should be the same
orig_expected_demand = wntr.metrics.expected_demand(orig_wn)
skel_expected_demand = wntr.metrics.expected_demand(skel_wn)

orig_expected_demand.sum(axis=1).plot() # plot timeseries of total demand
skel_expected_demand.sum(axis=1).plot()

print(orig_expected_demand.sum().sum()) # print total demand
print(skel_expected_demand.sum().sum())

# Extract the base demand for each water network model
# The base demand will not be the same
orig_base_demand = orig_wn.query_node_attribute('base_demand')
skel_base_demand = skel_wn.query_node_attribute('base_demand')

print(orig_base_demand.sum()) # print total base demand
print(skel_base_demand.sum())
```

**Comment by bahadurr** [comment]
Katherine

I changed the extension of the script from .py to .txt and resending. Hopefully this file won’t be stripped by Outlook.  You may want to change the extension back to .y to run it.

My understanding is that the Base demand for the whole model (not individual nodes) should remain same before and after Skeletonization.



Rakesh Bahadur, Ph.D., PMP | Leidos
MS FS 1-5-1
11951 Freedom Drive
Reston, VA 20190
phone: 571.526.7120
bahadurr@leidos.com<mailto:bahadurr@leidos.com>  |  leidos.com

[cid:image001.png@01CF9B6D.2D0979D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by kaklise** [comment]
We preserve the original base demand values and demand patterns when combining junctions in the skeletonization process.  We should clarify this in the user manual.  You could aggregate these into new base demands and demand patterns for each junction, but this could potentially create many new patterns, and makes debugging difficult.

**Comment by bahadurr** [comment]
Katherine

I think I know the issue. The small script you have sent to me converts pipe diameter from INCHES to METERS. I was using simple inch as there was no mention of the conversion in the manual. It is working fine and giving me reasonable results. I will now compare the original model with the skeletonized model

skel_wn = wntr.morph.skeletonize(orig_wn, 16*0.0254)


Thanks again for all your help

Rakesh Bahadur, Ph.D., PMP | Leidos
MS FS 1-5-1
11951 Freedom Drive
Reston, VA 20190
phone: 571.526.7120
bahadurr@leidos.com<mailto:bahadurr@leidos.com>  |  leidos.com

[cid:image001.png@01CF9B6D.2D0979D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by kaklise** [comment]
I'm glad to hear that it's working.  WNTR uses SI units throughout the software.  https://wntr.readthedocs.io/en/latest/units.html

**Comment by bahadurr** [comment]
Katherine

I am getting the following Waning:

UserWarning:

Not all curves were used in "C:\WNTR\Testing_Script/Texas_Example2_Testing_FOUO.inp"; added with type None, units conversion left to user

What does it mean?

Thanks again for all your help today

Rakesh Bahadur, Ph.D., PMP | Leidos
MS FS 1-5-1
11951 Freedom Drive
Reston, VA 20190
phone: 571.526.7120
bahadurr@leidos.com<mailto:bahadurr@leidos.com>  |  leidos.com

[cid:image001.png@01CF9B6D.2D0979D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by dbhart** [comment]
Hi Rakesh,

This warning means that for things like energy curves, we don’t use them in WNTR so we leave them alone. We assign curves their properties (pump, energy, etc.) based on what elements they get assigned to (pump-head, tank-volumes). So if there is a curve that never gets used, or which is an energy curve, we put this warning in there so the user knows that there may be a curve we didn’t identify the units for, so we left them alone. Hopefully that makes sense.

Dave H.
