### ISSUE TITLE
Topological metrics - Weight_graph

### ISSUE THREAD

**Issue by jeongsoo0908** [USEPA/WNTR#130]
According to the manual provided, It is stated that NetworkX can use weighted graph. 
If I consider the flowrate(Link attribution) as a weight using weighted graph, 
I'm wondering that how to calculate the weight.
Can you explain about this?

Please reply.
Thank you.

**Comment by kaklise** [comment]
You can weight the NetworkX graph by flowrate using the following example.  The example uses flowrate at 1 hour.  This example uses recent updates in WNTR 0.2.2.

```
import wntr
inp_file = 'networks/Net3.inp'
wn = wntr.network.WaterNetworkModel(inp_file)
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()
flowrate = results.link['flowrate'].loc[3600,:]
G = wn.get_graph(link_weight=flowrate)
```
If you want to return a weighted graph where the link directions are defined by flow direction, set `modify_direction` to True
```
G2 = wn.get_graph(link_weight=flowrate, modify_direction=True)
```
You can check the results as follows:
Flowrate on pipe 175 is positive (flow from start node to end node)
Flowrate on pipe 149 is negative (flow from end node to start node)
```
print(flowrate['175']) 
print(flowrate['149'])
```
In the NetworkX graph G, weight is equal to flow
```
print(G['157']['159']) # pipe 175
print(G['143']['141']) # pipe 149
```
In the NetworkX graph G2, weights are all positive and the start and end node are reversed if flow is negative
```
print(G2['157']['159']) # pipe 175
print(G2['141']['143']) # pipe 149
```

**Comment by jeongsoo0908** [comment]
Thank you for your reply,  but what I'm curious about is process of creating a weighted graph.

Could you explain it to me?

**Comment by kaklise** [comment]
A weighted graph just assigns a value to links and/or nodes.  These weights can be used in topographic calculations.  For example, if you want to compute a path length through a network, you'd want to weight each link by it's pipe length.   If you computed path length using an unweighted graph, the result would in number of links instead of total pipe length.

**Comment by ziedbouf** [comment]
Hi @kaklise, @jeongsoo0908  sorry to jump in directly on the same thread. I am trying to compute the pairwise distance  between all nodes  but for some reasons it seems i am mistaking (as i am newbie to this field):
`G = wn.get_graph(link_weight='length', modify_direction=True)` 

```training_nodes = sensors[:20]
print(training_nodes)

['n1', 'n4', 'n31', 'n54', 'n105', 'n114', 'n163', 'n188', 'n215', 'n229', 'n288', 'n296', 'n332', 'n342', 'n410', 'n415', 'n429', 'n458', 'n469', 'n495']
```

```
testing_nodes = senors[21:]
print(testing_nodes)


result: ['n516', 'n519', 'n549', 'n613', 'n636', 'n644', 'n679', 'n722', 'n726', 'n740', 'n752', 'n769']
```

```
other_nodes = (set(G.nodes) - set(training_nodes)) - set(testing_nodes)
other_nodes = list(other_nodes)
other_nodes.sort()
```

```
pl.figure(0, figsize = [40, 40])
#node positions
pos = nx.kamada_kawai_layout(G)

# draw nodes
nx.draw_networkx_nodes(G, pos, with_labels=True, node_size=400, nodelist=training_nodes, node_color="r")
nx.draw_networkx_nodes(G, pos, with_labels=True, node_size=400, nodelist=testing_nodes, node_color="b")
nx.draw_networkx_nodes(G, pos, with_labels=True, node_size=400, nodelist=other_nodes, node_color="g")

#draw edges
ec = nx.draw_networkx_edges(G, pos, alpha=0.2)

#legend
labels = nx.draw_networkx_labels(G, pos=pos, font_color='k')
red_patch = mpatches.Patch(color='red', label='training nodes')
blue_patch = mpatches.Patch(color='blue', label='testing nodes')
green_patch = mpatches.Patch(color='green', label='other nodes')
pl.legend(handles=[red_patch, blue_patch, green_patch])
```

<img width="1047" alt="Screen Shot 2020-03-29 at 21 55 58" src="https://user-images.githubusercontent.com/5924038/77857752-27b99500-7208-11ea-919b-63afe6ae335d.png">

Looking to the graph, i cannot see any disjoint sections and i am expecting all coefficients of the matrices of pairwise shortest distances between nodes are non null, however this is not right and i have no idea why:

```
G = wn.get_graph(link_weight='length')
shortest_path_length = nx.all_pairs_dijkstra_path_length(G)
dist = pd.DataFrame(dict(shortest_path_length)).sort_index(axis=1)
dist
```
And i got the following result where most of the coefficient are NAN:
<img width="1095" alt="Screen Shot 2020-03-29 at 21 59 39" src="https://user-images.githubusercontent.com/5924038/77857837-aadaeb00-7208-11ea-8773-030ceba67f08.png">

I think i am missing something  and i would really appreciate your help and guidelines on this

**Comment by ziedbouf** [comment]
sorry stupide mistake on my end forgot to generate an undirected graph, i am surprise it on the way the graph is generated as directed graph? and basically the shortest distances matrices end up to be not positive defined which another problem to deal with more  @theoretical point of view 😞

**Comment by kaklise** [comment]
Thanks for the update.  Water network models are defined as directed graphs to preserve information regarding the start and end node of links.  This information is used to define the direction of valves and pumps.

**Comment by ziedbouf** [comment]
Thanks @kaklise i see, but does this should be under the control level. What i mean is that from physical point of view it's not related to the pressure distribution in the network itself, is this assumption right?

**Comment by kaklise** [comment]
This information could be defined at the controls level, but WNTR retains the start and end node conventions defined in EPANET.  This does have an impact on network pressure in a hydraulic simulation.  As you mentioned above, topographic paths can be computed using an undirected graph.  You could also create directed graphs based on other attributes, like flow direction.

**Comment by ziedbouf** [comment]
I wonder if there are any place where where we could have  these type of discussions and subjects 🤔as i am exploring this field and i am interested in learning more on the physics and application related to this.

Thank you some @kaklise
