### ISSUE TITLE
distributed processing

### ISSUE THREAD

**Issue by ziedbouf** [USEPA/WNTR#132]
Thanks For the USEPA community on creating such an amazing library. I would like to ask if there are any distributed computation framework such as [dask](https://dask.org/) or [ray](https://rise.cs.berkeley.edu/projects/ray/)  used by USEPA to run large scale simulation done.

**Comment by pshassett** [comment]
Depending on the processing capabilities you have available, the [python multiprocessing library](https://docs.python.org/3.8/library/multiprocessing.html#module-multiprocessing) could be a useful option.  I have used it in applications of WNTR to execute sets of ~3000 simulations in parallel.  If you are interested I would be happy to share my methods.

**Comment by dionikolop** [comment]
That would be very interesting!

**Comment by ziedbouf** [comment]
@pshassett  that's very interesting and it would be nice start to see how we distribute simulations.

**Comment by pshassett** [comment]
Take a look at [this function](https://github.com/pshassett/CriticalityMaps/blob/97b864f56333c0e30a95d01e8d6143048dbaaedd/criticalityMaps/criticality/mp_queue_tools.py#L24) that takes a list of (function, args) tuples as input and returns all of the results objects of your function in a list. By default this uses 2/3 of the processors on the machine but can be manually specified with the `num_processors` argument. This could be copied and modified to meet the output format of your applications.

This is of course just one approach, I am sure there are numerous more efficient and scalable methods for higher performance.

**Comment by ziedbouf** [comment]
thanks @pshassett yes this one approach for one single machine is valid and specially when using high end computation machine on the cloud.
