### ISSUE TITLE
Weighted graph

### ISSUE THREAD

**Issue by jpark7926** [USEPA/WNTR#133]
Hi, I'm curious about creating a weighted graph.

For example, if I want to compute a Betweenness centrality through a network, I want to weight each link using flowrate results.

I applied weights to calculate a Betweenness centrality(weighted : flowrate), but we would like to hear an explanation of how the weighted graph results are calculated.

If you possible, I would appreciate it if you could explain it through the Net1.

Please reply, Thank you

**Comment by kaklise** [comment]
There is an example in #130 that creates a weighted graph using flowrate on Net3.  I believe that the NetworkX method to compute betweenness centrality requires a simple graph (which can be weighted, but can only have one link between nodes).  If your network has multiple links between nodes, you can reduce this to a simple graph using `simple_graph = nx.Graph(multi_graph)`.  

The WNTR documentation includes an example to compute betweenness centrality from a graph. https://wntr.readthedocs.io/en/latest/resilience.html#topographic-metrics

**Comment by jpark7926** [comment]
Thank you for your answer :)
