### ISSUE TITLE
plot_network function does not scale colorbar based on link values, only node

### ISSUE THREAD

**Issue by tyjchen** [USEPA/WNTR#135]
I was trying to plot some link attributes using the plot_network() function from the wntr.graphics.network module, but notice that the colorbar setting only changes for nodal attributes and not links.
Specifically, when I set node_attributes to none and try to plot the data in link_attributes, the colorbar is only displayed to range between 0-1 no matter what. Is there any way around this?

**Comment by kaklise** [comment]
Can you include a simple example, perhaps using one of the networks in the example folder?

**Comment by JremySch** [comment]
I have the same request. 
The option _link_range=[]_ change the scale color in graphic but doesn't change the scale of colorbar. The code below use the Net3.inp as you request. 

`import wntr
import matplotlib.pyplot as plt
# Create a water network model
inp_file = 'networks/Net3.inp'
wn = wntr.network.WaterNetworkModel(inp_file)

# Simulate hydraulics
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

# Plot results on the network
pressure_at_5hr = results.node['pressure'].loc[5*3600, :]
flow_at_5hr = results.link['flowrate'].loc[5*3600, :]

Fig, Axarr = plt.subplots(1,2,figsize=(12,4))
Ax0 = Axarr[0]
wntr.graphics.plot_network(wn,
                           node_attribute=pressure_at_5hr,
                           node_size=30, node_range = [0,50],
                           title='Pressure',
                           node_colorbar_label='Pressure (bar)', ax=Ax0)

Ax1 = Axarr[1]
wntr.graphics.plot_network(wn,
                           link_attribute=flow_at_5hr,
                           node_size=10,link_width=3, link_range= [0,100],
                           title='Flow',
                           link_colorbar_label='Flow (l/s)', ax=Ax1)`

**Comment by JremySch** [comment]
I have the same request. 
the code below use the example Net3.  
```
import wntr
import matplotlib.pyplot as plt
# Create a water network model
inp_file = 'networks/Net3.inp'
wn = wntr.network.WaterNetworkModel(inp_file)

# Simulate hydraulics
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

# Plot results on the network
pressure_at_5hr = results.node['pressure'].loc[5*3600, :]
flow_at_5hr = results.link['flowrate'].loc[5*3600, :]*1000 

Fig, Axarr = plt.subplots(1,2,figsize=(12,4))
Ax0 = Axarr[0]
wntr.graphics.plot_network(wn,
                           node_attribute=pressure_at_5hr,
                           node_size=30, node_range = [0,50],
                           title='Pressure',
                           node_colorbar_label='Pressure (bar)', ax=Ax0)

Ax1 = Axarr[1]
wntr.graphics.plot_network(wn,
                           link_attribute=flow_at_5hr,
                           node_size=10,link_width=3, link_range= [0,100],
                           title='Flow',
                           link_colorbar_label='Flow (l/s)', ax=Ax1)
```

**Comment by kaklise** [comment]
Thanks.  This is a NetworkX issue, see https://github.com/networkx/networkx/pull/3698.  Looks like the fix will be included in the NetworkX 2.5 release.  I'm not sure what their release schedule is.  If this is an issue, we can think about adding a patch in WNTR.  If you clone NetworkX from GitHub, you should get the following figure.  
![Figure_1](https://user-images.githubusercontent.com/17935331/81712523-ed136100-9431-11ea-888e-70440a7a8087.png)

**Comment by JremySch** [comment]
Thanks. I just cloned the networkX (version 2.4) from Github using Python 3.7.6. I run your code from #3698 and I get the same issue as in the figures below. 

![Figure_1](https://user-images.githubusercontent.com/63313855/81720946-608f8f80-947f-11ea-8845-e6c0bf87d8e0.png)

![Figure_2](https://user-images.githubusercontent.com/63313855/81720970-684f3400-947f-11ea-9da8-21db17aa72a3.png)

**Comment by kaklise** [comment]
The NetworkX updates are currently in master, and not part of a tagged release.  Until the next NetworkX release, we should probably include this in WNTR.

**Comment by JremySch** [comment]
I fixed it. I added the two lines of code by hand in the networkx/drawing/nx_pylab.py file. I don't know why when I cloned I didn't get the same result. Thank you again.

**Comment by kaklise** [comment]
The recent release of NetworkX 2.5 resolves this issue.
