### ISSUE TITLE
Value Error using Sensor Placement Algorithm

### ISSUE THREAD

**Issue by carlos-p14** [USEPA/WNTR#136]
I'm having some trouble testing the sensor placement algorithm. When I tested the files Net1.inp and Net2.inp everything went fine, but when I changed to my network, which is a little bit bigger than the other two (dunno if this is relevant), something wrong happened. The error message was "ValueError: zero-size array to reduction operation maximum which has no identity". 

What should I do to solve this problem? Is it some kind of problem with my network? It is in LPS instead of GPM.

**Comment by kaklise** [comment]
Do you know if the simulations created the data needed for the sensor placement optimization? Can you send the stack trace?

**Comment by carlos-p14** [comment]
To be honest, I don't know what the algorithm has created, but the
procedure was very similar to the other one examples. It printed all the
nodes names, but when it was supposed to print the network with the sensors
placed, the error message appeared.

I don't how I could send you the stack trace, but I can send you the
network I'm working on and the algorithm I´m using too (even though I have
just downloaded it from GitHub), if you wouldn't mind, of course. Could it
be that way?

Em seg, 27 de abr de 2020 17:49, Katherine Klise <notifications@github.com>
escreveu:

**Comment by kaklise** [comment]
Feel free to send the network file.  I also suggest reviewing the sensor placement documentation at https://chama.readthedocs.io to better understand the requirements.

**Comment by carlos-p14** [comment]
Okay, so this is the network I'm using.

I appreciate your colaboration and thank you very much for your attention
and the link, it will be very helpful :).

Em ter., 28 de abr. de 2020 às 15:31, Katherine Klise <
notifications@github.com> escreveu:

**Comment by kaklise** [comment]
The file was not attached.  Feel free to email the file to kaklise@sandia.gov.

**Comment by kaklise** [comment]
Changing the INP time option to use a simulation duration longer than 0 resolved the issue.
