### ISSUE TITLE
[BUG Report]Function "assign_demand" doesn't work

### ISSUE THREAD

**Issue by 1-1-2** [USEPA/WNTR#137]
I was following the [instrution](https://wntr.readthedocs.io/en/latest/waterquality.html#using-pdd) and found that the function didn't work as expected. The node demands didn't make any change, while the new pattern was added to the network model.
In this function, it check if the node has attribute "demands",  which a junction nor other node doesn't have(maybe in the old version it had?). 
```python
    def assign_demand(self, demand, pattern_prefix='ResetDemand'):
            ....
            # Reset base demand
            if hasattr(node, 'demands'):
                node.demands.clear()
                node.demands.append((1.0, pattern, 'PDD'))
```

I think in this version checking the "demand_timeseries_list" attribute maybe the right choice and this part need to be rewrite/fix.

Sincerely yours.

**Comment by 1-1-2** [comment]
Here's the code i think it might be right.

```python
    def assign_demand(self, demand, pattern_prefix='ResetDemand'):

        for node_name, node in self.nodes():
            
            # Extract the node demand pattern and resample to match the pattern timestep
            demand_pattern = demand.loc[:, node_name]
            #demand_pattern.index = demand_pattern.index.astype('timedelta64[s]')
            demand_pattern.index = pd.TimedeltaIndex(demand_pattern.index, 's')
            resample_offset = str(int(self.options.time.pattern_timestep))+'S'
            demand_pattern = demand_pattern.resample(resample_offset).mean() / self.options.hydraulic.demand_multiplier

            # Add the pattern
            pattern_name = pattern_prefix + node_name
            self.add_pattern(pattern_name, demand_pattern.tolist())
            pattern = self.get_pattern(pattern_name)

            # Reset base demand
            if hasattr(node, 'demand_timeseries_list'):
                node.demand_timeseries_list.clear()
                node.demand_timeseries_list.append((1.0, pattern, 'PDD'))
```

+ change 1:

```python
            demand_pattern = demand_pattern.resample(resample_offset).mean() / self.options.hydraulic.demand_multiplier
```

Cause the "demand_multiplier" may not be set 1.0 in the network model. Yeah, i happen to using a not 1.0 network model and it confuse me for a whole hour for wrong demand result.
A better solution maybe add a switch to the function and set to True by default. Or it maybe an float and set 1.0 by default.

+ change 2:

```python
            # Reset base demand
            if hasattr(node, 'demand_timeseries_list'):
                node.demand_timeseries_list.clear()
                node.demand_timeseries_list.append((1.0, pattern, 'PDD'))
```

Try to make it right, and things works well in my test.


Sorry for my bad English, for it's not my mother tongue. Love you guys for your work!

**Comment by kaklise** [comment]
Thanks for pointing this out.  I agree that this function needs to be updated to use the demand timeseries list and use the demand multiplier.  I'll try to get this integrated into the master branch soon.
