### ISSUE TITLE
python-3.8 support

### ISSUE THREAD

**Issue by jjstickel** [USEPA/WNTR#140]
I tried using with python-3.8 on Mac (using setup.py to install). When importing `wntr`, I get the error:

`ModuleNotFoundError: No module named 'wntr.sim.aml._evaluator'`

Browsing the sources, it looks like this might be due to the absence of the file `wntr/sim/aml/_evaluator.cpython-38m-darwin.so`, and so I presume python-3.8 is not yet supported? How would that file be generated?

**Comment by kaklise** [comment]
We hope to support Python 3.8 soon.  There are two steps: updating the conda-forge build for the aml module and then updating the travis config to run the 3.8 tests.  When we looked at this a while back, some of the dependencies did not support 3.8, but that has probably changed.  We'll try to look at this again soon.

**Comment by jjstickel** [comment]
OK, thanks for the update.

**Comment by kaklise** [comment]
The dev branch now supports Python 3.8.  The [release notes](https://github.com/USEPA/WNTR/blob/dev/documentation/whatsnew/v0.2.3.rst) include additional information on code updates.

**Comment by kaklise** [comment]
The master branch now supports Python 3.8
