### ISSUE TITLE
Set diameters with epanettools, from a csv

### ISSUE THREAD

**Issue by nando1988** [USEPA/WNTR#142]
I am trying to set the values of the diameters in a inp file, and save them to another file.
I ran the code and compared the diameters, and it seems that only the first one changed and it didn't change to the value I set in the csv.
Can someone please help me with this issue?
Thanks.

`
#importar dependencias
import PySimpleGUI as sg
from  epanettools.epanettools import EPANetSimulation, Node, Link, Network, Node
import setPROPERTY
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import math
from matplotlib import pyplot
import os
import tkinter
import _tkinter
import warnings
from tkinter.filedialog import askopenfilename

root = tkinter.Tk()
root.withdraw()
#os.chdir('D:\Works\Estudios\Epanet y Python\Proyectos\Epanet Files')
file=askopenfilename(filetypes=[('.csvfiles', '.inp')],
                                        title='Seleccione el proyecto de EPANET')
es=EPANetSimulation(file) # creamos el objeto que tendra las caracteristicas de la red
es.run()
#Obtener informacion de los nodos
nodos=es.network.nodes
cond=es.network.links
print('ID Conductos')
lista_IDCond=list(es.network.links[x].id for x in cond)
print(lista_IDCond)
diametros=Link.value_type['EN_DIAMETER']
diam_81_A=list([es.network.links[i].results[diametros] for i in cond])
print('DIametros de Tuberias: ',diam_81_A)
p=Node.value_type['EN_PRESSURE']
pt=list([es.network.nodes[i].results[p] for i in nodos])
print('Presiones actuales: ',pt)
file2=askopenfilename(filetypes=[('.csvfiles', '.csv')],
                                        title='Seleccione el archivo CSV con los diametros del proyecto')
xl=pd.read_csv(file2)
#print(xl.sheet_names)
df1=pd.DataFrame(xl)
f='D:\Works\Estudios\Epanet y Python\Archivos\inp\Modificados Python\modificado.inp'
warnings.simplefilter(action='ignore', category=FutureWarning)
for row in df1.iterrows():
    #print('Colunm Name : ', df)
    #print('Column Contents : ', df1.loc[i,'Diamteros'])
    #for j in cond:
        #if row['No']==es.network.links[j].id:
    #print(entro)
    r=es.ENsetlinkvalue(1,diametros,float(row['Diametros']))#Cambio los diametros de los tubos
    es.ENsaveinpfile(f)
ee=EPANetSimulation(f) 
ee.run()# creamos el objeto que tendra las caracteristicas de la red
for i in nodos:
    print('Diamtero actual: ',es.network.links[i].results[diametros],' : Diametro actualizado: ',ee.network.links[i].results[diametros])
`

**Comment by kaklise** [comment]
I suggest posting this issue on the epanettools GitHub page
