### ISSUE TITLE
Method for calculation of Betweenness centrality

### ISSUE THREAD

**Issue by jeongsoo0908** [USEPA/WNTR#146]
I have a question about calculating the betweenness centrality.
If you look at the manual or the explanation on the website, it says that we can consider the weight when calculating the betweenness centrality.

ex :  >>> length = wn.query_link_attribute('length')
        >>> wG = wn.get_graph(wn, link_weight=length) 

If the weight of the flowrate is set as the weight for calculating the betweenness centrality, it is expected that the code can be written as follows.

ex :  >>> flowrate = results.link['flowrate']
        >>> G2 = wn.get_graph(wn, link_weight=flowrate, modify_direction=True) 
        >>> betweenness_centrality = nx.betweenness_centrality(G2)

However, the calculated results do not seem to give proper weight consideration.
If i inverse operation about betweenness centrality, the results of the normalization have been shown.
So, I would like to know how to take into account the weight when using the method of betweenness centrality.
Please reply.
Thank you.

**Comment by kaklise** [comment]
The NetworkX betweenness_centrality function includes an input parameter to use weight, but the default value is None.  To use the weights , you need to include the edge weight name , in this case``nx.betweenness_centrality(G2, weight="weight")``

**Comment by jeongsoo0908** [comment]
Thank you for your answer.

In my case I would like to consider the flowrate as a weight to calculate the betweenness centrality.
According to you, after performing the PDD analysis, I understand that weight can be flowrate.

But, I've already done what you mentioned.(nx.betweenness_centrality(G2, weight="weight"))
ex : nx.betweenness_centrality(G2, weight="flowrate", modify_direction=True)
      nx.betweenness_centrality(G2, weight="lentgth", modify_direction=True)

What I'm curious about here is that I entered different weights, but the results of calculating the betweenness centrality are the same.
These results are judged to be poorly weighted.

I'll wait for a good answer.
Thank you.

**Comment by kaklise** [comment]
I think the problem is with MultiDiGraphs.  NetworkX betweenness_centrality used to operate on MutliDiGraph (the object type returned by WNTR get_graph) but recent updates in NetworkX do not allow for this.  I'm surprised that an error is not thrown, but I was able to reproduce the issue you're seeing where the calculation is the same with and without weights.  

The following example produces different values for betweenness centrality with and without weights. 
```
import wntr
import networkx as nx

inp_file = 'networks/Net3.inp'
wn = wntr.network.WaterNetworkModel(inp_file)
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()
flowrate_at_hr5 = results.link['flowrate'].loc[5*3600, :]
G = wn.get_graph(wn, link_weight=flowrate_at_hr5, modify_direction=True)
simple_graph = nx.Graph(G)

bc = nx.betweenness_centrality(simple_graph)
wntr.graphics.plot_network(wn, node_attribute=bc)

bc_weighted = nx.betweenness_centrality(simple_graph, weight='weight')
wntr.graphics.plot_network(wn, node_attribute=bc_weighted)
```

**Comment by jeongsoo0908** [comment]
If the weight is set to flowrate when calculating the Betwiness centrality, it is expected that the cutting point located in front of the drain will be of the highest importance.
However, the results are located in the center, so I would appreciate it if you could explain why.

**Comment by kaklise** [comment]
I suggest stepping through the algorithm, documented on the NetworkX site: https://networkx.github.io/documentation/stable/reference/algorithms/centrality.html#shortest-path-betweenness. NetworkX also includes functions for edge betweenness centrality and betweenness centraility using specific sources and sinks, which might be of use.

**Comment by kaklise** [comment]
After using betweenness centrality for a different application, I realized that flowrate needs to be inverted in the example above to get the desired results.  Betweenness centrality is a measure of shortest paths that pass through a node.  To make sure that high flowrate correlates with short paths, you can use 1/flowrate as the weight. In the example above, you could define G as follows.
`G = wn.get_graph(wn, link_weight=1/flowrate_at_hr5, modify_direction=True)`
