### ISSUE TITLE
EPANET Error 200 - I need to do many Iterations

### ISSUE THREAD

**Issue by JoseVinicius1998** [USEPA/WNTR#149]
Hello, I'm a student of electrical Engineering and I'm making a algorithm of optimization for calibration of a WDS. However, 
I am not able to do iterations, it always gives the error 200, in the method "run_sim()".  It's like he can only iterate. How Can i solve this problem?

Note: I call a function inside the loop that does the simulation

**Comment by dbhart** [comment]
EPANET error 200 means there are errors in the INP file. I would look in the .rpt file that is created to try to find the errors, or try to load it into the EPANET GUI to see if it will tell you where the error is.

**Comment by JoseVinicius1998** [comment]
Thanks very much dbhart. Your tip was valuable. The problem was some negative roughness after the first iterate to my algorithm. Your help was providential. Thanks so much!!!
