### ISSUE TITLE
Error 305 - I need to do a lot of iterates

### ISSUE THREAD

**Issue by JoseVinicius1998** [USEPA/WNTR#150]
Hello, I'm a student of electrical Engineering and I'm making a algorithm of optimization for calibration of a WDS. However,
I am not able to do many iterates, it always gives the error 305. It's like he can only limited iterates. How Can i solve this problem? Is there a workaround for this?

**Comment by GalPerelman** [comment]
Hi,
Error 305 stands for "cant open the hydraulic file" (inp file), see [here](http://epanet.de/documentation/errorcodes.html.en) for error codes
Does the inp file is changed throughout your simulation?
Do you close open files after every iteration?

**Comment by kaklise** [comment]
I believe this is related to issue #115 and should be resolved using EPANET 2.2.  The dev branch of WNTR now supports EPANET 2.2.  We plan to merge this into master and tag the release later this summer, but it is ready for use now.

**Comment by JoseVinicius1998** [comment]
Hi,
Thank you very much for the suggestions. So, i solve my problem updating the version of my python. Now, I'm using the python 3.8.1 with epanet 2.2 as well.

**Comment by Sabrinasc360** [comment]
Olá José, eu estou com o mesmo problema que o seu. Você conseguiu resolver? se sim, me conta como?

Hi José, I have the same problem as yours. Did you manage to solve? if so, tell me how?

**Comment by JoseVinicius1998** [comment]
Oi Sabrina. Resolvi mais ou menos. Eu pensei ter resolvido utilizando as versões de python e epanet que disse acima. Mas após várias "brincadeiras" eu meu código, percebi que não. Mas um jeito que funcionava sem problemas era quando se deletava todos os aquivos gerados pelo python antes de cada rodagem do código, mas não era sempre que funcionava. Se descobrir outra forma ficarei grato também.


Hi Sabrina. I resolved more or less. I thought I solved it using the python and epanet versions I said above. But after several "games" with my code, I realized that it wasn't. But one way that it worked without problems was when you deleted all files generated by python before each code run, but it didn't always work. If you find out another way I will be grateful too.

**Comment by thyagonaves** [comment]
Olá. Infelzimente estou com o mesmo problema, rodando processo de otimização e em determinada iteração tenho o erro 305. Alguém conseguiu solucionar?

Hello. Unfortunately, I have the same problem, running the optimization process and in a given iteration I have error 305. Has anyone managed to solve it?
