### ISSUE TITLE
How to avoid generating these strange files?

### ISSUE THREAD

**Issue by yejustme** [USEPA/WNTR#155]
When I tried to run the WNTR many times, every thing is OK except that  it generates these strange files. How to avoid this ？
![QQ截图20200722201139](https://user-images.githubusercontent.com/15081527/88175300-45e44e80-cc58-11ea-8391-02cf76bb8c06.png)

**Comment by dbhart** [comment]
Well, none of us have seen this behavior before. When EPANET crashes, it sometimes leaves files prefixed with "en", for example, "enSJFALS". But nothing "s64...". 

Can you give more information regarding operating system, hardware, etc. that you are using? And what you are trying to do with WNTR (if you can give that type of info out).

**Comment by yejustme** [comment]
> 
> 
> Well, none of us have seen this behavior before. When EPANET crashes, it sometimes leaves files prefixed with "en", for example, "enSJFALS". But nothing "s64...".
> 
> Can you give more information regarding operating system, hardware, etc. that you are using? And what you are trying to do with WNTR (if you can give that type of info out).

Thanks. But after I upgrade the WNTR to the newest 0.3.0 version, it seems that WNTR no longer generate these files.
