### ISSUE TITLE
Creating a directed acyclic graph using flow direction as a weight (networkx)

### ISSUE THREAD

**Issue by kalebsm** [USEPA/WNTR#156]
I am trying to create a directed acyclic graph using the flow direction as a weight. There is an example of using flow rate as the weight in the resilience metrics section of the documentation (https://wntr.readthedocs.io/en/latest/resilience.html). However, taking the approach in the example results in dataframe with columns time and flow_rate as the weight instead of a single value (see example below), which I hope to be either negative or positive. 
![image](https://user-images.githubusercontent.com/56654036/88352965-c58e1e00-cd29-11ea-87fd-8c0000a73db8.png)

![image](https://user-images.githubusercontent.com/56654036/88353062-20c01080-cd2a-11ea-9290-af906e6a841f.png)

My ultimate goal is to determine the lowest common ancestor of two different nodes within the system, and according to networkx that means the graph must be directed and acyclic (https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.lowest_common_ancestors.lowest_common_ancestor.html#networkx.algorithms.lowest_common_ancestors.lowest_common_ancestor). I assume since there is an example, somebody has successfully weighted a graph with the flow rate. Any help would be appreciated.

**Comment by kaklise** [comment]
The example should be updated to use ``G = wn.get_graph(link_weight=flowrate, modify_direction=True)``.  This will swap the start and end node for flowrates that are negative and create a graph that represents flow magnitude and direction.  Let us know if that solves the issue and we'll update the example.

**Comment by kalebsm** [comment]
I think there are some problems with the modify_direction setting. I've gone through the source code for the wntr.network.model (https://wntr.readthedocs.io/en/latest/_modules/wntr/network/model.html#WaterNetworkModel.get_graph) to figure out how the graph gets constructed when modify_direction = True. 

Over the course of a simulation, such as in the example I showed up top, the flowrate object extracted from the wntr simulator results is a dataframe (see above where the 'weight' key as a dataframe of time and flow as its value). So the modify_direction if statement on line 1501 of wntr.network.model uses creates a series of boolean statements for when the flow at a certain time is negative. Python doesn't know what to do with when given an if statement with a series boolean, and since the statement is in a try-except, the for loop always skips the modify_direction part.
![image](https://user-images.githubusercontent.com/56654036/89214728-59b37d00-d595-11ea-8cc8-3e9f448d6e93.png)

I think a problem with modifying the direction of the nodes to create a positive flow direction (for the purpose of weighting the graph according to flowrate) is that over the course of the simulation, some pipes may switch directions such that they can be both positive or negative at different time steps. This will be true of looped networks and not for water mains. I'm not familiar with the all_paths method in networkx - so I don't know what the aforementioned example is really getting at. However, as far as creating a graph that is weighted by flow direction the example does not work.

**Comment by kaklise** [comment]
The example has been updated so that flowrate is a pandas Series (not the entire DataFrame).  We also added a test to make sure we get the correct directed graph.
