### ISSUE TITLE
Can't change PRV settings after importing inp file

### ISSUE THREAD

**Issue by bernardoct** [USEPA/WNTR#157]
I'm trying to load an inp file and change the settings of its PRVs in python prior to running the hydraulic solver. The I'm having is that the results do not change after setting the pressure to 0 or 500 from the 55 in the inp file. I did see changes in results when changing pipe diameters but not PRV settings. I also noticed that the temp.inp file comes out with the original PRV setting, even though when I print the PRVs using the iterator from wn.valves() the setting seems to be changed. Below is my script:
```python
wn = wntr.network.WaterNetworkModel(r'WNTR\examples\networks\Net6.inp')
wn.get_link('VALVE-3891').setting = 0
# wn.get_link('VALVE-3891').setting = 500

# returns "35.172\n0" (35.172 being 50 psi in meters of head) though the temp.inp file shows the following:
# [VALVES]
# ;ID                   Node1                Node2                            Diameter Type              Setting           Minor Loss
#  VALVE-3890           JUNCTION-3160        JUNCTION-2848                      6 PRV               50               0   ;
#  VALVE-3891           JUNCTION-3319        JUNCTION-3281                      6 PRV               55               0   ;

for n, v in wn.valves():
    print(v.setting)

# Simulate hydraulics
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

# Plot results on the network
flows = results.link['flowrate'].loc[:, 'VALVE-3891']
flows.plot()
plt.show()
```
Am I doing something wrong, is this a bug, or is what I'm trying to do just not supported?

Thanks.

**Comment by bernardoct** [comment]
I think I found the issue. I'll test the my fix and submit a pull request in the coming few days.

**Comment by jermaine1ronquillo** [comment]
I am also trying to change the settings of TCV valves after importing my inp files, but when running the model using the EpanetSimulator the result is still based on the settings of the inp file, but switching to WNTRSimulator seems to work fine

**Comment by kaklise** [comment]
[PR to sandialabs/WNTR](https://github.com/sandialabs/WNTR/pull/3) been merged with USEPA/WNTR.
