### ISSUE TITLE
How to define time to repair in wntr?

### ISSUE THREAD

**Issue by mzare47** [USEPA/WNTR#158]
Hi, 
I'm new in wntr. I'd like to run a 'Use Case: Earthquake preparedness' on my network model. The algorithm is:
1-Generate a water network model
2-Define fragility curves for failure and available resources for recovery
3-Simulate PGA and PGV from an earthquake
4-Modify the network based fragility curves and available resources
5-Run a hydraulic and water quality simulation
6-Compute WSA and population impacted by low service
7-Analyze results and generate graphics

Based on this article: [https://www.osti.gov/servlets/purl/1458072]( https://www.osti.gov/servlets/purl/1458072)

**This is my code:**
`import wntr
from scipy.stats import lognorm
import numpy as np
import matplotlib.pylab as plt

np.random.seed(564789)

# Create a water network model
inp_file = 'networks/sadra.last2.inp'
wn = wntr.network.WaterNetworkModel(inp_file)

# Modify the water network model
wn.options.time.duration = 7*48*3600
wn.options.time.hydraulic_timestep = 1800
wn.options.time.report_timestep = 1800

# Graph the network
wntr.graphics.plot_network(wn, title=wn.name)

# Define fragility curve  
FC = wntr.scenario.FragilityCurve()
FC.add_state('Minor', 1, {'Default': lognorm(0.5,scale=0.3)})
FC.add_state('Major', 2, {'Default': lognorm(0.5,scale=0.7)}) 
wntr.graphics.plot_fragility_curve(FC, xlabel='Peak Ground Acceleration (g)')

# Define the earthquake
#wn = wntr.morph.scale_node_coordinates(wn, 1)
#wntr.graphics.plot_network(wn, title=wn.name)
epicenter = (640717,3300562) # x,y location
magnitude = 6.5 # Richter scale
depth = 10000 # m, shallow depth
earthquake = wntr.scenario.Earthquake(epicenter, magnitude, depth)
distance = earthquake.distance_to_epicenter(wn, element_type=wntr.network.Pipe)
pga = earthquake.pga_attenuation_model(distance)  
pgv = earthquake.pgv_attenuation_model(distance)
repair_rate = earthquake.repair_rate_model(pgv) 

# Plot epicenter
wntr.graphics.plot_network(wn, link_attribute=pga, node_size=0, link_width=1.5, 
                           title='Peak ground acceleration')
plt.scatter(epicenter[0], epicenter[1], s=1000, c='r', marker='*', zorder=2)

# Draw damage state for each pipe
pipe_PEDS = FC.cdf_probability(pga)
pipe_damage_state = FC.sample_damage_state(pipe_PEDS)
pipe_damage_state_map = FC.get_priority_map()
val = pipe_damage_state.map(pipe_damage_state_map)
custom_cmp = wntr.graphics.custom_colormap(3, ['grey', 'royalblue', 'darkorange'])
wntr.graphics.plot_network(wn, link_attribute=val, node_size=0, link_width=2,
                           link_cmap=custom_cmp, title='Damage state: 0=None, 1=Minor, 2=Major')

`

**How to define time to repair and recovery time in code?** Plz help me to complete my code base on the algorithm.
thanks

**Comment by kaklise** [comment]
I assume you plan to add leaks based on the values in `val` (major leak, minor leak, no leak). You can define the start and end time for each leak using the `add_leak` method.  See https://wntr.readthedocs.io/en/latest/disaster_models.html?highlight=add_leak#pipe-breaks-or-leaks for an example.  

We have an Jupyter notebook in the examples/demo folder for earthquakes, but I believe it is out-of-date with recent updates in WNTR.  I'll try to get that updated, but it may still help answer your question.

**Comment by kaklise** [comment]
The earthquake demo has been updated to use the latest version of WNTR.  This includes leak repair time, which can be set by the user.
