### ISSUE TITLE
Problem loading Water Network Model from EPANET 2.2

### ISSUE THREAD

**Issue by todorGaidarov** [USEPA/WNTR#162]
Hi 
I'm trying to load water network model created with EPANET 2.2 using the following line:
```
wn = wntr.network.WaterNetworkModel(inp_file)
```
Unfortunately I got this error:
```
usr/local/lib/python3.6/dist-packages/wntr/network/model.py in __init__(self, inp_file_name)
     89         self._inpfile = None
     90         if inp_file_name:
---> 91             self.read_inpfile(inp_file_name)
     92 
     93         # To be deleted and/or renamed and/or moved

/usr/local/lib/python3.6/dist-packages/wntr/network/model.py in read_inpfile(self, filename)
   1742         """
   1743         inpfile = wntr.epanet.InpFile()
-> 1744         inpfile.read(filename, wn=self)
   1745         self._inpfile = inpfile
   1746 

/usr/local/lib/python3.6/dist-packages/wntr/epanet/io.py in read(self, inp_files, wn)
    326 
    327         ### TANKS
--> 328         self._read_tanks()
    329 
    330         ### PIPES

/usr/local/lib/python3.6/dist-packages/wntr/epanet/io.py in _read_tanks(self)
    585                 curve_name = None
    586             else:
--> 587                 raise RuntimeError('Tank entry format not recognized.')
    588             self.wn.add_tank(current[0],
    589                         to_si(self.flow_units, float(current[1]), HydParam.Elevation),

RuntimeError: Tank entry format not recognized.
```

And tanks section in the .inp file looks like this:
```
[TANKS]
 ;ID               Elevation     InitLevel     MinLevel      MaxLevel      Diameter      MinVol        VolCurve          Overflow
  6                0             1.3           0             2.1           50            0             *                 Yes ;
```

It has 9 fields and I guess this is what breaks it.

**Comment by GalPerelman** [comment]
Hi @todorGaidarov 
Where does the "Overflow" column come from?
Usually, TANKS section has only the first 8 columns

**Comment by todorGaidarov** [comment]
Hi @GalPerelman 
The "Overflow" column comes from EPANET 2.2 I think. 
I am attaching the screen from EPANET with the tank property marked in red.
I've just removed the column as a workaround so that I can load the network.

![overflow_whole_screen_marked](https://user-images.githubusercontent.com/17799696/92221966-f2942b80-eea6-11ea-8b56-f228f85bedd3.png)

**Comment by GalPerelman** [comment]
You are right, this is a new feature of the 2.2 version
Might be that wntr is still not supporting this option

**Comment by dbhart** [comment]
Yes, this is a new feature. It is not well documented in the EPANET 2.2 documentation. However, we are doing a fix right now for the “dev” branch of WNTR, which has EPANET 2.2 support. I will post again when it has been fixed.

**Comment by dbhart** [comment]
I believe this is now fixed in the “dev” branch.

**Comment by todorGaidarov** [comment]
HI,
I won't be able to test it right now, but I believe the issue is fixed and will close the issue.
