### ISSUE TITLE
Problem importing results bin file

### ISSUE THREAD

**Issue by bernardo-suez** [USEPA/WNTR#165]
If a simulation is called with duration that is not a multiple of the report time step, WNTR seems to try to import results going to the next full multiple of the report time step, which causes problems when reshaping the binary array into a dataframe in [io.py, line 2790](https://github.com/USEPA/WNTR/blob/c2d3b70c65cc938fb3d19de8a730c23c43859843/wntr/epanet/io.py#L2788). Below are the times for my test case, which I unfortunately cannot publish in full for there being confidential data.

[TIMES]
 Duration           	62:30 
 Hydraulic Timestep 	0:15 
 Quality Timestep   	0:00 
 Pattern Timestep   	0:30 
 Pattern Start      	0:00 
 Report Timestep    	1:00 
 Report Start       	0:00 
 Start ClockTime    	0
 Statistic          	NONE

There was something weird in the output bin, though, which is that the output array had in the last column (the one not supposed to exist) four extra zeroes and three extra junk numbers, as shown below:

value | name | 0 | 3600 | 7200 | … | 216000 | 219600 | 223200 | 226800
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
demand | 31 | 0.858695 | 0.592855 | 0.670497 | … | 1.206397 | 1.206397 | 1.206397 | 0
demand | 34 | 0.993511 | 0.866264 | 0.698884 | … | 1.523058 | 1.523058 | 1.523058 | 0
demand | 37 | 0.133334 | 0.107404 | 0.07062 | … | 0.371526 | 0.371526 | 0.371526 | 0
demand | 40 | 1.353442 | 0.97383 | 1.112217 | … | 1.858744 | 1.858744 | 1.858744 | 0
demand | 43 | 0.957569 | 0.840501 | 0.686512 | … | 1.444752 | 1.444752 | 1.444752 | 8.83E-44
demand | 46 | 0.954125 | 0.637162 | 0.729735 | … | 1.368693 | 1.368693 | 1.368693 | 8.41E-45
demand | 49 | 1.723925 | 0.994569 | 1.207587 | … | 2.677877 | 2.677877 | 2.677877 | 2.07E-20
demand | 52 | 0.208376 | 0.151715 | 0.071335 | … | 0.72887 | 0.72887 | 0.72887 | 
demand | 55 | 2.184323 | 1.720141 | 1.109563 | … | 4.116034 | 4.116034 | 4.116034 | 
demand | 58 | 0.947763 | 0.634208 | 0.725786 | … | 1.357873 | 1.357873 | 1.357873 | 
demand | 61 | 1.755735 | 1.009338 | 1.227333 | … | 2.731976 | 2.731976 | 2.731976 | 
… | … | … | … | … | … | … | … | … | …

Maybe modifying the except statement right below the line I mentioned to account for these cases would do?

**Comment by dbhart** [comment]
So you are correct - you are always supposed to use a multiple of the report timestep for duration; EPANET will not report any data beyond the last report step. The last "junk" numbers are in fact the final checksums for an EPANET binary file.

If I understand, you are suggesting using a floor function to handle this case where the simulation runs past the final report step? So that we would round down to the nearest report timestep to get the file the correct shape? I believe that would be a better solution than adding to the except statement?

**Comment by dbhart** [comment]
Ah - no, in io.py, line 2693 is where the change would need to be made. That's a bug.

**Comment by dbhart** [comment]
This has been fixed in the dev branch now.

**Comment by bernardo-suez** [comment]
@dbhart you're right, that should allow for a much cleaner solution. Thanks for looking into this.
