### ISSUE TITLE
Demand-driven simulation

### ISSUE THREAD

**Issue by chocolate-771** [USEPA/WNTR#166]
In Pressure dependent demand simulation, if the nominal and minimum pressure of each node are different, can they be set separately?

**Comment by kaklise** [comment]
That is correct, when using the WNTRSimulator the nominal and minimum pressure can be set independently for each junction.  A small example is included in the following section of the documentation, https://wntr.readthedocs.io/en/latest/hydraulics.html#pressure-dependent-demand-simulation

**Comment by chocolate-771** [comment]
thank you for  reply, I get it.
