### ISSUE TITLE
The repair process introduces new leak nodes and pipes, will this increase the HeadLoss of the overall network?

### ISSUE THREAD

**Issue by algchyhao** [USEPA/WNTR#167]
When the number of leaked pipes is quite large, after all pipes repaired, the pressure in the whole network is lower than nomal state. Can't find out the reason.

**Comment by kaklise** [comment]
This should not have an impact on headloss across pipes.  When splitting each pipe using `wntr.morph.split_pipe`, this adds a node and pipe to each original pipe, but headloss in the system remain the same.  If you are adding and removing leaks, this should also have no impact.   If the leak ends and the system controls have changed, this can impact headloss .  The code I used to test this out is below.  If you have an example that shows different behavior, please let us know.

```
import wntr

# Original network model

wn = wntr.network.WaterNetworkModel('Net3.inp')
print(wn.describe(level=1))

sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()
wntr.graphics.plot_network(wn, node_attribute=results.node['pressure'].loc[24*3600, :], node_range=[0,50])

# Original + extra junction at each pipe + add and remove leak

wn = wntr.network.WaterNetworkModel('Net3.inp')
for pipe_name in wn.pipe_name_list:
    wntr.morph.split_pipe(wn, pipe_name, pipe_name+'_split', pipe_name+'_split', return_copy=False)
    leak_node = wn.get_node(pipe_name+'_split')
    leak_node.add_leak(wn, 1)
    leak_node.remove_leak(wn)
                            
print(wn.describe(level=1))

sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()
wntr.graphics.plot_network(wn, node_attribute=results.node['pressure'].loc[24*3600, :], node_range=[0,50])
```

**Comment by algchyhao** [comment]
> 
> 
> This should not have an impact on headloss across pipes. When splitting each pipe using `wntr.morph.split_pipe`, this adds a node and pipe to each original pipe, but headloss in the system remain the same. If you are adding and removing leaks, this should also have no impact. If the leak ends and the system controls have changed, this can impact headloss . The code I used to test this out is below. If you have an example that shows different behavior, please let us know.
> 
> ```
> import wntr
> 
> # Original network model
> 
> wn = wntr.network.WaterNetworkModel('Net3.inp')
> print(wn.describe(level=1))
> 
> sim = wntr.sim.EpanetSimulator(wn)
> results = sim.run_sim()
> wntr.graphics.plot_network(wn, node_attribute=results.node['pressure'].loc[24*3600, :], node_range=[0,50])
> 
> # Original + extra junction at each pipe + add and remove leak
> 
> wn = wntr.network.WaterNetworkModel('Net3.inp')
> for pipe_name in wn.pipe_name_list:
>     wntr.morph.split_pipe(wn, pipe_name, pipe_name+'_split', pipe_name+'_split', return_copy=False)
>     leak_node = wn.get_node(pipe_name+'_split')
>     leak_node.add_leak(wn, 1)
>     leak_node.remove_leak(wn)
>                             
> print(wn.describe(level=1))
> 
> sim = wntr.sim.EpanetSimulator(wn)
> results = sim.run_sim()
> wntr.graphics.plot_network(wn, node_attribute=results.node['pressure'].loc[24*3600, :], node_range=[0,50])
> ```



> 
> 
> This should not have an impact on headloss across pipes. When splitting each pipe using `wntr.morph.split_pipe`, this adds a node and pipe to each original pipe, but headloss in the system remain the same. If you are adding and removing leaks, this should also have no impact. If the leak ends and the system controls have changed, this can impact headloss . The code I used to test this out is below. If you have an example that shows different behavior, please let us know.
> 
> ```
> import wntr
> 
> # Original network model
> 
> wn = wntr.network.WaterNetworkModel('Net3.inp')
> print(wn.describe(level=1))
> 
> sim = wntr.sim.EpanetSimulator(wn)
> results = sim.run_sim()
> wntr.graphics.plot_network(wn, node_attribute=results.node['pressure'].loc[24*3600, :], node_range=[0,50])
> 
> # Original + extra junction at each pipe + add and remove leak
> 
> wn = wntr.network.WaterNetworkModel('Net3.inp')
> for pipe_name in wn.pipe_name_list:
>     wntr.morph.split_pipe(wn, pipe_name, pipe_name+'_split', pipe_name+'_split', return_copy=False)
>     leak_node = wn.get_node(pipe_name+'_split')
>     leak_node.add_leak(wn, 1)
>     leak_node.remove_leak(wn)
>                             
> print(wn.describe(level=1))
> 
> sim = wntr.sim.EpanetSimulator(wn)
> results = sim.run_sim()
> wntr.graphics.plot_network(wn, node_attribute=results.node['pressure'].loc[24*3600, :], node_range=[0,50])
> ```

Thank you kaklise for the prompt reply. I am trying very strong earthquake which causes over half of the pipelines fails. After all the pipelines got recovered, the overall pressure in the network is still obviously lower than that subjected to minor earthquakes. The pumps are all working. What could be the causes please? I using PDD mode. If there is no more leaks, the pumps should be powerfull enough to supply the demand, right?

**Comment by kaklise** [comment]
As long as the tanks are able to fill and there are no other controls limiting pressure in the network, then I agree that pressure should be recovered after the leaks are fixed.   I'll double check that the leak controls have no impact once the leak ends. If you're able to share an example, that would be helpful.

**Comment by algchyhao** [comment]
> 
> 
> As long as the tanks are able to fill and there are no other controls limiting pressure in the network, then I agree that pressure should be recovered after the leaks are fixed. I'll double check that the leak controls have no impact once the leak ends. If you're able to share an example, that would be helpful.

Hi kaklise,

You are correct, I missed some damaged pipes that should be fiexed. Just a question before cloing the comment, why there are pipes with leaked_demand a very small negative number, i.e. -10^(12), is this caused by numerical error? Thanks.

**Comment by kaklise** [comment]
Very small negative pressures are caused by numerical error.
