### ISSUE TITLE
EPANET error 305 during optimization

### ISSUE THREAD

**Issue by thyagonaves** [USEPA/WNTR#174]
Hello, I'm running an optimization process in which every iteration there is an EPANET solver, but in any iteration the error 305 happens and I lose the optimization. To run the script again I have to close Spyder, and start the process again, but error 305 appears again at a certain time.

I've tried to force the saving of EPANET temporary files and it still didn't work: 
             sim.run_sim(file_prefix='tempPSO1', save_hyd=True, hydfile='temphyd1.hyd')

**Comment by kaklise** [comment]
Are you using the latest version of WNTR (version 0.3.0)?  I believe this issue has been resolved now that the EpanetSimulator can use EPANET 2.2.
