### ISSUE TITLE
Error when processing rules for pumps using speed parameter

### ISSUE THREAD

**Issue by carmine1990** [USEPA/WNTR#178]
When i run the .inp file with wntr library, i have this error:
" 'HeadPump' object has no attribute 'valve_type' "

Instead if i run the .inp file into epanet it work. I give you the .inp file for testing.
[35A01.zip](https://github.com/USEPA/WNTR/files/5597144/35A01.zip)

The problem is in the io.py file (epanet directory) when it try to resolve the generate_control method:
------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\wntr\network\model.py", line 88, in __init__
    self.read_inpfile(inp_file_name)
  File "C:\Program Files\Python38\lib\site-packages\wntr\network\model.py", line 1764, in read_inpfile
    inpfile.read(filename, wn=self)
  File "C:\Program Files\Python38\lib\site-packages\wntr\epanet\io.py", line 330, in read
    self._read_rules()
  File "C:\Program Files\Python38\lib\site-packages\wntr\epanet\io.py", line 1330, in _read_rules
    ctrl = rule.generate_control(self.wn)
  File "C:\Program Files\Python38\lib\site-packages\wntr\epanet\io.py", line 2370, in generate_control
    if link.valve_type.upper() in ['PRV', 'PBV', 'PSV']:
AttributeError: 'HeadPump' object has no attribute 'valve_type'
------------------------------------------------------------------------------------------------------------

I leave exemple of one rule write to simulate the varying speed pump used in .inp file:
rule 1010
if node FSEQ_0000000000442700-118765 pressure > 70.7
and pump 35A02P04_POZZO00136_POMPA01243 setting is 0.6
then pump 35A02P04_POZZO00136_POMPA01243 setting is 0.59
priority 1

**Comment by carmine1990** [comment]
I modified the io.py file at line 2370-2377 and now it works. I write you the edited part:
[...]
                    if isinstance(link, wntr.network.Pump):
                        value = value
                    elif isinstance(link, wntr.network.Valve):
                        if link.valve_type.upper() in ['PRV', 'PBV', 'PSV']:
                            value = to_si(self.inp_units, value, HydParam.Pressure)
                        elif link.valve_type.upper() in ['FCV']:
                            value = to_si(self.inp_units, value, HydParam.Flow)
[...]

I give you the io.py file revised
[io.zip](https://github.com/USEPA/WNTR/files/5601436/io.zip)

**Comment by kaklise** [comment]
Thanks for posting the issue and revised io.py file.  Feel free to submit a pull request, otherwise we'll get this integrated soon.

**Comment by carmine1990** [comment]
Thank you kaklise, i submited a pull request like you suggest me. I'm a new user on Github and i didn't know how to revise a script.
