### ISSUE TITLE
Plot a specific node. 

### ISSUE THREAD

**Issue by edalopezga** [USEPA/WNTR#180]
Hi, thanks for the tool.

I need to plot the elevations of the network, but I need to remark a specific node, maybe with another color or size, how can I do that.

**Comment by kaklise** [comment]
You can specify an axes in `plot_network`.  This allows you to add additional information to the plot.  For example, the following marks a specific node on a network graphic of elevation (using Net3 as an example).  
```
plt.figure()
ax = plt.gca()
wntr.graphics.plot_network(wn, node_attribute='elevation', ax=ax)
wntr.graphics.plot_network(wn, node_attribute=['123'], node_size=60, ax=ax)
```
You could also plot directly on the axes using a matplotlib scatter.
```
plt.figure()
ax = plt.gca()
wntr.graphics.plot_network(wn, node_attribute='elevation', ax=ax)
node = wn.get_node('123')
ax.scatter(node.coordinates[0], node.coordinates[1], s=60, c='k', marker='s')
```

**Comment by edalopezga** [comment]
Thanks, it works perfectly.
