### ISSUE TITLE
Emitter coefficients

### ISSUE THREAD

**Issue by Keramatfar** [USEPA/WNTR#181]
Dear admin,
I would like to work with emitter coefficients as i work with them in the EPANET. The documentation is not quiet clear. Can you please guide me?

**Comment by kaklise** [comment]
Emitter coefficient is a node attribute, for example:
```
node = wn.get_node('119')
node.emitter_coefficient = 0.2
```
We can improve the documentation so this is easier to find.

**Comment by kaklise** [comment]
Emitter coefficients are now included in the API docs.
