### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'networks/Net3.inp'

### ISSUE THREAD

**Issue by Mottabata** [USEPA/WNTR#184]
I am new to wntr. I am trying the examples and I had the following issue
 [1] import wntr
[2] inp_file = 'networks/Net3.inp'
[3] wn = wntr.network.WaterNetworkModel(inp_file)
Traceback (most recent call last):

  File "<ipython-input-9-c37fa123a0ee>", line 2, in <module>
    wn = wntr.network.WaterNetworkModel(inp_file)

  File "C:\Users\mota\anaconda3\lib\site-packages\wntr\network\model.py", line 88, in __init__
    self.read_inpfile(inp_file_name)

  File "C:\Users\mota\anaconda3\lib\site-packages\wntr\network\model.py", line 1764, in read_inpfile
    inpfile.read(filename, wn=self)

  File "C:\Users\mota\anaconda3\lib\site-packages\wntr\epanet\io.py", line 275, in read
    with io.open(filename, 'r', encoding='utf-8') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'networks/Net3.inp'

**Comment by kaklise** [comment]
Based on the folder where you are running this analysis, there should be folder called networks that contains Net3.inp.  Does this file and directory structure exist? If Net3.inp file is located elsewhere, you can change the relative path when defining inp_file.

**Comment by Mottabata** [comment]
this is where the example file is 
C:\Users\mota\anaconda3\Lib\site-packages\examples\networks\Net3.inp

**Comment by kaklise** [comment]
I suggest moving the examples into a more usable space.  To make sure you don't impact your Anaconda files, I suggest downloading the examples from https://github.com/USEPA/WNTR. More information is available at https://wntr.readthedocs.io/en/stable/getting_started.html in the Note.

**Comment by Mottabata** [comment]
those notes were exactly what i followed to install the additional examples from the Github link you provided.
what do you mean by a "more usable space"?

**Comment by kaklise** [comment]
I suggest not storing example files in Anaconda site-packages.  A location such as C:\Users\usename\WNTR_examples would make the files easier to access.  If that folder contains networks/Net3.inp, you should be able to run the getting_started.py example.
