### ISSUE TITLE
Installation and Import Failure: Missing '_evaluator' Module

### ISSUE THREAD

**Issue by seanotoole03** [USEPA/WNTR#189]
Hello,

As part of a research team, I've recently begun looking into the use of WNTR for the simulation and visualization of water networks and testbeds. However, right off the bat we've hit a stumbling block, and despite going through the standard installation process multiple times (tested pip, anaconda, and git clone/setup.py), we consistently hit the same error whenever we attempt to import and begin using WNTR:
![image](https://user-images.githubusercontent.com/38194734/108751609-afcf1a00-74ff-11eb-9aeb-5950068de682.png)

When attempting to run a program relying on WNTR for processing and converting .inp files (inp2cpa), you can see that while the initial calls are obviously different, and a different installation of WNTR is being used, the same errors are returned. Version is 3.8.5, as shown in the screengrab:
![image](https://user-images.githubusercontent.com/38194734/108751846-f6247900-74ff-11eb-87f1-8af3c36ed07c.png)

A separate error occurs when attempting to run from Python 3.6.4:
![image](https://user-images.githubusercontent.com/38194734/108752804-2caec380-7501-11eb-8f57-bd1fb728b6b8.png)

Running nosetests obviously gives the same error as in the 3.8.5 imports:
![image](https://user-images.githubusercontent.com/38194734/108753552-20773600-7502-11eb-921d-f22eda089644.png)

Both of the installs shown here are running on current editions of Windows 10 Pro, Version 20H2, Build 19042.804
All modules on which WNTR is dependent have been installed and double-checked.
If needed, I would be happy to provide additional information and/or attempt installs on other VMs in order to demonstrate the errors.

**Comment by dbhart** [comment]
Hi @seanotoole03 . I'll look into the 3.8 issue - do you have cython installed? As for 3.6, have you tried installing six? (pip install six). It is the python2/3 compatibility package, and we still have a couple of functions that do unicode vs bytes comparisons.

**Comment by dbhart** [comment]
Also, if you go here https://github.com/USEPA/WNTR/runs/1937294970?check_suite_focus=true you can expand the "Install dependencies" tab and see if there's anything you are missing. That is our build check that does windows with python 3.8

**Comment by dbhart** [comment]
Is there a reason you are running 32-bit python 3.8?

**Comment by seanotoole03** [comment]
David,

No particular reason for running Py38-32, at least as far as this is concerned, it's simply the python distro I've been using most frequently on this device. Would a different distro be better? I have an older Python 3.6.4 installed as well for a related project.
All dependencies, mandatory and optional, have been installed, for both installations.
Have made sure the 'six' is installed for both now, no longer seeing that error for Python 3.6.4, but am now seeing the same error as encountered with 3.8-32. 
![image](https://user-images.githubusercontent.com/38194734/109094699-a4364b80-76d7-11eb-9970-724ec37d5697.png)

I should note that I've run a separate install process on a new Ubuntu 20.04 VM, and have managed to get WNTR up and running there. Not sure what specific issues are going on in my Windows box, then. What other details can I provide right now? Tests I can run?
The results of attempting nosetests from the software tests section is as follows, similar to attempting to run the code ordinarily: 
![image](https://user-images.githubusercontent.com/38194734/109095164-76053b80-76d8-11eb-9a69-4915b12eb1b0.png)

**Comment by TimothyVD** [comment]
Hi @seanotoole03, 

I (am forced to) use Windows 10 and Anaconda, and for me WNTR runs smoothly.
In the past I encountered similar issues for a variety of python packages when I was not using the anaconda prompt. I see you are using MINGW64 (git bash prompt?) and the standard cmd, but I know from previous experience that these cmd interfaces caused issues in Windows.

Kind regards,
Timothy

**Comment by kaklise** [comment]
WNTR requires 64-bit Python to run the compiled code in wntr.sim.aml and to run the epanet22 DLL.  Please let us know if moving to 64-bit Python resolves the issue.

**Comment by seanotoole03** [comment]
Timothy,

In much the same boat, although I'm not stuck with Anaconda. Good to know that the git bash interface could be part of the problem, what would you suggest using instead? Is Powershell the preferable option here?

Katherine,

I went ahead and got 3.9.2 64-bit installed, but am facing the same issue, unfortunately. 
![image](https://user-images.githubusercontent.com/38194734/109401002-5012ad80-7909-11eb-98c6-42ca1cace830.png)
Any suggestions?

Thanks again for all the help, hopefully this is an issue purely with my own configs.

**Comment by TimothyVD** [comment]
Hi @seanotoole03  ,

If I understand well, you are not using anaconda/miniconda on windows? In the past I ran into a lot of issues on Windows when I was not using anaconda. Probably other options are out there, but anaconda did the trick for me.

I think your issue is explained here: https://stackoverflow.com/questions/47914980/how-to-access-anaconda-command-prompt-in-windows-10-64-bit

In my specific case: I don't let Anaconda mess with my path, so I have to use the anaconda prompt. Other options like powershell, cmd, git bash, ... will only yield errors.

Kind regards,
Timothy

**Comment by dbhart** [comment]
I believe we may not be building a Python 3.9 conda-forge binary, I will also check into that. I think Python 3.8 may be the most recent binary, in which case that would certainly be part of the issues. Sorry that this isn’t clearer; @kaklise – we might want to make something on both the rtd pages and the readme that specifies what we have built?

**Comment by michaelbynum** [comment]
I'd like to fix something in the c++ extension. We can get builds for 3.9 at the same time, and accomplish two things at once.

**Comment by seanotoole03** [comment]
Timothy,

Running from Anaconda seems to call Python 3.7.2, which fixes the import problem from the standard Python command line. Thanks for the great suggestion.
Unfortunately, it looks like part of my problem might be tied up in the requirement that the overarching program runs using 'fbs run', which is still limited to Python 3.5-3.6, and for which the config files seem to be non-functional in determining runtime interpreter. So even though I specify an earlier version of Python to run in the venv, it simply runs 3.9.2 anyways, which is where we're getting these errors from.

So it looks like the issues with WNTR can be resolved by path management and ensuring that current Python version is 3<V<3.9 (at least for right now), if I'm understanding this right? There aren't any issues central to WNTR remaining on my end at this point, since the issues have been identified as Python version and path visibility. All remaining issues will be on the fbs and venv side.
Thanks again for the help and guidance!

**Comment by kaklise** [comment]
This issue has been resolved now that WNTR supports Python 3.9
