### ISSUE TITLE
Pressure dependent demand simulation

### ISSUE THREAD

**Issue by chocolate-771** [USEPA/WNTR#193]
How to understand"By default, the each junction’s required and minimum pressure is set to None and the global value in the hydraulic options are used."

What is the global value in the hydraulic options? Do I need to set this myself?

**Comment by dbhart** [comment]
If you have the following ``wn = wntr.network.WaterNetworkModel()`` then,

``wn.options.hydraulic.minimum_pressure`` is used for the minimum pressure for any node where ``node.minimum_pressure is None`` .

and

``wn.options.hydraulic.required_pressure`` is used for the required pressure for any node where ``node.required_pressure is None`` .

By default, the global minimum pressure is 0, and the global required pressure is 0.07 m H2O (which are the default values for minimum and required pressure in EPANET 2.2).

I hope that helps.

**Comment by dbhart** [comment]
If you have the following `wn = wntr.network.WaterNetworkModel()` then,

`wn.options.hydraulic.minimum_pressure` is used for the minimum pressure for any node where `node.minimum_pressure is None` .

and

`wn.options.hydraulic.required_pressure` is used for the required pressure for any node where `node.required_pressure is None` .

By default, the global minimum pressure is 0, and the global required pressure is 0.07 m H2O (which are the default values for minimum and required pressure in EPANET 2.2).

I hope that helps.
