### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by mi01** [USEPA/WNTR#194]
Since some Linux distributions already use Python 3.9 it would be great to get support for this version. When just installing WNTR in such an environment, either with `pip install` or with `setup.py install`, the missing C++ libraries for 3.9 are problematic. I was quite confused by the following error in this case: `ModuleNotFoundError: No module named 'wntr.sim.aml._evaluator'`, before i found the missing libraries to be to problem here.

So i tried to figure out how to compile the libraries on my own. I installed swig and set the flags `use_swig` and `build` to True in `setup.py`, but this was not working. It took a while before i realized, that the libraries are actually copied from the source folder, not from the build folder. Finally i found the correct command: `python setup.py build_ext --inplace`.

In the first place I want to share my problem and the solution here. But I also want to encourage you, to write down the necessary build steps in the documentation, in case people need to compile the libraries for whatever reason.

**Comment by kaklise** [comment]
Thanks for opening this issue.  We'll try to update the aml to support 3.9 soon.  We'll also update the documentation to clarify how the libraries are compiled.

**Comment by pirofti** [comment]
Based on @mi01 solution, I have put together an [AUR package](https://aur.archlinux.org/packages/python-wntr/) for Arch Linux. The important bits start [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-wntr#n24).

**Comment by kaklise** [comment]
The latest WNTR release (0.3.1) include support Python 3.9. Let us know if you have any issues with the update.
