### ISSUE TITLE
Pressure Driven Analysis with EpanetSimulator

### ISSUE THREAD

**Issue by mi-les** [USEPA/WNTR#196]
I am trying to run a PDD with the EpanetSimulator but from the results it seems that it keeps running a demand-driven simulation despite having set `wn.options.hydraulic.demand_model = 'PDD'`. This is my minimal example:

```
wn = wntr.network.WaterNetworkModel()

wn.add_reservoir('reservoir', base_head=10, coordinates=(0,0))
wn.add_junction('node_1', base_demand=0.01, elevation=5,  coordinates=(0.5, 0))
wn.add_junction('node_2', base_demand=0.01, elevation=11, coordinates=(1, 0))
wn.add_pipe('pipe_1', 'reservoir', 'node_1', length=100, diameter=1, roughness=100, minor_loss=0.0, status='OPEN')
wn.add_pipe('pipe_2', 'node_1', 'node_2', length=100, diameter=1, roughness=100, minor_loss=0.0, status='OPEN')

wn.options.time.duration = 86400
wn.options.time.hydraulic_timestep = 3600

wn.options.hydraulic.demand_model = 'PDD'
sim = wntr.sim.EpanetSimulator(wn)
sim.mode = 'PDD'
results = sim.run_sim()
```

Both DD and PDD give me the same results:
- pressure:

| node 1| node 2| 
|---------|--------|
|4.999848 | -1.000192|

- demand

| node 1| node 2| 
|---------|--------|
|0.01 | 0.01|

am I missing something? trying to change the Epanet version does not work for me because `run_sim()` cannot take the argument `version`.

**Comment by dbhart** [comment]
hi @mi-les 

If run_sim doesn't work for you with a version argument, then I am going to surmise that you don't have the most recent WNTR (version 3.x). Version <=2.3 did not have EPANET 2.2 support yet, so that could explain the issue. If you check `wntr.__version__` it should tell you which it is. If that doesn't fix it, please let me know.

**Comment by kaklise** [comment]
I think the issues is that WNTR has a very low default value for required pressure.  This was carried over from EPANET where the default required pressure is 0.1 psi.  I suggest updating the required pressure before running the simulation (for example, `wn.options.hydraulic.required_pressure = 20`).  Required pressure is in meters in WNTR.
