### ISSUE TITLE
Pressure Driven Analysis with WNTRSimulator

### ISSUE THREAD

**Issue by chocolate-771** [USEPA/WNTR#200]
Hello ，I am trying to run a PDD with the WNTRSimulator but from the results it seems that it keeps running a demand-driven simulation despite having set wn.options.hydraulic.demand_model = 'PDD'. This is my minimal example:

inp_file = 'js/zh1.inp'
wn = wntr.network.WaterNetworkModel(inp_file)
wn.options.hydraulic.demand_model = 'PDD'
wn.options.time.duration = 24*3600
wn.options.hydraulic.minimum_pressure = 0
wn.options.hydraulic.required_pressure = 80
sim = wntr.sim.WNTRSimulator(wn)
results = sim.run_sim()

Am I missing something?

**Comment by kaklise** [comment]
I ran the example you provided with Net3 using PDD and DD and see differences in the simulation results.  If the pressures in your network are above 80 m, the results will be the same.
