### ISSUE TITLE
plot_network error when add_colorbar = True using directed=True with link_attribute

### ISSUE THREAD

**Issue by kethansarma** [USEPA/WNTR#205]
- Used Code
ax = wntr.graphics.plot_network(wn, link_attribute=velocity_at_1hr, node_size=0, directed=True,
                               add_colorbar=True)
- Issue
AttributeError                            Traceback (most recent call last)
<ipython-input-228-41164f276c77> in <module>
     26                            node_size=10,link_width=3, link_range= [0,100],
     27                            title='Flow',
---> 28                            link_colorbar_label='Flow (l/s)', ax=Ax1, directed=True)

~\anaconda3\envs\py3p7ML\lib\site-packages\wntr\graphics\network.py in plot_network(wn, node_attribute, link_attribute, title, node_size, node_range, node_alpha, node_cmap, node_labels, link_width, link_range, link_alpha, link_cmap, link_labels, valve_layer, add_colorbar, node_colorbar_label, link_colorbar_label, directed, ax, filename)
    230         clb.ax.set_title(node_colorbar_label, fontsize=10)
    231     if add_link_colorbar and link_attribute:
--> 232         clb = plt.colorbar(edges, shrink=0.5, pad=0.05, ax=ax)
    233         clb.ax.set_title(link_colorbar_label, fontsize=10)
    234     ax.axis('off')

~\anaconda3\envs\py3p7ML\lib\site-packages\matplotlib\pyplot.py in colorbar(mappable, cax, ax, **kw)
   2007     if ax is None:
   2008         ax = gca()
-> 2009     ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
   2010     return ret
   2011 colorbar.__doc__ = matplotlib.colorbar.colorbar_doc

~\anaconda3\envs\py3p7ML\lib\site-packages\matplotlib\figure.py in colorbar(self, mappable, cax, ax, use_gridspec, **kw)
   2236                              'panchor']
   2237         cb_kw = {k: v for k, v in kw.items() if k not in NON_COLORBAR_KEYS}
-> 2238         cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
   2239 
   2240         self.sca(current_ax)

~\anaconda3\envs\py3p7ML\lib\site-packages\matplotlib\colorbar.py in colorbar_factory(cax, mappable, **kwargs)
   1683         cb = ColorbarPatch(cax, mappable, **kwargs)
   1684     else:
-> 1685         cb = Colorbar(cax, mappable, **kwargs)
   1686 
   1687     cid = mappable.callbacksSM.connect('changed', cb.on_mappable_changed)

~\anaconda3\envs\py3p7ML\lib\site-packages\matplotlib\colorbar.py in __init__(self, ax, mappable, **kw)
   1203         # Ensure the given mappable's norm has appropriate vmin and vmax set
   1204         # even if mappable.draw has not yet been called.
-> 1205         if mappable.get_array() is not None:
   1206             mappable.autoscale_None()
   1207 

AttributeError: 'list' object has no attribute 'get_array'

- Workaround
ax = wntr.graphics.plot_network(wn, link_attribute=velocity_at_1hr, node_size=0, directed=True,
                               add_colorbar=False)
vmin = velocity_at_1hr.min()
vmax = velocity_at_1hr.max()
cmap = plt.cm.Spectral_r
sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=vmin, vmax=vmax))
sm.set_array([])
cbar = plt.colorbar(sm,label='pressure', shrink=0.5, pad=0.05)
cbar.ax.set_title('Pressure')
plt.show()
plt.show()

**Comment by kaklise** [comment]
Thanks for posting this issue and workaround.  We can get that integrated into plot_network soon, but feel free to submit a PR if you'd like make the change.

**Comment by kethansarma** [comment]
Thanks for the response. I am attaching plot_network code addressing the issue. Kindly go through it

`
"""
The wntr.graphics.network module includes methods plot the
water network model.
"""
import logging
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import animation

try:
    import plotly
except:
    plotly = None
try:
    import folium
except:
    folium = None
    
from wntr.graphics.color import custom_colormap

logger = logging.getLogger(__name__)

def _format_node_attribute(node_attribute, wn):
    
    if isinstance(node_attribute, str):
        node_attribute = wn.query_node_attribute(node_attribute)
    if isinstance(node_attribute, list):
        node_attribute = dict(zip(node_attribute,[1]*len(node_attribute)))
    if isinstance(node_attribute, pd.Series):
        node_attribute = dict(node_attribute)
    
    return node_attribute

def _format_link_attribute(link_attribute, wn):
    
    if isinstance(link_attribute, str):
        link_attribute = wn.query_link_attribute(link_attribute)
    if isinstance(link_attribute, list):
        link_attribute = dict(zip(link_attribute,[1]*len(link_attribute)))
    if isinstance(link_attribute, pd.Series):
        link_attribute = dict(link_attribute)
            
    return link_attribute
        
def plot_link_network(wn, node_attribute=None, link_attribute=None, title=None,
               node_size=20, node_range=[None,None], node_alpha=1, node_cmap=None, node_labels=False,
               link_width=1, link_range=[None,None], link_alpha=1, link_cmap=None, link_labels=False,
               valve_layer=None, add_colorbar=True, node_colorbar_label='Node', link_colorbar_label='Link',                    
               directed=False, ax=None, filename=None):
    """
    Plot network graphic

    Parameters
    ----------
    wn : wntr WaterNetworkModel
        A WaterNetworkModel object

    node_attribute : None, str, list, pd.Series, or dict, optional

        - If node_attribute is a string, then a node attribute dictionary is
          created using node_attribute = wn.query_node_attribute(str)
        - If node_attribute is a list, then each node in the list is given a 
          value of 1.
        - If node_attribute is a pd.Series, then it should be in the format
          {nodeid: x} where nodeid is a string and x is a float. 
        - If node_attribute is a dict, then it should be in the format
          {nodeid: x} where nodeid is a string and x is a float

    link_attribute : None, str, list, pd.Series, or dict, optional

        - If link_attribute is a string, then a link attribute dictionary is
          created using edge_attribute = wn.query_link_attribute(str)
        - If link_attribute is a list, then each link in the list is given a 
          value of 1.
        - If link_attribute is a pd.Series, then it should be in the format
          {linkid: x} where linkid is a string and x is a float. 
        - If link_attribute is a dict, then it should be in the format
          {linkid: x} where linkid is a string and x is a float.

    title : str, optional
        Plot title 

    node_size : int, optional
        Node size 

    node_range : list, optional
        Node range ([None,None] indicates autoscale)
        
    node_alpha : int, optional
        Node transparency
        
    node_cmap : matplotlib.pyplot.cm colormap or list of named colors, optional
        Node colormap 
        
    node_labels: bool, optional
        If True, the graph will include each node labelled with its name. 
        
    link_width : int, optional
        Link width

    link_range : list, optional
        Link range ([None,None] indicates autoscale)

    link_alpha : int, optional
        Link transparency
    
    link_cmap : matplotlib.pyplot.cm colormap or list of named colors, optional
        Link colormap
        
    link_labels: bool, optional
        If True, the graph will include each link labelled with its name. 
        
    add_colorbar : bool, optional
        Add colorbar

    node_colorbar_label: str, optional
        Node colorbar label
        
    link_colorbar_label: str, optional
        Link colorbar label
        
    directed : bool, optional
        If True, plot the directed graph
    
    ax : matplotlib axes object, optional
        Axes for plotting (None indicates that a new figure with a single 
        axes will be used)
        
    Returns
    -------
    nodes, edges : matplotlib objects for network nodes and edges

    Notes
    -----
    For more network draw options, see nx.draw_networkx
    """

    if ax is None: # create a new figure
        plt.figure(facecolor='w', edgecolor='k')
        ax = plt.gca()
    # Graph
    if directed is True:
        if link_attribute is not None or node_attribute is not None:
            G = wn.get_graph(node_weight = node_attribute, link_weight=link_attribute, modify_direction=True)
            pos = nx.get_node_attributes(G,'pos')
        
    else:
        G = wn.get_graph()
        G = G.to_undirected()
        # Position
        pos = nx.get_node_attributes(G,'pos')
    if len(pos) == 0:
        pos = None   

    # Define node properties
    add_node_colorbar = add_colorbar
    if node_attribute is not None:
        
        if isinstance(node_attribute, list):
            if node_cmap is None:
                node_cmap = ['red', 'red']
            add_node_colorbar = False
        
        if node_cmap is None:
            node_cmap = plt.cm.Spectral_r
        elif isinstance(node_cmap, list):
            if len(node_cmap) == 1:
                node_cmap = node_cmap*2
            node_cmap = custom_colormap(len(node_cmap), node_cmap)  
         
        node_attribute = _format_node_attribute(node_attribute, wn)
        nodelist,nodecolor = zip(*node_attribute.items())

    else:
        nodelist = None
        nodecolor = 'k'
    
    add_link_colorbar = add_colorbar
    if link_attribute is not None:
        
        if isinstance(link_attribute, list):
            if link_cmap is None:
                link_cmap = ['red', 'red']
            add_link_colorbar = False

        if link_cmap is None:
            link_cmap = plt.cm.Spectral_r
        elif isinstance(link_cmap, list):
            if len(link_cmap) == 1:
                link_cmap = link_cmap*2
            link_cmap = custom_colormap(len(link_cmap), link_cmap)  
       
            
        link_attribute = _format_link_attribute(link_attribute, wn)
        
   
        attr = {}
        for link_item in G.edges:
            attr[link_item] = link_attribute[link_item[2]]
         link_attribute = attr
        
        linklist,linkcolor = zip(*link_attribute.items())
    else:
        linklist = None
        linkcolor = 'k'
    
    if title is not None:
        ax.set_title(title)
        
    edge_background = nx.draw_networkx_edges(G, pos, edge_color='grey', 
                                             width=0.5, ax=ax)
    
    nodes = nx.draw_networkx_nodes(G, pos, 
            nodelist=nodelist, node_color=nodecolor, node_size=node_size, 
            alpha=node_alpha, cmap=node_cmap, vmin=node_range[0], vmax = node_range[1], 
            linewidths=0, ax=ax)
    edges = nx.draw_networkx_edges(G, pos, edgelist=linklist,  
                                   edge_color=linkcolor, width=link_width, alpha=link_alpha, edge_cmap=link_cmap, 
                                    edge_vmin=link_range[0], edge_vmax=link_range[1], ax=ax)
    if node_labels:
        labels = dict(zip(wn.node_name_list, wn.node_name_list))
        nx.draw_networkx_labels(G, pos, labels, font_size=7, ax=ax)
    if link_labels:
        labels = {}
        for link_name in wn.link_name_list:
            link = wn.get_link(link_name)
            labels[(link.start_node_name, link.end_node_name)] = value
        nx.draw_networkx_edge_labels(G, pos, labels, font_size=7, ax=ax)
    if add_node_colorbar and node_attribute:
        clb = plt.colorbar(nodes, shrink=0.5, pad=0, ax=ax)
        clb.ax.set_title(node_colorbar_label, fontsize=10)
    if add_link_colorbar and link_attribute:
        vmin = min(map(abs,link_attribute.values())) #link_attribute_raw.abs().min() 
        vmax = max(map(abs,link_attribute.values())) #link_attribute_raw.abs().max()
        cmap = plt.cm.Spectral_r
        sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=vmin, vmax=vmax))
        sm.set_array([])
        clb = plt.colorbar(sm, shrink=0.5, pad=0.05, ax=ax)
        clb.ax.set_title(link_colorbar_label, fontsize=10)
    ax.axis('off')
    
    if valve_layer is not None:
        for valve_name, (pipe_name, node_name) in valve_layer.iterrows():
            pipe = wn.get_link(pipe_name)
            if node_name == pipe.start_node_name:
                start_node = pipe.start_node
                end_node = pipe.end_node
            elif node_name == pipe.end_node_name:
                start_node = pipe.end_node
                end_node = pipe.start_node
            else:
                print("Not valid")
                continue
            x0 = start_node.coordinates[0]
            dx = end_node.coordinates[0] - x0
            y0 = start_node.coordinates[1]
            dy = end_node.coordinates[1] - y0
            valve_coordinates = (x0 + dx * 0.1,
                                     y0 + dy * 0.1)
            ax.scatter(valve_coordinates[0], valve_coordinates[1], 15, 'r', 'v')   
     
    if filename:
        plt.savefig(filename)
        
    return nodes, edges

**Comment by kaklise** [comment]
Thanks. I included some minor updates and a test, I'll submit this as a PR and you can review.

**Comment by kaklise** [comment]
Closed by #207.  We will be tagging a release soon, which will make this update available through pypi/conda.
