### ISSUE TITLE
Can't loop EpanetSimulator after Epanet Error 302 occurs

### ISSUE THREAD

**Issue by sievold** [USEPA/WNTR#208]
I am trying to perform monte carlo simulation on a data set using EpanetSimulator . I have to loop the simulation 3000 times at least. But roughly every 500-1000 iterations, I run into the Epanet Error 302. And once that happens, every subsequent iteration keeps giving the same error. I saw someone else post a similar issue in 2018 but the issue was not properly resolved because the issue could not be reproduced. I am going to add my code and data here to help with that. 
From what I understood, the code creates the temp.bin , temp.rpt and temp. inp files at the end of every run and then attempts to read those files in the new run even though that's not what I want it to do.

MOD.txt and rerun.txt in the attachment are supposed to be MOD.inp and rerun.py respectively. Path directories in the code may need to be edited if anyone wants to run the code.

**Comment by dbhart** [comment]
Hi @sievold,
I have not had a chance to look in detail yet, but there is a way to change the inpfile prefix (the "temp" part). This can be done by calling:
`sim.run_sim(file_prefix="iter{:s}".format(i))`
for example. Of course, then you will get lots of temporary files you may need to remove, but that at least will keep them from ever writing to the same files.

Hopefully that's a start...

**Comment by kaklise** [comment]
Before closing this issue, I tested this out using Net3 and ran EpanetSimulator in a loop 3000 times.  No issues.   We suspect this issue has been resolved with updates to EPANET 2.2.
