### ISSUE TITLE
A issue about demand pattern change in simulation

### ISSUE THREAD

**Issue by Vencientwsq** [USEPA/WNTR#211]
Hello，I am trying to use different demand patterns in a simulation, I checked the user's manual but couldn't find the answer.

for example, now my wn.options.time.duration = 12*30*24*3600(one year)  ,and i try to make demand pattern change  (per month/week/day ) 
now I have different daily demand pattern data, how can I add_pattern in every node and run simulation , should i :
if i in range(1,366):
       node_all =wn.get_node()
       node_all.demand_pattern = data[i]#data is the daily demand pattern multiplier

something like this ? I'm so confusing 

All in all,I try to use synthesized data to analyze burst detection  algorithm,with such non-changeable  
demand_pattern simulation  data are not reliable for real applications due to scarce variation.
now i want to use daily pattern (365 different pattern multipliers) in a time.duration = 12*30*24*3600(one year), to change demand_pattern every day.
Thank you for your assistance.

**Comment by Vencientwsq** [comment]
time.duration = 12 * 24 *3600 (one year)

**Comment by Vencientwsq** [comment]
Maybe use the WNTRSimulator Pause and restart?
for i in range(1,366):
pat i = add_pattern (data[i])
node_demand_pattern = pat i
wn.options.time.duration = i*24*3600
sim = wntr.sim.WNTRSimulator(wn)
i days_results = sim.run_sim()

**Comment by dbhart** [comment]
@Vencientwsq - are you trying to change the demand multiplier every day? E.g., 

    one_day_pattern = [12, 12, 12, 15, 15, 15, 12, 12, 12, 8, 8, 8]  # pretending that this is a 2-hour timestep
    yearly_pattern = one_day_pattern * 366  # this is now 366 * 12 numbers long
    wn.add_pattern('yearly', yearly_pattern)
    for name, node in wn.junctions():
        node.demand_timeseries_list[0].pattern_name = 'yearly'

Is this what you are trying to do?
