### ISSUE TITLE
Changing the setting of a valve

### ISSUE THREAD

**Issue by BramHillebrand** [USEPA/WNTR#239]
I want to run several scenario's in which I close and then reopen valves, specifically a FCValve

To achieve this I try to set the setting of the FCValve to 0 via the initial_setting since you cannot manipulate the setting directly.

However after running the simulation using EpanetSimulator the flow rate of my FCValve is still the old setting and not zero

Here is my pseudocode:
`valve = network.get_link('FCV')`
    `valve.initial_setting = 0`
`sim = wntr.sim.EpanetSimulator(network)`
    `results = sim.run_sim()`

I then expect 
`results.link['flowrate']['FCV']` to give 0 but it gives 0.5 (the old setting) So it seems the setting of the valve was not overwritten

**Comment by BramHillebrand** [comment]
I noticed that although I cannot set `valve.setting` I am able to set `valve._setting`
When I do this `results.link['flowrate']['FCV']` does indeed give me 0 (1e-9 to be exact but that is fine) So although I do not understand why my approach above does not work. I think I have a workaround for now

**Comment by dbhart** [comment]
Hi, I’m not sure what the initial setting would be changed, but I think if you only want to open or close the valve you want to use “initial_status” as “Open” or “Closed”.

**Comment by kaklise** [comment]
I created a simple test case where the FCV should limit flow to a downstream junction.  I'm able to change the initial setting using `valve.initial_setting` and the simulation results mimic that setting (in `results.link['flowrate']['FCV']`) at time 0.  
This only works when the valve status is ACTIVE (which can be set using `valve.initial_status = "ACTIVE"`). If the valve status is OPEN, the valve behaves like an open pipe and if the valve status is CLOSED then flow is 0.
