### ISSUE TITLE
Is there a way to explicitly assign the pumping energy to a variable?

### ISSUE THREAD

**Issue by zerateltu** [USEPA/WNTR#24]
Hello,
   Thank you for developing this great tool. I'm wondering if there is a way to extract the pumping energy and assign it to a variable using the tool. I see that the cost of pumping is included in the results generated from "wntr.metrics.cost", however, I'm not able to separate the pumping energy consumption.
    Thanks

**Comment by michaelbynum** [comment]
I believe the wntr.metrics.cost function provides a cost based on the design of the network (investment cost) rather than the operating cost. It sounds like you want the operating cost. Is that correct? I don't think WNTR supports pump operating costs yet.

**Comment by zerateltu** [comment]
Hello Michael, thank you for the reply. 
I read from the "WNTR Documentation-Release 0.1.2 (DRAFT Documentation)" that "**Network cost is the annual maintenance and operations cost of tanks, pipes, vales, and pumps** based on the equations from the Battle of Water Networks II [SOKZ12]. Default values can be included in the calculation. Network cost can be computed using the cost method."(pp42 of the document)

**Comment by michaelbynum** [comment]
Ah, sorry - my mistake - let me clarify. I thought you were looking for the pump cost based on the results of a simulation. The wntr.metrics.cost function does give an estimate of the annual maintenance and operations cost, but it is estimated from the design of the network rather than the results of a simulation. For example, the pumping cost from wntr.metrics.cost provides a cost estimate based off of the maximum power output of the pump (not the actual flowrate of water through the pump at a given time). 

Can you specify exactly what you are looking for?

@kaklise Can you confirm what I have said?

**Comment by kaklise** [comment]
That is correct.   Cost includes maintenance and operations from a design perspective.  The annual cost is a function of max power.  The user can change these values, but the default is from the BWNII problem description.

**Comment by zerateltu** [comment]
Thank you both for your clarification.
Michael your initial guess is right. I'm trying to extract the pumping energy based on actual demand at each junction (simulation results). I'm working on a project that looks at the impact of rain harvest system on the water distribution system (e.g. change of demand, energy consumption and average water age).

**Comment by michaelbynum** [comment]
Okay, in that case, WNTR does not currently support what you are looking for. It should not be difficult to add though. I will try to add this functionality early next week.

Nothing computed in wntr.metrics.cost depends on simulation results.

**Comment by zerateltu** [comment]
Thanks Michael!

**Comment by michaelbynum** [comment]
zerateltu,
Are you using price patterns? That is going to take me a bit longer to implement. Other than price patterns, I almost have this finished - I just need to add a couple tests.

**Comment by zerateltu** [comment]
Hello Michael,
   Thank you for the quick update. My primary goal is to be able to extract the pumping energy from the simulation. It will be great if I can also obtain the corresponding maintenance cost and GHG emissions.
   Regards

**Comment by michaelbynum** [comment]
Pull request #25 should take care of this issue. There is now a pump_energy function in the metrics module to compute pump energy and cost from simulation results. See http://wntr.readthedocs.io/en/latest/apidoc/wntr.metrics.economic.html#wntr.metrics.economic.pump_energy for detailed information.
