### ISSUE TITLE
error in "chemical concentration using a water quality simulation" example

### ISSUE THREAD

**Issue by pracapaulo** [USEPA/WNTR#244]
Hi, i have tried to run this example code:
wn.options.quality.parameter='CHEMICAL'
source_pattern = wntr.network.elements.Pattern.binary_pattern("SourcePattern",
                                                              start_time=2*3600, end_time=15*3600,
                                                              step_size=3600, duration=7*24*3600)
wn.add_pattern('SourcePattern',source_pattern)
wn.add_source('Source1', '121', 'SetPoint', 1000,'SourcePattern')
wn.add_source('Source2', '123', 'SetPoint', 1000,'SourcePattern')
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

And i get this error: File "C:\Users\pprac\.conda\envs\machinelearning\lib\site-packages\wntr\epanet\toolkit.py", line 173, in _error
    raise EpanetException('EPANET Error {}'.format(self.errcode))

EpanetException: EPANET Error 200

Any help?

Thanks

**Comment by kaklise** [comment]
When I run this code using Net3, the simulation runs and the results look good.   Which version of WNTR are you using?

**Comment by pracapaulo** [comment]
Hi, thanks for your answer. 
You are write, the code is good. My problem was, I have wrote this code after other instructions that somehow lead to the error.
Once again thanks,
Paulo Praça
