### ISSUE TITLE
UnicodeDecodeError when INP file name or INP path contains accented letters

### ISSUE THREAD

**Issue by hyperprogram2** [USEPA/WNTR#245]
Hi,

Following error occurs with when trying to open an INP file with accented letters in the file name or the path name.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 6539: invalid continuation byte

For example :
fichier_epanet_inp = 'D:/z_DATA/zz_Temp/TEST/accentué.inp'
wn = wntr.network.WaterNetworkModel(fichier_epanet_inp)

Regards

**Comment by dbhart** [comment]
EPANET does not support Unicode characters. I will look into why a filename would not load correctly.

**Comment by azharsalman** [comment]
this happens even when I try to load a file like this
inp_file = 'test.inp'
wn = wntr.network.WaterNetworkModel(inp_file)

Can you please provide a fix for this ASAP?

**Comment by hyperprogram2** [comment]
Hello,
In addition, the error also occurs when the INP file contains accented letters (in the name of junctions, links or patterns ...)

**Comment by dbhart** [comment]
EPANET only supports ASCII characters. This means no accents or unicode (utf-8/utf-16) characters will work with EPANET. This is a limitation of EPANET, and you can certainly reach out to that team to see if they can update it (it is C/C++ code that uses 8-bit chars instead of 16-bit wide chars).

**Comment by hyperprogram2** [comment]
Hmmmm...

Epanet v2. 0 or v2. 2 works fine with accented characters.

The same inp file with accented works fine with epanet v2.0 or v2. 2 but not with WNTR

**Comment by dbhart** [comment]
Well shoot. I was missing that 'ascii' is not the same as 'latin-1', which the EPANET toolkit uses. That is to say, EPANET uses standard C 8-bit characters but the 'ascii' encoding is actually 7-bit characters.

I have written a patch that will go up in the current PR, I apologize for that mistake.

**Comment by dbhart** [comment]
@hyperprogram2 @azharsalman this should now be fixed in ``main``.
