### ISSUE TITLE
Overflow boolean

### ISSUE THREAD

**Issue by carmine1990** [USEPA/WNTR#250]
Hello Everybody,

using YES (like it's suggested by EPA's guide, or TRUE/True/1) on the overflow field (tank) the assert on wntr.network.model.py give an error:
code (line 1958):
_assert isinstance(overflow, (type(None), bool)), "overflow must be a Boolean"_

I had commented the line and now the script and the simulation run fine.

**Comment by kaklise** [comment]
#251 resolves this issue.  Thanks!
