### ISSUE TITLE
Issue with Resilience Metric - Modified Resilience Index

### ISSUE THREAD

**Issue by lar3763** [USEPA/WNTR#252]
Howdy! I am trying to calculate the Todini Index and Modified Resilience Index for a specific water network. I have looked through the API and it seems that "wntr.metrics.hydraulic.modified_resilience_index" does not exist in the package. I have downloaded the latest version, but this seems weird to me. Can anyone offer any help to resolve this issue? Thanks in advance!

**Comment by ucchejbb** [comment]
https://github.com/USEPA/WNTR/blob/main/wntr/metrics/hydraulic.py
Todini - Line 182
Modified RI - Line 242

Of the main branch. 

You will likely have to install this version using the instructions for setup.py.

**Comment by lar3763** [comment]
Thank you for the quick response. Would I have to uninstall the version I have at the moment or could I just download setup.py and run it in Python? Any advice would be greatly appreciated.

**Comment by ucchejbb** [comment]
@lar3763 You will need to use the 'python setup.py develop' option that is in the readthedocs. You should be able to do this without uninstalling the old version, although you can uninstall it just to be safe if you'd like.

**Comment by lar3763** [comment]
I have followed the steps from readthedocs, and I am still unsuccessful in being able to calculate the Modified RI. Anything other help you could suggest? @ucchejbb

**Comment by kaklise** [comment]
I'm working on a new release for WNTR that will include the modified resilience index when WNTR is downloaded from pypi and conda.  I hope to have that done in the next few days.  The instructions above should work (installing WNTR from GitHub), but your python environment could still be pointing to the old version.  After importing WNTR, you can check the version number using `wntr.__version` and the file location using `wnrt.__file__`

**Comment by kaklise** [comment]
This issue has been resolved with the release of v0.4.1.   Note that if you're using a Windows machine, you'll need to install WNTR using PyPI (#255).
