### ISSUE TITLE
Please add Python 3.10 support

### ISSUE THREAD

**Issue by jjstickel** [USEPA/WNTR#254]
Please add Python 3.10 support. Thanks.

**Comment by jjstickel** [comment]
As reported in #194, it is possible to generate the necessary library for Python 3.10 in the sources of the latest release:
1. set `use_swig` and `build` to True in setup.py
2. execute the command `python setup.py build_ext --inplace`
3. use pip to install your local copy of wntr with `pip install --user -e [path to wntr]

**Comment by DanielHabenicht** [comment]
As the PR is merged when can we expect a new release? :)

**Comment by kaklise** [comment]
Thanks for inquiring.  It took us a while to finalize the new build/release process that works without the precompiled files.  I think we have that wrapped up now.  I plan to post the release by the end of the week.

**Comment by kaklise** [comment]
WNTR 0.5.0 has been tagged.  The release is available through PyPI.  We're working on some issues with the conda release.

**Comment by DanielHabenicht** [comment]
@kaklise Works for python3.10 on linux. 

But I get the same error still if I use it with pyscript, it uses `wntr-0.5.0-py3-none-any.whl`. 
Is this the conda release issue?

**Comment by kaklise** [comment]
I should remove `wntr-0.5.0-py3-none-any.whl`, that was uploaded by mistake.  It still works, but the code needs to be built by the user.  The other wheels that are specific to an operating system and python version (e.g., `
wntr-0.5.0-cp310-cp310-win_amd64.whl`) should not have this issue.

**Comment by DanielHabenicht** [comment]
Alright, please keep us updated when you release a 0.5.1 without the `any` wheel. 

Seems like adding support for wntr running inside the WASM environment of pyscript needs some more [work](https://github.com/pyodide/pyodide/issues/3305).

**Comment by kaklise** [comment]
The `any` wheel has been removed from the 0.5.0 release on PyPI.  The github actions should push directly to PyPI on our next release (there was an issue with the token).  I'm not familiar with the pyodide package you referenced, I'll take a look.

**Comment by DanielHabenicht** [comment]
Thanks! I think you can close this issue then :) 

It just crossed my mind that executing WNTR in WASM (in Browser) would enable enabling a faster and up to date version of https://github.com/sdteffen/epanet.js (+ all WNTR specific stuff)
