### ISSUE TITLE
"ValueError: could not convert string to float: '8 AM'" when reading inp file

### ISSUE THREAD

**Issue by LeoKad** [USEPA/WNTR#256]
Hi, i am getting this value error when i am trying to read the Mesopolis.inp file.
ValueError: could not convert string to float: '8 AM'

It stems from the Rules in that .inp file, where for some rules times in AM and PM are given. 

Is there a way to go around that and change the inp file? How does WNTR treat these rules and which units are compatible?

Thanks a lot!

**Comment by kaklise** [comment]
@dbhart, can you look into this issue?

**Comment by dbhart** [comment]
@LeoKad I think that if you change it from 8 AM to 8:00 AM or 8:00:00 AM it should work, at least it has for me. Single times, like just the hour, seem to cause our parser some problems. If it still doesn't work, please let me know, but I think this will solve your issue.
