### ISSUE TITLE
Epanet Python Simulation

### ISSUE THREAD

**Issue by henryco123** [USEPA/WNTR#258]
![1](https://user-images.githubusercontent.com/101436098/165402708-34fe8e0e-07bb-42e5-aad2-4e33aa68461a.PNG)
![2](https://user-images.githubusercontent.com/101436098/165402705-3dd9d60a-a52a-4b60-af35-6577ad149a64.PNG)

I have the pressure results for the different nodes as it is in the table in figure 1. I tried to plot the pressure results for a few of the entire system and nodes on a probability density curve and cumulative density curve, but I had the error in figure 2. 

Please, can someone please help me with the right codes as I am on standstill and I have been battling to no avail.

**Comment by kaklise** [comment]
I assume you are trying to plot the distribution of pressure at select junctions.  Looks like the code you're using to create a subset is not needed (Nodes is already a subset of the results), however this only includes one timestep (24*3600) so this won't make for an interesting distribution.

Using simulation results from Net 3 (`getting_started` example), the following code works for me.

```
import seaborn as sns
import matplotlib.pylab as plt

plt.figure()

subset_of_junctions = ['123', '201', '141']

for junc_name in subset_of_junctions:
    junc_pressure = results.node['pressure'].loc[:,junc_name]
    sns.distplot(junc_pressure, hist=False, kde=True)

plt.xlabel('Pressure')
```

**Comment by kaklise** [comment]
For the entire system, you'd just use the following (no loop)
```
sns.distplot(results.node['pressure'], hist=False, kde=True)
```

**Comment by henryco123** [comment]
Hi Katherine,

Your first suggestion worked perfectly.

But the shape was not smooth and the size was very small.

Please, how can I adjust this? Pardon my many questions, I am only new to
this and getting started gradually.
Also, please, what does the code look like when I try to adjust the size of
each pipe diameter differently and generating results for each simulation
when I closed each of the pipes.

Thanks

**Comment by kaklise** [comment]
Smoothness will depend on the number of nodes and timesteps in simulation results. KDE can be very misleading for small sample sizes. 

The following include examples that modify network attribute (like diameter) and run pipe criticality analysis (closing one pipe for each simulation).

https://wntr.readthedocs.io/en/latest/waternetworkmodel.html#iterate-over-elements
https://wntr.readthedocs.io/en/latest/getting_started.html#additional-examples

**Comment by henryco123** [comment]
Thanks USEPA/WNTR for your help.
