### ISSUE TITLE
Difference between 'leak_demand' and 'demand' using WNTR instead of EPANET sim

### ISSUE THREAD

**Issue by gabrielication** [USEPA/WNTR#262]
Hi,
I am simulating different events inside the ``Net3.inp`` example network while using WNTR as the simulator engine. 

I have noticed the presence of the ``leak_demand`` value when I am adding some leaks inside randomly selected nodes. I feel that this field is not properly documented in the Wiki because it is not clear if ``leak_demand`` represents the current demand with the effect of the leakage already added in, or a separated value to be added to the original ``demand`` value.

Since ``leak_demand`` is not present inside the classic EPANET simulator, I have deduced that it represents the first case by checking on the ``test_network_leaks.py`` file inside the library from line 88:

```python
        for node_name, node in wn.nodes():
            if node_name != "leak1":
                for t in results.node["demand"].index:
                    self.assertLessEqual(
                        abs(
                            results.node["demand"].at[t, node_name]
                            - epanet_results.node["demand"].at[t, node_name]
                        ),
                        0.00001,
                    )
            else:
                for t in results.node["leak_demand"].index:
                    self.assertLessEqual(
                        abs(
                            results.node["leak_demand"].at[t, node_name]
                            - epanet_results.node["demand"].at[t, node_name]
                        ),
                        0.00001,
                    )
```

I do not know if my hypothesis is 100% correct so a confirmation from you and a report inside the Wiki is largely appreciated :)

Thank you for your time.

**Comment by kaklise** [comment]
This is confusing.  In the WNTRSimulator total demand = `demand` + `leak_demand` .  When using the EpanetSimulator, only `demand` is reported. This is the total demand which could include an emitter.

The test was set up to compare EPANET with an emitter to WNTR with a leak demand. The leak junction has no other demand.  
In the test, the EpanetSimulator `demand` will equal WNTRSimulator `demand` on junctions that DO NOT include the emitter and the EpanetSimulator `demand` will equal WNTRSimulator `leak_demand` on junctions that DO include the emitter.   We'll make sure this is included in the documentation.

**Comment by gabrielication** [comment]
Now it is clear. Thank you very much @kaklise :)

**Comment by kaklise** [comment]
Thanks, the documentation has been updated.
