### ISSUE TITLE
HOW TO CALL INPUTE DATA FROM EPANET TO PYTHON

### ISSUE THREAD

**Issue by henryco123** [USEPA/WNTR#264]
Hi All,

Please, how do i call up my input data for my links, diameter, length, roughness and node characteristics, elevation, demand from epanet to python jupyter notebook.

wn.link['diameter', 'length', 'roughness']
wn.node['demand','elevation']

Thanks.

**Comment by ucchejbb** [comment]
@henryco123 I am assuming you are asking how to access information to change it programmatically.

You can work through wn.get_link(LINK_NAME) or wn.get_node(NODE_NAME) where LINK_NAME or NODE_NAME are string names associated with the network. 
wn.get_link(LINK_NAME).diameter or 
wn.get_link(LINK_NAME).length would access those properties for example. 

The trickiest of these is nodal demand: 
wn.get_node(node).demand_timeseries_list[0].base_value = value

Hope that helps.

**Comment by henryco123** [comment]
Hi Jonathan,

Should I want to get the entire nodes/pipe properties in the system and not
just a single node/pipe property how should that look as a Python code?

Thanks.

**Comment by kaklise** [comment]
I suggest reviewing https://wntr.readthedocs.io/en/latest/waternetworkmodel.html#water-network-model.  That includes information on how to access and query node and link attributes.
