### ISSUE TITLE
Emitter coeff. behave differently after saving to inp file

### ISSUE THREAD

**Issue by cmdgy** [USEPA/WNTR#268]
Dear admin,
I'm new to wntr, so please tell me if I made any mistakes.
In my case, when dealing with emitter coefficient, wntr and EPANET GUI returned different result on the same inp file. 
It seems that, when wntr loads an inp file with CMH units(or build up the network by scratch using add_junction, add_pipe) and runs a simulation,
the temp.inp file that wntr generates bahaves differently calculating leaks from emitter compared with the original file(or the same network buillt in EPANET GUI).

I found a workaround to this problem, which is to manually set the units of wn object to 'CMH':
`wn_10_GPM.options.hydraulic.inpfile_units = 'CMH'`

Check my example in the attachment, Thanks for your time.
[wntr_emitter_problem.zip](https://github.com/USEPA/WNTR/files/8821475/wntr_emitter_problem.zip)

**Comment by kaklise** [comment]
Thanks for posting this issue and example.  I think I found the bug.  I can push an update soon and can include the example as a test.

**Comment by kaklise** [comment]
The conversion factor was incorrect for the emitter coefficient.  I just merged an update (PR #270) which resolves this issue.  When I reran the example you provided the emitter coefficient, pressure and leak metrics are the same for each case.  The update is now available in the main branch and will be included in the next release.
