### ISSUE TITLE
AttributeError in wntr.metrics.economic.pump_cost

### ISSUE THREAD

**Issue by bernardo-suez** [USEPA/WNTR#274]
When calculating pump energy costs I'm getting an attribute error 'WaterNetworkModel' object has no attribute 'energy' [here](https://github.com/USEPA/WNTR/blob/89f73a870337a0b49ea4923d3920d9e62dd51341/wntr/metrics/economic.py#L398). I believe the fix would be to replace `if wn.energy.global_pattern is None:` by `if wn.options.energy.global_pattern is None:`.

**Comment by dbhart** [comment]
You are absolutely correct. Do you want to create a fix and be a contributor? :-)

**Comment by bernardo-suez** [comment]
Absolutely. I'll send the fix later today.

**Comment by kaklise** [comment]
Closed by #306
