### ISSUE TITLE
How can I get the list of data include pressure of start node, pressure of end node and pipe that connect between them?

### ISSUE THREAD

**Issue by YanisaMadmay** [USEPA/WNTR#277]
Hi, I am new to python and WNTR
I am working with my dissertation and almost of the equation that I used need the data of the pressure from start node, pressure from end node and the pipe that linke between them. I did not know they can have a specific coding to deal with this problem or not. I already did the coding my myself and I get struck as the attaching picture. I try to create table to get the name of the start and the end node however the pressure that I have contain in different time level so it said that the dimension is not match. Moreover, I cannot find the way to get the name of link between them.

![image](https://user-images.githubusercontent.com/93888486/176391230-6b98fda9-61aa-4e46-a1ef-539418a62d68.png)

![image](https://user-images.githubusercontent.com/93888486/176391677-ab7b4c67-4c84-4a33-811d-6b5d8d0de809.png)
This is the example of pressure 

![image](https://user-images.githubusercontent.com/93888486/176391922-21746ba4-6485-46c1-a93f-b21dbf4c76b0.png)
This is wahat exactly inside the table I try to create.

**Comment by ucchejbb** [comment]
@YanisaMadmay Are you trying to look at start->end segments longer than a single pipe, or just trying to find pressures at the start and end node of a given pipe? I'm reading it as just the single pipe. I would start by just iterating over the pipes themselves, and creating a dataframe with link name, start and end nodes, and start and end pressures. The link has start_node and end_node information.

So something like this--
for pipe in wn.link_name_list:
    startnode = wn.get_link(pipe).start_node.name
    endnode = wn.get_link(pipe).end_node.name

    # assuming you have a results object
    pressure_at_startnode = results.node['pressure'][startnode]
    pressure_at_endnode = results.node['pressure'][endnode]

Depending on what type of analysis you are doing, you will likely need to multiindex your storage dataframe either over time, or over pipes. Hopefully that helps.

If you are trying to do segments, you will likely have to rely on shortest path analysis between nodes, but then flow direction should also likely be considered which will make it a little more complicated. That relies on the NetworkX functionality, and that is reasonably well documented.

**Comment by YanisaMadmay** [comment]
Thank you so much. I already solve this problem.
