### ISSUE TITLE
Am I able to run two pumps in parallel?

### ISSUE THREAD

**Issue by davitens** [USEPA/WNTR#278]
I am loading a .inp file with pumps disposed in parallel. After I run my code and I save the .inp file with winter, the parallel pumps dissapear and only one of them is shown. How can I solve it?

Before loading network with WNTR:
![image](https://user-images.githubusercontent.com/58690384/176716031-e9223338-223a-4ba8-86ac-006cf7e2ef18.png)

After loading network with WNTR:
![image](https://user-images.githubusercontent.com/58690384/176716185-43ea3891-329c-417b-a99b-304fa66c8cc8.png)

**Comment by davitens** [comment]
Thanks for the info, I guess pumps were just overlaying.

**Comment by ucchejbb** [comment]
@davitens See https://github.com/USEPA/WNTR/issues/223 for more information on the vertex issue. But I'm glad that the pump information was not being lost.
