### ISSUE TITLE
simulation code breaking at a particular value

### ISSUE THREAD

**Issue by uthmankareem** [USEPA/WNTR#280]
Hello,
I have a data matrix of 1000 scenarios of a network which I am running a simulation on. The moment I get to 61st scenario, I get a key error of 0 after querying the pressure to know which pipes are greater than the threshold. I discovered that the index of this gave me a value of 9900 or varying sometimes as against the regular zero. So it gives key error 0 because of that and the code breaks. I tried finding the index within the loop and another issue came up as the result of the query does bring out anything in some instances and the loop stops. I could paste the code if needed.
Please I need your help on this.
The error message below:
:\Users\Uthman\Anaconda3\lib\site-packages\wntr\sim\core.py:1299: UserWarning: Simulation did not converge at time 00:00:00. Reached maximum number of iterations: 2999
  warnings.warn('Simulation did not converge at time ' + self._get_time() + '. ' + mesg)
KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-11-0cbbb3c00261> in <module>
     63     pressure_above_threshold = wntr.metrics.query(pressure_m_df, np.greater,threshold)
     64     pressure_above_threshold = pressure_above_threshold.T
---> 65     pressure_below_threshold_lst = pressure_above_threshold.index[pressure_above_threshold[0] == False]
     66     sum_to_subtract_from_denom = denominator_df[pressure_below_threshold_lst].values.sum()
     67     num_SSI = denom_SSI - sum_to_subtract_from_denom

**Comment by kaklise** [comment]
It looks like the simulation does not converge at the first timestep and the simulation results might not be created.  The WNTRSimulator includes some options to set simulation options (like the number of iterations and convergence thresholds), but it's also possible that the 61st scenario is not feasible.  It would be worth investigating how that scenario differ from the previous scenarios.  Can you provide a minimal example that produces the same error?

**Comment by uthmankareem** [comment]
Hello,
Thank you for your response. I wrote my code algorithm in a different format. It ran past the 61st scenario now. I want to run every scenarios before making any other comments on if everything is okay or not. But in the meantime, I will like to get a link to where I can alter the number of iterations and convergence thresholds. 

Best regards,
Uthman Kareem

**Comment by kaklise** [comment]
See `solver_options` in the documentation for the WNTRSimulator `run_sim`. 
 https://wntr.readthedocs.io/en/latest/apidoc/wntr.sim.core.html#wntr.sim.core.WNTRSimulator.run_sim

**Comment by uthmankareem** [comment]
Hello,
When I extend the number of iterations above 100, my code breaks again at scenario 125. However, I decided to change the simulator to epanet simulator instead of wntr, the epanet simulator ran the code perfectly up to desired value(900 for now). I do have two concerns. I am not sure if epanet simulator is suitable for pressure driven simulation. Also, I added leak and breaks to my network using wntr method. Will that be effective with the epanet simulator?
You would recall I said my simulation using wntr method ran up to 100. So when I compared the first output 100 outputs of each methods(both wntr and epanet simulator), they were different. average of each was about 9.8 and 9.06. I need your help please. Thank you.
Also, if you think I am using the wrong method to model leak and pipe breaking with epanet, kindly help with reference on how to use epanet to model leak and pipe breaks. Otherwise, I just want to be sure if what I did here is correct. 
Please find my code below:
new2 is a dataframe of 1000 by 317. 1 represents pipe break while 2-5 represents different type of leaks. Thank you.

start = time.time()
threshold = 14.0649
num_ssi = []
for i in range(200):
    all_pipe = new2[i]
    leak=list(all_pipe[all_pipe!=0].index)
    wn = wntr.network.WaterNetworkModel('MOD.inp')
    if len(leak)!=0:
        for pipe in leak:
            if all_pipe.loc[pipe]==1:
                a = str(pipe)+'nodeA'
                b = str(pipe)+'nodeB'
                wn = wntr.morph.link.break_pipe(wn, str(pipe), str(pipe)+'B', a, b, add_pipe_at_end=True, split_at_point=0.5)
            elif all_pipe.loc[pipe] == 2:
                d = wn.get_link(str(pipe))
                D = d.diameter
                t = 0.0002
                p = 1
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=t*p*D*np.pi, start_time=0, end_time=24*3600)
            elif all_pipe.loc[pipe] == 3:
                d = wn.get_link(str(pipe))
                D = d.diameter
                theta = 0.5*np.pi/180
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=theta*0.5*np.pi*D**2, start_time=0, end_time=24*3600)
            elif all_pipe.loc[pipe] == 4:
                L=13
                d = wn.get_link(str(pipe))
                D = d.diameter
                theta = 0.1*np.pi/180
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=L*D*theta, start_time=0, end_time=24*3600)
            elif pipe == 5:
                k1=0.5
                k2=0.5
                d = wn.get_link(str(pipe))
                D = d.diameter
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=np.pi*k1*k2*D**2, start_time=0, end_time=24*3600)
    else:
        wn = wntr.network.WaterNetworkModel('MOD.inp')
    wn.options.hydraulic.demand_model = 'PDD'  #pressure-driven simulation
            #Setting simulation time
            #hydraulic simulation uses H-W as default, even gives option to specify how you want to approx. H-W 
    sim_time_seconds = 3600*24
    wn.options.time.duration = sim_time_seconds  #Simulation duration (seconds)
    sim = wntr.sim.EpanetSimulator(wn)
    results = sim.run_sim() # by default, this runs EPANET 2.2.0
    pressure_m_df = results.node['pressure'].iloc[:1]
    demand_df = results.node['demand'].iloc[:1]
    denominator_df = demand_df * pressure_m_df
    denom_SSI = denominator_df.values.sum()
    pressure_above_threshold = wntr.metrics.query(pressure_m_df, np.greater,threshold)
    pressure_above_thresholdT = pressure_above_threshold.T
    pressure_below_threshold_lst = pressure_above_thresholdT.index[pressure_above_thresholdT[0] == False].tolist()
    sum_to_subtract_from_denom = denominator_df[pressure_below_threshold_lst].values.sum()
    num_SSI = denom_SSI - sum_to_subtract_from_denom
    num_ssi.append(num_SSI)
print(num_ssi)
print(sum(num_ssi)/200)
end = time.time()
print("run time:", end - start)

**Comment by uthmankareem** [comment]
Hello,
When I extend the number of iterations above 100, my code breaks again at scenario 125. However, I decided to change the simulator to epanet simulator instead of wntr, the epanet simulator ran the code perfectly up to desired value(900 for now). I do have two concerns. I am not sure if epanet simulator is suitable for pressure driven simulation. Also, I added leak and breaks to my network using wntr method. Will that be effective with the epanet simulator?
You would recall I said my simulation using wntr method ran up to 100. So when I compared the first output 100 outputs of each methods(both wntr and epanet simulator), they were different. average of each was about 9.8 and 9.06. I need your help please. Thank you.
Also, if you think I am using the wrong method to model leak and pipe breaking with epanet, kindly help with reference on how to use epanet to model leak and pipe breaks. Otherwise, I just want to be sure if what I did here is correct.
Please find my code below:
new2 is a dataframe of 1000 by 317. 1 represents pipe break while 2-5 represents different type of leaks. Thank you.

**Comment by uthmankareem** [comment]
Hello,
When I extend the number of iterations above 100, my code breaks again at scenario 125. However, I decided to change the simulator to epanet simulator instead of wntr, the epanet simulator ran the code perfectly up to desired value(900 for now). I do have two concerns. I am not sure if epanet simulator is suitable for pressure driven simulation. Also, I added leak and breaks to my network using wntr method. Will that be effective with the epanet simulator?
You would recall I said my simulation using wntr method ran up to 100. So when I compared the first output 100 outputs of each methods(both wntr and epanet simulator), they were different. average of each was about 9.8 and 9.06. I need your help please. Thank you.
Also, if you think I am using the wrong method to model leak and pipe breaking with epanet, kindly help with reference on how to use epanet to model leak and pipe breaks. Otherwise, I just want to be sure if what I did here is correct.
Please find my code below:
new2 is a dataframe of 1000 by 317. 1 represents pipe break while 2-5 represents different type of leaks. Thank you.


start = time.time()
threshold = 14.0649
#threshold = 20
num_ssi = []
for i in range(980):
    all_pipe = new2[i]
    leak=list(all_pipe[all_pipe!=0].index)
    wn = wntr.network.WaterNetworkModel('MOD.inp')
    if len(leak)!=0:
        for pipe in leak:
            if all_pipe.loc[pipe]==1:
                a = str(pipe)+'nodeA'
                b = str(pipe)+'nodeB'
                wn = wntr.morph.link.break_pipe(wn, str(pipe), str(pipe)+'B', a, b, add_pipe_at_end=True, split_at_point=0.5)
            elif all_pipe.loc[pipe] == 2:
                d = wn.get_link(str(pipe))
                D = d.diameter
                t = 0.0002
                p = 1
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=t*p*D*np.pi, start_time=0, end_time=24*3600)
            elif all_pipe.loc[pipe] == 3:
                d = wn.get_link(str(pipe))
                D = d.diameter
                theta = 0.5*np.pi/180
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=theta*0.5*np.pi*D**2, start_time=0, end_time=24*3600)
            elif all_pipe.loc[pipe] == 4:
                L=13
                d = wn.get_link(str(pipe))
                D = d.diameter
                theta = 0.1*np.pi/180
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=L*D*theta, start_time=0, end_time=24*3600)
            elif pipe == 5:
                k1=0.5
                k2=0.5
                d = wn.get_link(str(pipe))
                D = d.diameter
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=np.pi*k1*k2*D**2, start_time=0, end_time=24*3600)
    else:
        wn = wntr.network.WaterNetworkModel('MOD.inp')
    wn.options.hydraulic.demand_model = 'PDD'  #pressure-driven simulation
            #Setting simulation time
            #hydraulic simulation uses H-W as default, even gives option to specify how you want to approx. H-W 
    sim_time_seconds = 3600*24
    wn.options.time.duration = sim_time_seconds  #Simulation duration (seconds)
    sim = wntr.sim.EpanetSimulator(wn)
    results = sim.run_sim() # by default, this runs EPANET 2.2.0
    pressure_m_df = results.node['pressure'].iloc[:1]
    demand_df = results.node['demand'].iloc[:1]
    denominator_df = demand_df * pressure_m_df
    denom_SSI = denominator_df.values.sum()
    pressure_above_threshold = wntr.metrics.query(pressure_m_df, np.greater,threshold)
    pressure_above_thresholdT = pressure_above_threshold.T
    pressure_below_threshold_lst = pressure_above_thresholdT.index[pressure_above_thresholdT[0] == False].tolist()
    sum_to_subtract_from_denom = denominator_df[pressure_below_threshold_lst].values.sum()
    num_SSI = denom_SSI - sum_to_subtract_from_denom
    num_ssi.append(num_SSI)
print(num_ssi)
print(sum(num_ssi)/980)
end = time.time()
print("run time:", end - start)

**Comment by uthmankareem** [comment]
Hello,
When I extend the number of iterations above 100, my code breaks again at scenario 125. However, I decided to change the simulator to epanet simulator instead of wntr, the epanet simulator ran the code perfectly up to desired value(900 for now). I do have two concerns. I am not sure if epanet simulator is suitable for pressure driven simulation. Also, I added leak and breaks to my network using wntr method. Will that be effective with the epanet simulator?
You would recall I said my simulation using wntr method ran up to 100. So when I compared the first output 100 outputs of each methods(both wntr and epanet simulator), they were different. average of each was about 9.8 and 9.06. I need your help please. Thank you.
Also, if you think I am using the wrong method to model leak and pipe breaking with epanet, kindly help with reference on how to use epanet to model leak and pipe breaks. Otherwise, I just want to be sure if what I did here is correct.
Please find my code below:
new2 is a dataframe of 1000 by 317. 1 represents pipe break while 2-5 represents different type of leaks. Thank you

The code is in pdf and also pasted directly below the pdf.
[epanet issue.pdf](https://github.com/USEPA/WNTR/files/9129057/epanet.issue.pdf)

start = time.time()
threshold = 14.0649
#threshold = 20
num_ssi = []
for i in range(980):
    all_pipe = new2[i]
    leak=list(all_pipe[all_pipe!=0].index)
    wn = wntr.network.WaterNetworkModel('MOD.inp')
    if len(leak)!=0:
        for pipe in leak:
            if all_pipe.loc[pipe]==1:
                a = str(pipe)+'nodeA'
                b = str(pipe)+'nodeB'
                wn = wntr.morph.link.break_pipe(wn, str(pipe), str(pipe)+'B', a, b, add_pipe_at_end=True, split_at_point=0.5)
            elif all_pipe.loc[pipe] == 2:
                d = wn.get_link(str(pipe))
                D = d.diameter
                t = 0.0002
                p = 1
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=t*p*D*np.pi, start_time=0, end_time=24*3600)
            elif all_pipe.loc[pipe] == 3:
                d = wn.get_link(str(pipe))
                D = d.diameter
                theta = 0.5*np.pi/180
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=theta*0.5*np.pi*D**2, start_time=0, end_time=24*3600)
            elif all_pipe.loc[pipe] == 4:
                L=13
                d = wn.get_link(str(pipe))
                D = d.diameter
                theta = 0.1*np.pi/180
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=L*D*theta, start_time=0, end_time=24*3600)
            elif pipe == 5:
                k1=0.5
                k2=0.5
                d = wn.get_link(str(pipe))
                D = d.diameter
                k = str(pipe) + 'leak_node'
                wn = wntr.morph.split_pipe(wn, str(pipe), str(pipe)+'B', k, return_copy = False)
                leak_node = wn.get_node(k)
                leak_node.add_leak(wn, area=np.pi*k1*k2*D**2, start_time=0, end_time=24*3600)
    else:
        wn = wntr.network.WaterNetworkModel('MOD.inp')
    wn.options.hydraulic.demand_model = 'PDD'  #pressure-driven simulation
            #Setting simulation time
            #hydraulic simulation uses H-W as default, even gives option to specify how you want to approx. H-W 
    sim_time_seconds = 3600*24
    wn.options.time.duration = sim_time_seconds  #Simulation duration (seconds)
    sim = wntr.sim.EpanetSimulator(wn)
    results = sim.run_sim() # by default, this runs EPANET 2.2.0
    pressure_m_df = results.node['pressure'].iloc[:1]
    demand_df = results.node['demand'].iloc[:1]
    denominator_df = demand_df * pressure_m_df
    denom_SSI = denominator_df.values.sum()
    pressure_above_threshold = wntr.metrics.query(pressure_m_df, np.greater,threshold)
    pressure_above_thresholdT = pressure_above_threshold.T
    pressure_below_threshold_lst = pressure_above_thresholdT.index[pressure_above_thresholdT[0] == False].tolist()
    sum_to_subtract_from_denom = denominator_df[pressure_below_threshold_lst].values.sum()
    num_SSI = denom_SSI - sum_to_subtract_from_denom
    num_ssi.append(num_SSI)
print(num_ssi)
print(sum(num_ssi)/980)
end = time.time()
print("run time:", end - start)

**Comment by kaklise** [comment]
Without the INP file this is hard to debug, but the PDF includes the following Warning

`REQUIRED PRESSURE is below the lower limit for EPANET (0.1 in psi or m). The value has been set to 0.1 in the INP file.`

When the required pressure is very low, PDD simulations will produce results that are nearly identical to DD simulations.  As for scenarios failing, this can occur if the network becomes infeasible to solve.  I suggest including a try/except block to allow the script to continue running even if one scenario fails.

**Comment by uthmankareem** [comment]
Thank  you for your response. There is no way I could import mod.inp here as it is not allowed. I thought the error was telling me the pressure was approximated to 0.1 instead of 0.07. I was wrong then. What do you suggest I do in this case?
Also, I later used wntr simulator to ru the same code by reducing the tolerance and it ran so far. However, I still want to be able to use epanet simulator so I can compare both.

**Comment by kaklise** [comment]
I suggest setting the required pressure to a higher value.  We generally use ` wn.options.hydraulic.required_pressure = 21.097` where 21.097 m = 30 psi.  You can also change the value in the INP file. Keep in mind that required pressure is network specific and can also change across the network.

**Comment by uthmankareem** [comment]
Hello,

Thank you for this. I will consider this. I use 14.068 for the wntr simulator. So if I decide to change the required pressure to 21.097 for epanet simulator, do I have to change the required pressure I use for wntr simulator to 21.097 as well so as to be able to compare both?
Also, I will like to be able to change the required pressure in the INP file. Do you have a link on how I can do that?
I appreciate.

**Comment by kaklise** [comment]
In the INP file, look for "Required Pressure", this will be set in the units for the INP file.  

In WNTR, both simulators (EpanetSimulator and WNTRSimulator) use the value set in `wn.options.hydraulic.required_pressure`. This is populated by the value in the INP file and can be modified in WNTR.

**Comment by uthmankareem** [comment]
okay. Thank you. I will do that
