### ISSUE TITLE
Pipe Leak 

### ISSUE THREAD

**Issue by YanisaMadmay** [USEPA/WNTR#281]
Hello,

I would like to know from https://github.com/USEPA/WNTR/blob/main/examples/stochastic_simulation.py, if it is possible to get the leak rate from this code. My aim is to use the leak model to estimate the total leak that can occur in my water network for the whole period of time. And finally, plot the graph of the leak rate varying in different time periods. However, I believe I can adjust the coding from the previous code to save my time. Can you guide me on how to deal with that?

![image](https://user-images.githubusercontent.com/93888486/178459310-e968555b-5d43-4f37-bbe7-654b9e7f15ae.png)

Thank you so much for your supporting.

**Comment by kaklise** [comment]
In that example, the simulated leak demand is stored in `results[i].node['leak_demand']`.  The added leak junctions should have non-zero values for leak demand.

**Comment by YanisaMadmay** [comment]
![image](https://user-images.githubusercontent.com/93888486/179351260-e0fd7352-99d4-4cb6-880d-9de31d8fb055.png)
I use this code to see for the leak_demand result and it cause zero. Did I missunderstand something? Becasue I expect that there is some value of leakage in there for me to get the possibility of the pipe leak.

**Comment by YanisaMadmay** [comment]
I would explained more that I think the coding from  https://github.com/USEPA/WNTR/blob/main/examples/stochastic_simulation.py is allow me to get the possibility of the leakage scenario in the water network. Therefore, I could get the leak demand from this stimulation.
Really appreciate for your help

**Comment by kaklise** [comment]
I believe this has been resolved, or is duplicated by newer issues #284 and #286
