### ISSUE TITLE
Error 200

### ISSUE THREAD

**Issue by henryco123** [USEPA/WNTR#282]
Hi All, I have tried from looking at the responses from precious error issues yet I could not get it right. Can someone please, help me look at these codes and error message to help me solve this problem. I am held at a point since I am trying to run different failure/disruptive scenarios that would produce negative pressure. Thanks All.
<img width="723" alt="1" src="https://user-images.githubusercontent.com/101436098/178819221-1b438564-6e08-444c-8607-7c198e0f82e1.PNG">
<img width="680" alt="2" src="https://user-images.githubusercontent.com/101436098/178819262-3f635214-c40c-4f95-a31f-33dfa14d1638.PNG">

**Comment by ucchejbb** [comment]
Does the original INP file run without the leak modifications? Error 200 is fairly generic, just that there was an error, so I would look at the original file and the generated temp.inp file to see if anything jumps out at being wrong.

**Comment by henryco123** [comment]
> Does the original INP file run without the leak modifications? Error 200 is fairly generic, just that there was an error, so I would look at the original file and the generated temp.inp file to see if anything jumps out at being wrong.

Thank you for your help.
