### ISSUE TITLE
Coordinates of link vertices not converted using wntr.morph.convert_node_coordinates_UTM_to_longlat

### ISSUE THREAD

**Issue by jermaine1ronquillo** [USEPA/WNTR#283]
Hello,

When using wntr.morph.convert_node_coordinates_UTM_to_longlat to convert the model only the coordinates of the nodes are converted but the vertices remain the same resulting to straight line in the model when plotted or exported back to *.inp file.

Thank you for the continuous update of this library.

**Comment by kaklise** [comment]
Thanks for pointing this out.  The vertices should be converted in all the coordinate conversion options in WNTR.  This should be an easy fix.  I'll look into it.

**Comment by kaklise** [comment]
This issue has been resolved by #332
