### ISSUE TITLE
Unit for simulate leak 

### ISSUE THREAD

**Issue by YanisaMadmay** [USEPA/WNTR#284]
Hi, I would like to add leak to my network by using stochastic based on following this link.
https://github.com/USEPA/WNTR/blob/main/examples/stochastic_simulation.py
I looked into the documentary and observed that the unit that is used in  my network is different from the unit that is used in the preogramme.
![image](https://user-images.githubusercontent.com/93888486/181096156-a3853b15-610c-4471-894f-372909a037f9.png)
My network unit for each element is listed below:
dimater (mm)
flow (LPS)
velocity (m/s)
unit headloss (m/km)
Demand (LPS)
My question is that I need to change the unit of
1. pipe diameter from mm to m to calculate the area of leak
2. the gaugae pressure in the pipe or p Pa.  How is this come from? Is it coming from the pressure node that I need to change the pressure at every node from m to PSI ?
This is really confuse because when I look at the example to add leak in NET3 I observed that it no need to change any unit although the NET3 have pipe dimeter unit in inch and demand unit is GPM. But it already has the pressure unit in PSI.
3. From the example coding: What is the 0.3 that multiple pipe dimeter to get leak diamter comefrom? It seem that no need to change the unit of pipe diameter.
![image](https://user-images.githubusercontent.com/93888486/181100024-5be84c8c-1001-4515-afe3-c1b3696b9ef4.png)
4. From the Net 3 the result of leak demand is in unit equal to m3/s right?
![image](https://user-images.githubusercontent.com/93888486/181100811-e0b6eacd-6fc0-4a7d-8afa-0de740a90624.png)

I already attached my network, which is the common reference network called BAK.
[BAK.txt](https://github.com/USEPA/WNTR/files/9192890/BAK.txt)

5 . Lastly, if I want to use stochastic to randomly add leak to the pipe, can I use the failure probability based on the pipe diameter like the eaxample? And this mean I did not need to use "split the pipe" for pipe break but I can use "add leak" directly.
I really appreciated if someone can answer it really important to my study. Thank you so much.

**Comment by kaklise** [comment]
1. When you load in the INP file into WNTR, the units of all network properties will be converted to SI units (see https://wntr.readthedocs.io/en/stable/units.html for more details).  Note that when I tried to load BAK.txt  into WNTR, it did not recognize "si" as a valid EPANET Unit Convention.  I think you need to change this to "LPS".  
2. The leak demand is computed by the WNTRSimulator (using the equation above).  This uses gauge pressure in Pa, but you don't need to compute that.  The leak demand that is returned in the results object is in m^3/s (see "leak_demand" in the example).
3. The 0.3 multiplier is just reducing the diameter of the leak to a value that is less than the diameter of the pipe.  That value can be updated as you see fit.  That should be clarified in the example.
4. Correct, leak demand is in m^3/s
5. You can define the failure probability using pipe diameter (as in the example) or using other properties.  You can't add a leak to a pipe directly, that is why the pipe is split and a leak is added to a new junction along the pipe.

I hope that helps!

**Comment by YanisaMadmay** [comment]
I really appreciate for that, Thank you so much

**Comment by YanisaMadmay** [comment]
Hi, I have a question with regard to the leak simulation.
After I installed valve using WNTR function and I want to simulate leak to see the different of leak before and after installation the valve. Unfortunaelty, it shows that the leak is zero I did know how to fix this. Could someone please pointout the mistake that can be solved.
![image](https://user-images.githubusercontent.com/93888486/182670780-17949910-584f-4cdd-b7dc-47569927d6e1.png)
This is the py file .
[production_no_loop_v2.zip](https://github.com/USEPA/WNTR/files/9253727/production_no_loop_v2.zip)

**Comment by YanisaMadmay** [comment]
็Hi Katherine Thank you so much for replying me. I have another important
question. After I use optimization and installed valve ( after simulate
leak),.Next I want to compare result before and after I install PRV.
In this case, the leakage need to reduce, but i got zero like it did not
simulate the leakage at all. Here is my example Pythin file, could you
please suggest how can I fix this problem?
[image: image.png]

ในวันที่ จ. 1 ส.ค. 2022 เวลา 21:48 Katherine Klise ***@***.***>
เขียนว่า:

**Comment by kaklise** [comment]
Closing this issue, the original question has been resolved and the new question was resubmitted as #286
