### ISSUE TITLE
Negative Pressure Irrespective of Running WNTRSimulator

### ISSUE THREAD

**Issue by henryco123** [USEPA/WNTR#285]
Hi All,

I still happen to encounter a similar issue. It worked the first time, and now it goes negative. Please Can anyone help me with a quick perusal because I am restrained at the moment and I have tried almost everything.

[TITLE]

[JUNCTIONS]
;ID              	Elev        	Demand      	Pattern         
 1               	210         	0.5         	1               	;
 3               	225         	0.0045      	1               	;
 4               	230         	0.00        	1               	;
 5               	220         	2.0         	1               	;
 2               	230         	0.045       	1               	;
 0               	240         	2.0         	1               	;

[RESERVOIRS]
;ID              	Head        	Pattern         
 6               	265         	                	;

[TANKS]
;ID              	Elevation   	InitLevel   	MinLevel    	MaxLevel    	Diameter    	MinVol      	VolCurve        	Overflow

[PIPES]
;ID              	Node1           	Node2           	Length      	Diameter    	Roughness   	MinorLoss   	Status
 3               	1               	3               	120         	180         	100         	0           	Open  	;
 7               	4               	5               	150         	90          	100         	0           	Open  	;
 5               	3               	4               	100         	200         	100         	0           	Open  	;
 4               	1               	2               	100         	200         	100         	0           	Open  	;
 6               	2               	4               	90          	100         	100         	0           	Open  	;
 2               	0               	1               	93.00       	200         	100         	0           	Open  	;
 1               	6               	0               	50          	200         	100         	0           	Open  	;

[PUMPS]
;ID              	Node1           	Node2           	Parameters

[VALVES]
;ID              	Node1           	Node2           	Diameter    	Type	Setting     	MinorLoss   

[TAGS]

[DEMANDS]
;Junction        	Demand      	Pattern         	Category

[STATUS]
;ID              	Status/Setting

[PATTERNS]
;ID              	Multipliers
;Sim_Net
 1               	0.3         	0.3         	0.2         	0.2         	0.2         	0.4         
 1               	0.6         	0.7         	0.8         	0.9         	0.9         	0.9         
 1               	0.9         	0.9         	0.9         	0.8         	0.8         	0.7         
 1               	0.7         	0.6         	0.6         	0.4         	0.3         	0.2         

[CURVES]
;ID              	X-Value     	Y-Value

[CONTROLS]

[RULES]

[ENERGY]
 Global Efficiency  	75
 Global Price       	0
 Demand Charge      	0

[EMITTERS]
;Junction        	Coefficient

[QUALITY]
;Node            	InitQual
 3               	170

[SOURCES]
;Node            	Type        	Quality     	Pattern

[REACTIONS]
;Type     	Pipe/Tank       	Coefficient

[REACTIONS]
 Order Bulk            	1
 Order Tank            	1
 Order Wall            	1
 Global Bulk           	0
 Global Wall           	0
 Limiting Potential    	0
 Roughness Correlation 	0

[MIXING]
;Tank            	Model

[TIMES]
 Duration           	48:00 
 Hydraulic Timestep 	0:15 
 Quality Timestep   	0:05 
 Pattern Timestep   	1:00 
 Pattern Start      	0:00 
 Report Timestep    	1:00 
 Report Start       	0:00 
 Start ClockTime    	12 am
 Statistic          	NONE

[REPORT]
 Status             	Yes
 Summary            	No
 Page               	0

[OPTIONS]
 Units              	LPS
 Headloss           	H-W
 Specific Gravity   	1.0
 Viscosity          	1.0
 Trials             	40
 Accuracy           	0.001
 CHECKFREQ          	2
 MAXCHECK           	10
 DAMPLIMIT          	0
 Unbalanced         	Continue 10
 Pattern            	1
 Demand Multiplier  	1.0
 Demand Model       	PDA
 Minimum Pressure   	0
 Required Pressure  	0.1
 Pressure Exponent  	0.5
 Emitter Exponent   	0.5
 Quality            	None mg/L
 Diffusivity        	1
 Tolerance          	0.01

[COORDINATES]
;Node            	X-Coord           	Y-Coord
1               	3175.047          	4450.652          
3               	4659.978          	5117.057          
4               	6220.736          	4503.902          
5               	7257.525          	4481.605          
2               	4804.905          	3946.488          
0               	1850.613          	4448.161          
6               	-66.890           	5440.357          

[VERTICES]
;Link            	X-Coord           	Y-Coord

[LABELS]
;X-Coord             Y-Coord             Label & Anchor Node

[BACKDROP]
  DIMENSIONS  	0.000             	0.000             	10000.000         	10000.000         
 UNITS          	None
 FILE           	
 OFFSET         	0.00            	0.00            

[END]

#Code Normal 

import wntr

import matplotlib.pyplot as plt

plt.style.use('classic')

%matplotlib inline

import seaborn as sns

import numpy as np

import pandas as pd

import math

# Create a water network model

inp_file = 'C:/Users/orime/Downloads/Modified_Network.inp'

wn = wntr.network.WaterNetworkModel(inp_file)

sim = wntr.sim.EpanetSimulator(wn)

results = sim.run_sim()

pressure_at_24hr = results.node['pressure'].loc[24*(3600), :]

#Leak on Node 3

# Create a water network model and simulate under Leak conditions

inp_file = 'C:/Users/orime/Downloads/Modified_Network.inp'

wn = wntr.network.WaterNetworkModel(inp_file)

wn.options.hydraulic.demand_model = 'PDD'

node = wn.get_node('3')

node.add_leak(wn, area=0.05, start_time=8*3600, end_time=18*3600)

sim = wntr.sim.WNTRSimulator(wn)

Leak_Node_3 = sim.run_sim()

Leak_Node_3_Pressure=Leak_Node_3.node['pressure']

Please, Help.

**Comment by kaklise** [comment]
Looks like all the junctions have positive pressure and the pressure at the reservoir is very slightly negative.  Even with PDD, small negative values can occur with both the EPANETSimulator and WNTRSimulator.
