### ISSUE TITLE
networkx==2.0 throws unhashable type: 'dict' 

### ISSUE THREAD

**Issue by kevbroch** [USEPA/WNTR#29]
venv/local/lib/python3.5/site-packages/networkx/classes/function.py", line 648, in set_node_attributes
    G.nodes[n][name] = values                    
TypeError: unhashable type: 'dict'  

I reverted to 1.11 ( pip install networkx==1.11 )  and problem when away.  
Here's link to migration guide: https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by kaklise** [comment]
Thanks for letting us know.  We'll get this fixed soon.

**Comment by kaklise** [comment]
Pull request #31 should take care of this issue.  Travis CI is still pulls in networkX v1.11, but we tested locally with v2.0.

**Comment by kaklise** [comment]
Travis CI is passing with networkx 2.0

**Comment by bakerwho** [comment]
I get this bug again in 2.1. Exactly as described by OP.

**Comment by mkoponen** [comment]
Can confirm. Reverted to 1.11 .

**Comment by kaklise** [comment]
The current version of WTNR is tested with networkx version 2.1.  The current test creates a networkx graph from a WNTR WaterNetworkModel using wn.get_graph(), this method calls set_node_attributes in networkx.  What version of WNTR are you using?  And when do you get the error?

**Comment by mkoponen** [comment]
I didn't notice that this isn't the group for networkx, but a software that uses it. I should file this report at networkx instead. The following code demonstrates the bug in networkx 2.1 (throws exception) and works correctly in 1.11

import networkx as nx                                                                                                                                                          
G = nx.Graph()                                                                                                                                                                 
pos = {0:(1.0,2.0), 1:(1.5,2.5)}                                                                                                                                               
G.add_node(0)                                                                                                                                                                    
G.add_node(1)                                                                                                                                                                         
nx.set_node_attributes(G, 'coord', pos)

**Comment by mkoponen** [comment]
I see bakerwho already did so. Networkx's official answer is that the syntax of the function was changed to following:

nx.set_node_attributes(G, values=values, name=name)

If bakerwho indeed got this error from WNTR, then it should be a simple matter of finding all calls to set_node_attributes and changing them to the new syntax. On the other hand, perhaps he made the same mistake as I, and found this by searching for the error and finding the original report, in which case this can be closed again.

**Comment by kaklise** [comment]
No problem.  WNTR has been updated to use the new syntax.

**Comment by wolfiex** [comment]
> nx.set_node_attributes(G, values=values, name=name)

Well, that's one way to break all legacy code... 

There really should be atleast a message within the error telling you that reversing the arguments may be the cause.

**Comment by kaklise** [comment]
Are you getting this error when using WNTR? or when using NetworkX?  Where `nx.set_node_attributes` is used within WNTR, the argument names `value` and `name` are used to avoid this error.
