### ISSUE TITLE
test sim result -> tests done in setup class instead of test function 

### ISSUE THREAD

**Issue by Thaulino** [USEPA/WNTR#290]
I think the proper way of testing would be to put the test code into a test function of the test class not in the setup function.

Please refer to: 
test_sim_results.py

kind regards

**Comment by kaklise** [comment]
This test just sets up a results object and tolerances.  No actual test is run.  This file was added for functionality we might add in the future.  It could be removed or ignored for now.

**Comment by Thaulino** [comment]
Hi @kaklise, 
Thanks for reviewing the issue, you are right - no tests are running, everything is fine. I somehow misinterpreted the test code.
