### ISSUE TITLE
Convert networkX back to wntr object?

### ISSUE THREAD

**Issue by palexbg** [USEPA/WNTR#296]
Hello,

I have just started playing with this package and successfully went through some networkX manipulations using the example Net3.inp file.

Now that I have done changes to the networkX graph object, I am wondering if there is a way to generate an .inp file out of it? 

I thought it would be possible to first convert a networkX to a wntr object and then export to .inp, but I can only see a function to convert wntr to networkX, not the other way around?

Thank you

**Comment by kaklise** [comment]
That is correct, WNTR can create a NetworkX graph from a WaterNetworkModel, but not the other way around.  That would be a great new feature in WNTR!  It might be easiest to convert the NetworkX graph to a dictionary or JSON (using NetworkX methods) and then reformat that data structure to use the WaterNetworkModel methods 'from_dict' or 'read_json`.  

See https://wntr.readthedocs.io/en/latest/waternetworkmodel.html#read-and-write-a-model-to-a-dictionary-or-json-file for links to the read/write methods in WNTR that use dictionaries and JSON.

**Comment by palexbg** [comment]
Thank you, @kaklise !
