### ISSUE TITLE
add_outage does not simulate power outage in results

### ISSUE THREAD

**Issue by astuhlmacher** [USEPA/WNTR#299]
I am unable to get the add_outage function working. I am trying to run a simulation where pumps lose power for a range of time. However, when I look at the results of run_sim, the pumps are on during the power outage time range. 

I included a minimal working example using Net3. Is there an error in this code?

```
import matplotlib.pyplot as plt
import wntr

# Create a water network model
inp_file = 'networks/Net3.inp' 
wn = wntr.network.WaterNetworkModel(inp_file)

# Modify the water network model
wn.options.time.duration = 24*3600 # 24 hour scheduling horizon
wn.options.time.hydraulic_timestep = 3600 #every 1 hour
wn.options.hydraulic.required_pressure = 14.065 #[m] 14.065m=~20psi
wn.options.hydraulic.minimum_pressure = 0 # [m]
wn.options.hydraulic.demand_model = 'PDD' # pressure-driven demand 

# Set the pump outages
pump335_idx = range(5,17) #1-hour time periods where there is a pump power outage
pump10_idx = range(7,16)

pump335_status = 'OUT (Start: {}, End: {}).'.format(pump335_idx[0], pump335_idx[-1])
pump335 = wn.get_link('335') # River
pump335.add_outage(wn, pump335_idx[0]*3600, end_time=pump335_idx[-1]*3600) #start_time, end_time

pump10_status = 'OUT (Start: {}, End: {}).'.format(pump10_idx[0], pump10_idx[-1])
pump10 = wn.get_link('10') # Lake
pump10.add_outage(wn, pump10_idx[0]*3600, end_time=pump10_idx[-1]*3600)  

# Run Hydraulic Simulator
sim = wntr.sim.WNTRSimulator(wn)#wntr.sim.EpanetSimulator(wn)#
print('Scenario: Pump 335 is ' + pump335_status + ' Pump 10 is ' + pump10_status)
results = sim.run_sim()  
   
# Plot pump status                    
plt.figure()
pumpstatus = results.link['status'][['10','335']]
pumpstatus.index /= 3600
pumpstatus.plot(ax=plt.gca())
plt.ylabel('Pump Status (ON=1)')
plt.grid(True)
```
>Scenario: Pump 335 is OUT (Start: 5, End: 16). Pump 10 is OUT (Start: 7, End: 15).

![pumpstatus](https://user-images.githubusercontent.com/7557750/191345726-16892076-848d-4d7d-84a8-0dcf26e1228d.png)

I can verify that a rule is created for each pump:
```
print(wn.get_control('335_outage'))
print(wn.get_control('10_outage'))
```
>IF  SYSTEM TIME ABOVE 05:00:00 AND SYSTEM TIME BELOW 16:00:00  THEN PUMP 335 STATUS IS CLOSED PRIORITY 6
>IF  SYSTEM TIME ABOVE 07:00:00 AND SYSTEM TIME BELOW 15:00:00  THEN PUMP 10 STATUS IS CLOSED PRIORITY 6

**Comment by kaklise** [comment]
Thanks for posting this issue. The power outages are defined as a Rules, however Net3 includes existing Controls that are triggered in a different manner and are overriding the power outage. The key to making these work together is to convert the Controls to Rules.  After you load the INP file to create a WaterNetworkModel (`wn`), you can convert the Controls to Rules using `wn.convert_controls_to_rules()`.  Each Rule has a priority and they will be evaluated in a more consistent way.  Note that the pump may not be powered back on after the power outage if there is not a Rule (or Control) that defines that action.  I'll add a note to the documentation that you often need to convert Controls to Rules when working with power outages.

**Comment by astuhlmacher** [comment]
That fixes it, thanks!
