### ISSUE TITLE
Read and write a model to a dictionary

### ISSUE THREAD

**Issue by joardima** [USEPA/WNTR#307]
In the "_**doc\Water network model**_" from "_https://wntr.readthedocs.io/en/latest/waternetworkmodel.html_" there is a typing mistake, specifically for the topic "_**Read and write a model to a dictionary**".

There, it is stated that to write a model to a dictionary the line "_wn.to_dict()_" should be written even though it should be "_wn.todict()_"

**Comment by kaklise** [comment]
`wn.todict` was changed to `wn.to_dict` in recent changes to WNTR.  In the future, we will use proper deprecation warnings to make this change more clear.  All to/from methods now use an underscore.  For example, WNTR includes `to_dict`, `from_dict`, `to_json` and `from_json`.
