### ISSUE TITLE
Possible wrong calculation of Todini Resilience Index (RI)

### ISSUE THREAD

**Issue by mariocastrogama** [USEPA/WNTR#317]
Hello,

I have been testing the hydraulic metrics and it seems came across a bug. 
In order to present the error I'm sharing an analysis with the [Richmond Skeleton](https://engineering.exeter.ac.uk/research/cws/resources/benchmarks/) benchmark.

I'm setting the model as PDA, with Pf = 20.0 and Po = 0.0 and Pexponent = 0.5.

When I try to calculate the RI, WNTR obtains RI which is outside the expected bounds of [0, 1]. See figure obtained with the code.
 
What seems to be the reason?

Regards,
MarioCG

code used.

   # run_Richmond resilience

    import wntr
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt

    # set parameters
    inpfile = 'Richmond_skeleton.inp'
    totalduration = 24
    Prequired = 20.

    # load inp file
    wn = wntr.network.WaterNetworkModel(inpfile) 

    # set the total duration of the hydraulic simulation hrs in HOURS
    wn.options.time.duration = totalduration*3600

    # set the options for PDA
    wn.options.hydraulic.demand_model = 'PDD'    
    wn.options.hydraulic.required_pressure = Prequired   #  m
    wn.options.hydraulic.minimum_pressure  = 0.0   # m
    wn.options.hydraulic.pressure_exponent = 0.5

    # choose simulator and version
    sim = wntr.sim.EpanetSimulator(wn)
    res = sim.run_sim(version='2.2')

    IR_wntr = wntr.metrics.todini_index(res.node['head'],res.node['pressure'],res.node['demand'],res.link['flowrate'],wn,Prequired)

    # plot the results obtained
    plt.plot(IR_wntr.index/3600,IR_wntr)
    plt.ylim((0.0, 1.0))
    plt.ylabel('RI')
    plt.xlabel('Time (hr)')

**Comment by kaklise** [comment]
Thank you for sending the example, I'll let you know what I find.

**Comment by kaklise** [comment]
The Todini index does not account for additional sources, like tanks or junctions with negative demand.  I believe this is why you’re seeing values outside [0,1]. The Richmond model includes several tanks and a junction with negative demand.  The code that computes the Todini Index in WNTR could be amended with additional logic to account for these elements, but the Modified Resilience Index (MRI), which is computed using only junctions, might be a better option for your network model.  

MRI can be computed as a timeseries per junction or as a timeseries over all junctions.

```
elevation = wn.query_node_attribute('elevation')[wn.junction_name_list]
pressure = res.node['pressure'].loc[:,wn.junction_name_list]
demand = res.node['demand'].loc[:,wn.junction_name_list]

MRI = wntr.metrics.modified_resilience_index(pressure, elevation, Prequired, demand, per_junction=False)

MRI_per_junction = wntr.metrics.modified_resilience_index(pressure, elevation, Prequired, per_junction=True)
```

An MRI value of 0 means that the system (or junction) is operating at its required energy conditions. Positive values mean that there is a surplus, while negative values indicate a deficit. The values can be over 1, but cannot be below –1 if elevation and pressure are positive.

Also keep in mind that the pressure threshold used in the Todini and Modified Resilience Index equations (Pstar) is globally applied to all junctions.  The code could be modified to accept a Pstar value per junction.
