### ISSUE TITLE
issues WNTR simulation

### ISSUE THREAD

**Issue by Armira93** [USEPA/WNTR#326]
i have to run 34410 simulation for a water network. i created a loop that should change base demand of 250 junctions and the total head of 4 reservoirs for each simulation. the problem is that sometimes i got one of this two error messages :
wntr.epanet.toolkit.EpanetException: EPANET Error 304
wntr.epanet.toolkit.EpanetException: EPANET Error 303

i run the Python script for less than 2000 and it worked!
i need your help please :(

**Comment by kaklise** [comment]
We've seen this issue in the past and thought it was resolved with the use of EPANET 2.2.  That said, with that many iterations I suggest adding a try/except block to catch isolated cases that fail (in this case fail to open report and output files).  What version of WNTR and EPANET are you using?

**Comment by Armira93** [comment]
I'm using EPANET 2.2. and WNTR i just installed it with pip, i don't know wich version!  
can you please explain the try/except block ?

thank you!

**Comment by kaklise** [comment]
The fire flow demo at https://github.com/USEPA/WNTR/blob/main/examples/demos/fire_flow_demo.ipynb includes a try/except block to collect information on simulations that failed.
