### ISSUE TITLE
Add leak in multiple nodes with a for loop error

### ISSUE THREAD

**Issue by joardima** [USEPA/WNTR#330]
I'm using Python 3.9 and WNTR 0.3.1.

With the WNTR simulator, _wntr.sim.WNTRSimulator( )_, I'm trying to add leaks in nodes, _node.add_leak( )_, through a for loop (included at the end of this message).

The script runs correctly when a leak is added to one node, however if a leak is added to an odd number of nodes the leak is only add to an even number of nodes.

In the below example the leak is only added to nodes 1 and 3 and not include node 5.

`
for j in [1,3,5]:
                node = WN.get_node(j)
                node.add_leak(
                    wn                  = wn,
                    area                = 0.0005,
                    discharge_coeff     = 0.75,
                    start_time          = 2*3600,
                    end_time            = 3*3600
                    )
`

N.B. 1,3,5 are the names of the nodes wherein I want to add a leak.

How could I solved it?

Thanks in advance.

**Comment by kaklise** [comment]
It's unclear if capitol WN is the same as lowercase wn, but I tested this out with Net3 and the leaks are added to the correct nodes.  See below
```
import wntr

inp_file = 'networks/Net3.inp'
wn = wntr.network.WaterNetworkModel(inp_file)

for j in ['247','249','251']: 
    node = wn.get_node(j) 
    node.add_leak(wn=wn, area=0.0005, discharge_coeff=0.75, start_time=2*3600,  end_time=3*3600)

sim = wntr.sim.WNTRSimulator(wn)
results = sim.run_sim()

leak_demand = results.node['leak_demand']
print(leak_demand.loc[:, leak_demand.sum()>0]) # shows leak demand at nodes 247, 249, and 251
```
