### ISSUE TITLE
Not importing on macOS Ventura 13.2 on M1 Pro CPU (arm64)

### ISSUE THREAD

**Issue by gabrielication** [USEPA/WNTR#331]
## Summary
My program that imports `wntr` stops immediately. It can't find a specific internal module of the library.
 
## Environment

Python 3.9 (venv on Pycharm)
WNTR 0.5.0
macOS Ventura 13.2 on M1 CPU (arm64 architecture)
 
## Example
 
```
Traceback (most recent call last):
  File "/Users/gabriele/Desktop/py_epanet2csv/py_epanet.py", line 1, in <module>
    import wntr
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/__init__.py", line 3, in <module>
    from wntr import morph
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/morph/__init__.py", line 13, in <module>
    from wntr.morph.skel import skeletonize
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/morph/skel.py", line 11, in <module>
    from wntr.sim.core import WNTRSimulator
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/sim/__init__.py", line 5, in <module>
    from wntr.sim.core import WaterNetworkSimulator, WNTRSimulator
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/sim/core.py", line 1, in <module>
    import wntr.sim.hydraulics
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/sim/hydraulics.py", line 13, in <module>
    from wntr.sim import aml
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/sim/aml/__init__.py", line 2, in <module>
    from .aml import Model, ParamDict, VarDict, ConstraintDict, Constraint
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/sim/aml/aml.py", line 3, in <module>
    from .evaluator import Evaluator
  File "/Users/gabriele/Desktop/py_epanet2csv/venv/lib/python3.9/site-packages/wntr/sim/aml/evaluator.py", line 13, in <module>
    from ._evaluator import *
ModuleNotFoundError: No module named 'wntr.sim.aml._evaluator'
```

**Comment by dbhart** [comment]
As an FYI – there is also likely an issue with the EPANET simulator DLL not having been built for ARM/M1. We have not added a pre-complied DLL, because I have not seen one from the OpenWaterAnalytics/EPANET github repo. If there is one there, let me know and I’ll get it added to WNTR.

Otherwise, you may need to compile EPANET yourself and add the DLL to the WNTR installation path. If you choose to go that route, I can help you with the installation of the DLL into WNTR.

All of this is, of course, assuming that you are using the ARM-native build of Python 3. If you aren’t, then it should work as soon as you rebuild as @kaklise specified.

**Comment by gabrielication** [comment]
> As an FYI – there is also likely an issue with the EPANET simulator DLL not having been built for ARM/M1. We have not added a pre-complied DLL, because I have not seen one from the OpenWaterAnalytics/EPANET github repo. If there is one there, let me know and I’ll get it added to WNTR. Otherwise, you may need to compile EPANET yourself and add the DLL to the WNTR installation path. If you choose to go that route, I can help you with the installation of the DLL into WNTR. All of this is, of course, assuming that you are using the ARM-native build of Python 3. If you aren’t, then it should work as soon as you rebuild as @kaklise specified.

Thank you for your support. Yes please, some help with the native compilation will be much appreciated.

**Comment by dbhart** [comment]
Sorry, I have been working on this. I do have a quick question - are you using an M1 native version of python? Or is it using their emulator? If it is the emulator version of python, you should be able to just install wntr using the methods described in WNTR's install instructions. If it is native, that is going to be a little harder, and that's what I'm still working on

**Comment by serbanstan** [comment]
Encountering the same issue on a M2 macbook running Ventura 13. Installing WNTR succeeds after following kaklise’s advice, however running code with WNTR points to missing EPANET dlls. Tried with anaconda python 3.8 and 3.10 as well as the native python version, but got the same result.

**Comment by gabrielication** [comment]
> Sorry, I have been working on this. I do have a quick question - are you using an M1 native version of python? Or is it using their emulator? If it is the emulator version of python, you should be able to just install wntr using the methods described in WNTR's install instructions. If it is native, that is going to be a little harder, and that's what I'm still working on

This issue that I have opened refers to the ARM version (native) for Python. As you have said, there is no native binary for that.

However, right now I am using the Rosetta-translated (x86 emulated) version of Python as a workaround in order to have WNTR working.

As a side note, I have compiled EPANET from the official repository using the native M1 compiler (cmake did all the work) and it went smooth. Let me know if there is a way to integrate this to the compilation of WNTR in order to get it working natively.

Thank you.
