### ISSUE TITLE
How can I join the development of wntr

### ISSUE THREAD

**Issue by Pu-nk** [USEPA/WNTR#337]
Hi, I am a PhD student researching water supply network related direction and would like very much to be involved in the development of the wntr package, what are the ways I can participate in it as an open source project?

**Comment by kaklise** [comment]
Thank you for your interest in contributing to WNTR.  Contributions can include adding new features, improving existing code, updating documentation, or adding tests.  You can review the open issues for ideas, or you can propose a new idea.
