### ISSUE TITLE
Can WNTR auto-calibrate hydraulic model based on SCADA data?

### ISSUE THREAD

**Issue by mark-chung** [USEPA/WNTR#339]
**Summary**
I am new to EPANET and spending many hours trying to calibrate hydraulic model using EPANET. Can I use WNTR auto calibrate based on SCADA data?

**Example**
I have .INP file, and SCADA data at some nodes (Head, Flow Rate). Can I use WNTR to run simulation, and find optimal Loss Coefficient of specific pipes, so that the simulation results match SCADA data? Possible to provide sample usage code for this purpose? Will wntr.sim help to achieve that? Appreciate your advice!

**Comment by kaklise** [comment]
WNTR does not include methods to calibrate models using SCADA data.  This would be a great feature to add to WNTR!  I have come across papers that use WNTR and calibrate water network models, the following paper by Tiedmann et al. comes to mind https://ascelibrary.org/doi/abs/10.1061/%28ASCE%29WR.1943-5452.0001561

**Comment by mark-chung** [comment]
Thanks @kaklise for highlighting that paper!
