### ISSUE TITLE
importing wntr on google colab

### ISSUE THREAD

**Issue by s-u-m-a-n-t-h** [USEPA/WNTR#342]
When I try to import wntr on google colab, I get the following error:

ImportError                               Traceback (most recent call last)
[<ipython-input-3-e8830d14604d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import wntr

8 frames
[/usr/local/lib/python3.9/dist-packages/wntr/sim/aml/evaluator.py](https://localhost:8080/#) in <module>
     11 # Pull in all the attributes from the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from ._evaluator import *
     14 else:
     15     from _evaluator import *

ImportError: numpy.core.multiarray failed to import

Can you please help fix this ?

**Comment by dbhart** [comment]
Hi @s-u-m-a-n-t-h 
I have just tried google collab for the first time. By default, the numpy version is not the newest, so you will need to start all notebooks with the following:

`!pip install --upgrade numpy wntr`

After doing this I was able to import wntr successfully. Please let us know if that works for you also!

**Comment by uthmankareem** [comment]
Hello, 

I was able to update wntr successfully following your advice. However, I was still unable to run simulation as colab does not still recognize wntr when I import wntr. This seems weird. I will be glad to get any other advice on this. 
Thank you.
