### ISSUE TITLE
With skelenazation add as input nodes_list and links_list which cannot be removed

### ISSUE THREAD

**Issue by frank-hulo** [USEPA/WNTR#347]
**Summary**
In some cases you would like to keep certain nodes and pipes within your model. For example at dma boundaries where you would like to keep naming consistent over multiple dma's. Currently only controls are set to be not removed, I also understand that in the example I give that there is a control at a dma boundry, but another example can be give at positions of flow sensor locations. 

**Additional context**
The change is very easy as a list of junc_with_controls and pipe_with_controls, these can easily be extended by a user input and all functionality will stay the same. 

It concerns: wntr/morph/skel/_Skelentonize

**Comment by kaklise** [comment]
This would be a great addition to skeletonization.   The `_Skelentonize` class is typically accessed by the user through the `skeletonize` function, so both would need to be updated.  Would you be interested in adding this update?

**Comment by frank-hulo** [comment]
Yes I can add it. This will be my first, so any guidelines?

**Comment by kaklise** [comment]
Great!  Contributing guidelines are available at https://wntr.readthedocs.io/en/latest/developers.html. In addition to updating the class/function, you'll need to update the documentation (probably just a sentence in morph.rst) and add a test (in test_morph.py).  Then you'll submit a Pull Request to the main branch.  The Pull Request can be a "work in progress", we can review and provide feedback.

**Comment by kaklise** [comment]
Closed by #425
