### ISSUE TITLE
Material and age in network model

### ISSUE THREAD

**Issue by frank-hulo** [USEPA/WNTR#349]
**Summary**
Hi, I was wondering if are there any ideas or developments within this community to add material and pipe age to the network model. I understand that the basis is Epanet, but it might be really interesting in stochastic simulations. I also understand that this data is often available in other files however, most utilities are not fully synced in naming between GIS and hydraulic systems. 

What is your opinion about this?

**Comment by kaklise** [comment]
Custom attributes can be added to any network component, see https://wntr.readthedocs.io/en/latest/waternetworkmodel.html#add-custom-element-attributes for an example.  This can include attributes like material and pipe age, which can be used in stochastic simulations.

WNTR now includes methods to build water network models from GIS data.  See https://wntr.readthedocs.io/en/latest/model_io.html#geodataframe-representation for more information.  To use the `from_gis` method, you can read GIS files (i.e., shapefile, geojson) into Python and create a dictionary of GeoDataFrames.  The column names from a utility database often need to be modified before using this method in WNTR.  

Feel free to post comments on how these capabilities work for you.
