### ISSUE TITLE
Setting "required_pressure" for a local junction node takes no effect in "PDD" mode

### ISSUE THREAD

**Issue by Halkyon64** [USEPA/WNTR#350]
Hi! I built a network and read it from wntr latest (1.0.0) version in python 3.8.
All I am trying to to for a first time - make a simple hydraulic analysis via wntr using PDD mode. But there is a problem: when I set required_pressure in global, i.e. `wn.options.hydraulic.required_pressure = 35`, then it works and I see changing in demand in results after simulation done. But, when I'm trying to set required pressure directly to my junctions nodes without specifying a global required_pressure attribute - values of demand remain the same as in inp file. Here is my code:

```
import math
import wntr
import pandas as pd

inp_file = net_open.inp'

pd.set_option('display.width', 400)
pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 100)

wn.options.hydraulic.demand_model = 'PDD'

# this line is working when uncommented  
# wn.options.hydraulic.required_pressure = 35

# those lines takes no effect ((
wn.get_node('12').required_pressure = 26
wn.get_node('12').minimum_pressure = 0
wn.get_node('12').pressure_exponent = 0.5
wn.get_node('14').required_pressure = 56
wn.get_node('14').minimum_pressure = 0
wn.get_node('14').pressure_exponent = 0.5

sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

for link_name, link in wn.links():
    print(link_name, results.link['flowrate'].loc[:, link_name].mean()*1000)

# show demands
results.node['demand'] * 1000

# show pressure
results.node['pressure']
```

Maybe I've missed something while configuring this network in wntr?

**Comment by Halkyon64** [comment]
ok, I found in docs this remark in [this section](https://wntr.readthedocs.io/en/latest/hydraulics.html#pressure-dependent-demand-simulation):

> The ability to use spatially variable required pressure, minimum pressure, and pressure exponent is only available when using the WNTRSimulator. The EpanetSimulator always uses values in the global hydraulic options.

It seems, there is no way to use local defined pressure for each junk for EpanetSimulator

**Comment by dbhart** [comment]
Sorry Alexey, but yes, it is a limitation at this time of EPANET 2.2.
