### ISSUE TITLE
Question regarding stochastic simulation and leakage

### ISSUE THREAD

**Issue by soroushmisc** [USEPA/WNTR#353]
**Summary**
I used the example codes in this link: [https://github.com/USEPA/WNTR/blob/main/examples/stochastic_simulation.py] with some variations to match my needs.
When I run the code on my inp file, it simulates the network in normal condition (without leakage) and saves the results (notably pressure). Then it resets to initial values and add leakage to pipes randomly (leakage mode). At the end, it calculates the difference in pressure between normal condition and leakage mode : normal pressure minus pressure w/ leakage.

My expectation was to see POSITIVE numbers, but the output head of results are as following: 
name | diff leak
100 | -1.074172974
1000 | -1.418317795
1001 | -1.418317795
1002 | -1.418317795
1003 | -1.418317795

The difference is minus which denotes the pressure in normal state was less than pressure in leakage state.

**Could you help me to understand if I made an error in the code?
If the code is fine, was my expectation wrong?**

**Environment**
Provide information on your computing environment.
 - Operating system: Windows 10
 - Python version: Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
 - Jupyter notebook version: The version of the notebook server is: 6.4.12
 - WNTR version: 0.5.0

### Here's my code:
`import numpy as np
import matplotlib.pyplot as plt
[diffleaks Taghvimi summer.xlsx](https://github.com/USEPA/WNTR/files/11645235/diffleaks.Taghvimi.summer.xlsx)

import pickle
import wntr
import matplotlib
import random

# Create a water network model
inp_file = 'C:\\Users\\sorou\\Taghvimi summer (3).inp'
wn = wntr.network.WaterNetworkModel(inp_file)

wn.options.hydraulic.demand_model = 'PDD'

sim = wntr.sim.EpanetSimulator(wn)
normal_results = sim.run_sim()

# Reset initial values and simulate hydraulics under nominal conditions
wn.reset_initial_values()

# Modify the water network model
wn.options.time.duration = 48*3600
wn.options.time.hydraulic_timestep = 1800
wn.options.time.report_timestep = 1800
wn.options.hydraulic.required_pressure = 18
wn.options.hydraulic.minimum_pressure = 0

# Define failure probability for each pipe, based on pipe diameter. Failure
# probability must sum to 1.  Net3 has a few pipes with diameter = 99 inches,
# to exclude these from the set of feasible leak locations, use
# query_link_attribute
pipe_diameters = wn.query_link_attribute('diameter', np.less_equal,0.9144, link_type=wntr.network.Pipe)
failure_probability = pipe_diameters/pipe_diameters.sum()

# Pickle the network model and reload it for each realization
f=open('wn.pickle','wb')
pickle.dump(wn,f)
f.close()

# Run 5 realizations
results = {} # Initialize dictionary to store results
np.random.seed(85000) # Set random seed
for i in range(1):

    # Select the number of leaks, random value between 1 and 50
    N = np.random.randint(1,50+1)

    # Select N unique pipes based on failure probability
    pipes_to_fail = np.random.choice(failure_probability.index, N,
                                     replace=False,
                                     p=failure_probability.values)

    # Select start time  of failure, uniform dist, between 1 and 10 hours
    time_of_failure = np.round(np.random.uniform(1,10,1)[0], 2)

    # Select duration of failure, uniform dist, between 12 and 24 hours
    duration_of_failure = np.round(np.random.uniform(12,24,1)[0], 2)
   
    # Add leaks to the model
    for pipe_to_fail in pipes_to_fail:
        pipe = wn.get_link(pipe_to_fail)
        leak_diameter = pipe.diameter*0.3
        area=3.14159*(leak_diameter/2)**2
       
        leak_area = random.uniform(0, area)
       
        wn = wntr.morph.split_pipe(wn, pipe_to_fail, pipe_to_fail + '_B', pipe_to_fail+'leak_node')
        leak_node = wn.get_node(pipe_to_fail+'leak_node')
        leak_node.add_leak(wn, area=leak_area,
                          start_time=time_of_failure*3600,
                          end_time=(time_of_failure + duration_of_failure)*3600)

       
       
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

# Plot resulting differences on the network
pressure_at_20hr = results.node['pressure'].loc[20*3600, :]
norm_pressure_at_20hr = normal_results.node['pressure'].loc[20*3600, :]
pressure_difference = norm_pressure_at_20hr - pressure_at_20hr
wntr.graphics.plot_network(wn, node_attribute=pressure_difference, node_size=30, title='Nominal - leakage \npressure difference at 24 hours') 
       
       
#export leaks to excel
pressure_difference.to_excel("diffleaks Taghvimi summer.xlsx")`

Thanks for your time and help in advance. :)
[diffleaks Taghvimi summer.xlsx](https://github.com/USEPA/WNTR/files/11645232/diffleaks.Taghvimi.summer.xlsx)

Best!

**Comment by kaklise** [comment]
Leaks are not compatible with the EpanetSimulator (EPANET models leaks using Emitters).  I believe if you change EpanetSimulator to WNTRSimulator, the difference in pressures will be positive.

**Comment by soroushmisc** [comment]
Hello Katherine @kaklise ,
Thank you for the respond. I have tried the code with WNTRSimulator. There is an error when I ran the code:

> .....anaconda3\lib\site-packages\wntr\sim\core.py:1299: UserWarning: Simulation did not converge at time 08:00:00. Reached maximum number of iterations: 2999
>   warnings.warn('Simulation did not converge at time ' + self._get_time() + '. ' + mesg)

Do you have any idea of the reasons this could happen and how to resolve that, please?
Thanks

**Comment by kaklise** [comment]
You can increase the number of iterations using `sim.run_sim(solver_options={"MAXITER": 6000})`, but this might indicate a larger issue.  For example, if you created many leaks at critical pipes, the system might be able to solve. You should be able to look at simulation results up to the point where the system did not converge.

**Comment by michaelbynum** [comment]
Another couple of suggestions are below. These all stem from the same reasoning which is that large sudden changes to the hydraulics make convergence more difficult.

1. Try decreasing the hydraulic timestep
2. Try making each leak start at a different time
3. Try starting with a smaller leak area and increasing it over a small time frame (e.g., 10 minutes)
