### ISSUE TITLE
in Ability to recognise PBV (Valves using WNTRSimulator)

### ISSUE THREAD

**Issue by henryco123** [USEPA/WNTR#354]
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11704/2318240449.py in <module>
     40 # Run a preliminary simulation to determine if junctions drop below the pressure threshold during normal conditions
     41 sim = wntr.sim.WNTRSimulator(wn)
---> 42 results = sim.run_sim()
     43 min_pressure = results.node['pressure'].loc[:, wn.junction_name_list].min()
     44 below_threshold_normal_conditions = set(min_pressure[min_pressure < pressure_threshold].index)

~\anaconda3\lib\site-packages\wntr\sim\core.py in run_sim(self, solver, backup_solver, solver_options, backup_solver_options, convergence_error, HW_approx, diagnostics)
    829         logger.debug('creating hydraulic model')
    830         self.mode = self._wn.options.hydraulic.demand_model
--> 831         self._model, self._model_updater = wntr.sim.hydraulics.create_hydraulic_model(wn=self._wn, HW_approx=HW_approx)
    832 
    833         if diagnostics:

~\anaconda3\lib\site-packages\wntr\sim\hydraulics.py in create_hydraulic_model(wn, HW_approx)
     93     constraint.fcv_headloss_constraint.build(m, wn, model_updater)
     94     if len(wn.pbv_name_list) > 0:
---> 95         raise NotImplementedError('PBV valves are not currently supported in the WNTRSimulator')
     96     if len(wn.gpv_name_list) > 0:
     97         raise NotImplementedError('GPV valves are not currently supported in the WNTRSimulator')

NotImplementedError: PBV valves are not currently supported in the WNTRSimulator

**Comment by kaklise** [comment]
Thanks for posting this issue.  PBVs are included in the list of limitations for the WNTRSimulator (https://wntr.readthedocs.io/en/latest/framework.html#limitations). This should be straight forward to implement, but it might take us some time to get to it.  Let us know if you are interested in adding this feature, otherwise I'll mark this as an enhancement and keep the issue open.

**Comment by henryco123** [comment]
Hi Katherine, I have now changed the type of valve to PSV. But I have one
greatest challenge below:

[image: image.png]

**Comment by kaklise** [comment]
I'm not able to see the image, it may have been attached to an email instead of posted in GitHub.

**Comment by henryco123** [comment]
<img width="641" alt="Capture" src="https://github.com/USEPA/WNTR/assets/101436098/35414fc4-698f-4d2a-a4c9-4f0a9e6e08a3">

**Comment by kaklise** [comment]
Looks like numpy is trying to multiple a float at NoneType. Can you provide a simple example using WNTR that replicates this issue?
