### ISSUE TITLE
How to get node name where minimum pressure occurs?

### ISSUE THREAD

**Issue by DanielaBS1** [USEPA/WNTR#356]
**Summary**
Hi, I am new here.
I am trying to run my first WNTR code and hoping to apply some graph theory for clustering. 
I have managed to import, run the model and visualize basic results. I can visualize a list of nodes name with relative pressures for a selection of times and basic things like that. However, I am trying to select the node with minimum pressure as I want o to used that node as a start point to apply the minimum path.

I have managed to select the minimum pressure using the 'min' function, but inspite of attempting many different possibilities I have not managed to get the name of the node where the minimum pressure occurs. I am sending a sample of what I have done to get the minimum pressure, I am not sure if it is the correct way to do it. 

I will be very glad if you could help with that simple matter. Many thanks.

import wntr 

sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()
wn = wntr.network.WaterNetworkModel(inp_file)
min_press=min(results.node['head'].loc[5*3600, :])
print(min_press)

**Comment by ucchejbb** [comment]
min_press = results.node['head'][results.node['head']==results.node['head'].loc[5*3600].min()].loc[5*3600].dropna()

That should all be on one line (it currently breaks onto 2 lines as I'm typing). 

When I try that with Net3.inp, I see 2 nodes with the minimum pressure at 5 hours. There might be a more elegant way to do that, but the results object is a pandas dataframe, so you can refer to their functions on how to interact with the data. 

min_press.index returns the list of nodes that are at the minimum pressure.

**Comment by kaklise** [comment]
You can use `results.node['pressure'].loc[:,wn.junction_name_list]` to get pressure at junctions only.
