### ISSUE TITLE
How to Avoid 'Reached maximum number of iterations' 

### ISSUE THREAD

**Issue by ilkehanaksu** [USEPA/WNTR#364]
Dear all,
I'm running simulations with different leak scenarios and saving the concatenated results in a single data frame. 
An error I keep getting is that:

ValueError: Length of values (720) does not match length of index (618)
with the UserWarning:
Simulation did not converge at time 618:00:00. Reached maximum number of iterations: 2999

 --  note: the number 618 keeps changing at every run.

Even though I change the maximum number of iterations and set a high number, I still have the same problem.  
Code runs successfully sometimes without any errors and the results get saved with no problem.
But most frequently I keep receiving the mentioned error.

Could someone please help me to solve this problem I'm facing?

**Comment by kaklise** [comment]
It is possible to define leak scenarios that cause the simulation to not converge.  I suggest storing the leak properties of scenarios that do not converge (leak location, leak rate, timing) and look at the simulations results prior to the convergence issue to see if you can troubleshoot the issue.  You can also add logging to the simulation to get additional information.  To set the logging level to debug, add the following lines to your code.
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

If you have a small example script and INP file that replicates the issue, we can also look into it.
