### ISSUE TITLE
ENsetlinkvalue unexpectedly fails to change attributes

### ISSUE THREAD

**Issue by Pu-nk** [USEPA/WNTR#380]
**Summary**
when I set the status of link, ENsetlinkvalue unexpectedly fails to change attributes

**Example**
import matplotlib.pyplot as plt
import os
import wntr
inp_file_path = "/Users/zehoo/Documents/SHM_SRC/water_networks/anytown_master.inp"
name = os.path.basename(inp_file_path).split('.')[0]
wn = wntr.network.WaterNetworkModel(inp_file_path)
enData = wntr.epanet.toolkit.ENepanet(version=2.2)
enData.ENopen('temp.inp', 'temp.rpt', 'temp.bin')
enData.ENopenH()
enData.ENinitH(1)
from wntr.epanet.util import EN
lid = enData.ENgetlinkindex('78')
aid = EN['STATUS']
enData.ENsetlinkvalue(lid, aid, 0.6)
enData.ENgetlinkvalue(lid, aid)

**Environment**
Provide information on your computing environment.
 - Operating system: 
 - Python version: 3.8
 - WNTR version:0.4.2

**Comment by dbhart** [comment]
Hi @Pu-nk , can you provide the OS you are using?

**Comment by dbhart** [comment]
Note, this is a problem with the Mac version of the EPANET toolkit. Closing this issue for now.
