### ISSUE TITLE
new added control does not work

### ISSUE THREAD

**Issue by TiaHao** [USEPA/WNTR#382]
Hi, I am trying to add new controls to a pump in a network, as following codes: 
 cond = controls.SimTimeCondition(wn, controls.Comparison.ge, '00:00:00')
 act = controls.ControlAction(pump, 'setting', 2)
 act1 = controls.ControlAction(pump, 'status', 1)
 ctrl = controls.Rule(cond, [act1, act], name="control_components_0")
 wn.add_control("control_components_0", ctrl)

sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()

but when I check the setting of the pump after simulation:
results.link['setting'][wn.pump_name_list][pump]
 it shows setting =1 instead of 2.  Does it mean the control does not work at all? How to solve this issue? Thank you!

**Comment by dbhart** [comment]
Hi @TiaHao , this is a case of EPANET rules not being quite clear. When you set the setting to "2", it is automatically changing the status to "active". When you change the status as the second action, it overrides the setting you just changed. So if you want to change the setting, you should only make that action.

If that still does not work, it may be related to the type of pump you have created - not all pumps can take a setting, some are simply on or off, and automatically choose the setting that is appropriate. So you may need to look at the pump definitions in the EPANET manual again to make sure.

I hope that helps

**Comment by TiaHao** [comment]
> Hi @TiaHao , this is a case of EPANET rules not being quite clear. When you set the setting to "2", it is automatically changing the status to "active". When you change the status as the second action, it overrides the setting you just changed. So if you want to change the setting, you should only make that action.
> 
> If that still does not work, it may be related to the type of pump you have created - not all pumps can take a setting, some are simply on or off, and automatically choose the setting that is appropriate. So you may need to look at the pump definitions in the EPANET manual again to make sure.
> 
> I hope that helps

Thank you for your reply. Yes, I can add control for setting only successfully rather a rule control as before.
