### ISSUE TITLE
POSSIBILITY OF NEGATIVE PRESSURE

### ISSUE THREAD

**Issue by uthmankareem** [USEPA/WNTR#391]
**Summary**
Describe your question.
Using wntr pipe leak or pipe break (blocking flow across the pipe)  methodology and model as described in the wntr documentation, is there still possibilty of having negative pressure in any of the nodes in the network? This is considering that the original network does without leak or break does not have any nodes with negative pressure.
Thank you.

**Comment by uthmankareem** [comment]
Thank you. I am using wntr in python module. The elevation distribution is between 31 to 39 meters for the different nodes in the network. Their are 4 reservoirs that do not have negative demands.
Actually, the literature I read advised running the simulation and check for negative pressure. If there are any, the nodes and associated pipes should be deleted and the simulation loop should continue like that until there is a simulation where there are no negative nodes again. Then our network performance can now be calculated. I am just wondering if this is necessary given that the wntr documentation did not state all these details. So I was trying to know if negative nodes have been taken care of in the wntr simulation or the chance of negative pressure nodes is rare and so might be negligible.
I am interested in this so as to shorten my code runtime and perhaps, I do not need to be removing or deleting any pipes. 
Also, note that the literature recommended removing pipes that broken from the network instead of the methodology and model proposed by wntr. So it is important for me to know if the pipe removal methodology warranted the checking and removal of negative pressure nodes which might not necessary with the methodology and model proposed in wntr documentation.
Lastly, if recomending checking of negative pressure nodes, is it more appropriate to remove them from the network by deleting or the methodology and model proposed by wntr documentation will suffice? 
I will be willing to provide more explanation if needed.
Thank you.

**Comment by kaklise** [comment]
I think this decision to remove the pipes depends on your application.  Negative pressures are possible with PDD simulations, however removing pipes will change the hydraulics of the system and might not be needed.  Does the literature your referring to use a DD or PDD simulation?  Please include a citation.

**Comment by uthmankareem** [comment]
This is a PDD simulation. The direct reference is Shinozuka and coworkers (Okumura and Shinozuka, 1991; Shinozuka, et al.,
1981, 1992; Hwang, et al., 1998).
Also, I will also like to know why "https://wntr.readthedocs.io/" is not loading because I am trying to understand why my simulation is throwing "  raise ValueError('cannot infer dimensions from zero sized index arrays')".Is it an issue of non-convergence? Alternatively, how ad where do I access the link with source codes the wntr hydraulic simulation? 
Thank you.

**Comment by kaklise** [comment]
Thanks for the reference.

The user manual is now located at https://usepa.github.io/WNTR/.  

You can find the source code at https://github.com/USEPA/WNTR.  The code for WNTRSimulation class is in https://github.com/USEPA/WNTR/blob/main/wntr/sim/core.py.
