### ISSUE TITLE
Questions about optimal scheduling of pumping stations

### ISSUE THREAD

**Issue by chooron** [USEPA/WNTR#394]
hello, I want to do a pumping station start/stop optimization scheduling to reduce the energy consumption of the pumping station, how should I control the operation state of the pump (open or close) in WNTR, should I use the function `controls.SimTimeCondition`?
In my code, I am constructing an array to formulate the condition object under each time:
`self.time_condition_list = [controls.SimTimeCondition(
            self.wn, '=', f"{i * self.time_step}:00:00") for i in range(time_len)]`
I'm not sure I'm doing this correctly

**Comment by dbhart** [comment]
Hi @chooron 

If I understand correctly, you are trying to optimize the pumping schedule, essentially a list of [on, off, off, on ...] for each hour, and the optimizer will choose the on or off status. 

The code you have above will create a set of conditions for each hour. You will need to have a rule for each hour that will be associated with one of these conditions, and also have an action (on/off, I assume). The list of actions will be what the optimizer will change, I think.

Anyway, I hope that this is helpful, if it doesn't, please comment and I'll see if I can clarify what I was thinking.
