### ISSUE TITLE
runnin the program

### ISSUE THREAD

**Issue by MunsakaPKM** [USEPA/WNTR#397]
i've trying to learn how wntr works hoping to apply it to my academic project, i've been searching for any tutorials but couldn't see any. I tried to create new networks from scratch, but been getting errors only, and even tried running some AI generated scripts but same thing, so frustrrating, how do i do it. Please may i see any example. 

 - Operating system:  windows 10
 - Python version: 3.12
 - WNTR version: 1.1.0

**Comment by kaklise** [comment]
Documentation for WNTR is available at https://usepa.github.io/WNTR/, this includes a getting started guide (https://usepa.github.io/WNTR/getting_started.html) and sections on specific topics like building networks from scratch (https://usepa.github.io/WNTR/waternetworkmodel.html#build-a-model-from-scratch).  WNTR also includes several examples in the examples folder (https://github.com/USEPA/WNTR/tree/main/examples)

**Comment by kbonney** [comment]
@MunsakaPKM. WNTR is not currently tested on Python 3.12. The latest python version that we test is 3.11 - I recommend downgrading your python and trying again.
