### ISSUE TITLE
Writing an inp file 'self' argument error message

### ISSUE THREAD

**Issue by DanielaBS1** [USEPA/WNTR#399]
After adding some controls to a model I am trying to save a new INP file by writing the flowing line:

_wntr.epanet.InpFile.write(filename='d.inp',wn=wn1)_

However I am getting the following error message:

_TypeError: InpFile.write() missing 1 required positional argument: 'self'_

When typing the arguments inside the parenthesis 'self' appears as first variable, but it is not on the documentation. 'self' been a python keyword it seams strange to be a required argument. Is it a bug? I could not work it out, can you advise?

I am using Python 3.10.9  via Spyder.

**Comment by kaklise** [comment]
While you can create an instance of the InpFile class and use its write method, I suggest calling `wntr.network.write_inpfile`, see https://usepa.github.io/WNTR/model_io.html#epanet-inp-file for more details.

**Comment by DanielaBS1** [comment]
Thanks for the suggestion. It did work.
