### ISSUE TITLE
Get the reactions tab in the inp file from a water network instance

### ISSUE THREAD

**Issue by alemanuel995** [USEPA/WNTR#401]
Hello!

I see inside the inp file there are two tabs with the same name: REACTIONS. One of them is inside the options property in a water netrork instance. But I don't understand how to get the other one.

This one is inside options, wich I'm ok with it; I've managed to acess it:

[REACTIONS]
 Order Bulk            	1
 Order Tank            	1
 Order Wall            	1
 Global Bulk           	0.0
 Global Wall           	0.0
 Limiting Potential    	0.0
 Roughness Correlation 	0.0

This is the one I can't acess from the water netrwork instance:

[REACTIONS]
;Type     	Pipe/Tank       	Coefficient

Could you help me?

Thank you!

 - Operating system: Windows 10 64 bits
 - Python version: 3.8
 - WNTR version: 1.1.0

**Comment by dbhart** [comment]
So, there should only be one REACTIONS section in an INP file at a time (actually, only one of any section title). Links to the EPANET documentation can be found at https://github.com/USEPA/EPANET2.2, the official EPANET 2.2 repository. I think the INP file description is listed in Appendix C(?) “Command Line EPANET”. Hope that is helpful
