### ISSUE TITLE
Values in [DEMANDS] section are repetead and others are missing

### ISSUE THREAD

**Issue by alemanuel995** [USEPA/WNTR#411]
**Summary**
When creating a water network object and send it to a new inp file, the values in the [DEMANDS] section are repeated twice and there are values missing in this section from the original inp file.

**Example**
[DEMANDS]
;ID        Demand     Pattern   
6          31.700463  P2         ;Usuario 2
6          31.700463  P2         ;Usuario 2
15         59.438367  P1         ;Usuario 4
15         59.438367  P1         ;Usuario 4

In the original inp file, the [DEMANDS] section looks like this:

[DEMANDS]
;Junction        	Demand      	Pattern         	Category
 6               	15.850231   	P1              	;Usuario 1  
 6               	31.700463   	P2              	;Usuario 2  
 15              	31.700463   	P2              	;Usuario 3  
 15              	59.438367   	P1              	;Usuario 4  

I'm doing it like this:

```
wn.add_junction(name=name, base_demand=base_demand, demand_pattern=demand_pattern,
                        elevation=elevation, coordinates=coordinates, demand_category=demand_category)
junction_1 = wn.get_node(name)
if demand_category is not None:
    junction_1.add_demand(base=base_demand, pattern_name=demand_pattern, category=demand_category)
```

wn variable is the instance of the water network. After adding a junction, I'm acessing that same node to add the demand. If not, the [DEMANDS] section remains empty, wich is worse.

Any sugesstion?
Thank you!

**Comment by kbonney** [comment]
HI @alemanuel995, could you provide a complete example using a network you provide or one of WNTR's example networks?

**Comment by alemanuel995** [comment]
Hi @kbonney,

I'm going to attach here the inp file (in text format) I'm using for this concrete example:
[Red_prueba-GPM-DW 1.txt](https://github.com/USEPA/WNTR/files/14636511/Red_prueba-GPM-DW.1.txt)

Thank you!

**Comment by kbonney** [comment]
@alemanuel995 Thank you. Please also provide a script which reproduces the problem you are encountering.

**Comment by alemanuel995** [comment]
@dbhart, I'm using the same version as you: 1.1.0. There must be something wrong in my code and I'll try to figure out.

Thank you!

**Comment by dbhart** [comment]
@alemanuel995 you're welcome! Just to check, if you run the same code I put in my comment, are you seeing the two different demands also in the dictionaries?

**Comment by alemanuel995** [comment]
@dbhart, yes. I see the two different demands. Thank you!

**Comment by dbhart** [comment]
@alemanuel995 Glad to help!
