### ISSUE TITLE
Cannot import the shortest_path

### ISSUE THREAD

**Issue by Skulldron** [USEPA/WNTR#44]
Hello. 
While freezing code with cx_Freeze I encountered problem with WNTR and SciPy . While trying to launch windows returns traceback:

> Traceback (most recent call last):
> 0 File "C:\DEV\Python\lib\site-packagesch_Freeze\initscripts\_startup_.py", line 14, in run
> 
> module.run()
> 
> File "C:\DEV\Python\lib\site-packages\cx_Freeze\initscripts\ConsoIe.py", line 26, in run
> e\ec(code, m._dict_)
> 
> File "SampleAPP.py", line 18, in < module>
> 
> File "C:\DEV\Python\lib\site-packageszntrLinit_.py", line 1, in < module>
> from wntr import epanet
> 
> File "C\DEV\Python\lib\site- packages\wntr\epanet\_init_.py", line 4, in < module>
> from .io import IoniIe #, BinFiIe, HydFile, RptFiIe
> 
> File "C:\DEV\Python\lib\site-packageszntr\epanet\io.py", line 32, in < module>
> import wntr.network
> 
> File "C\DEV\Python\lib\site- packages\wntr\network\_init_.py", line 6, in < module>
> from .eIements import Junction, Reservoir, Tank, Pipe, Pump, Valve, Pattern, TimeSeries, Demands, Curve, Source
> 
> File "C\DEV\Python\lib\site- packages\wntr\network\elements.py", line 37, in < module>
> from scipy.optimize import fsolve
> 
> File "C\DEV\Python\lib\site- packages\scipy\optimize\_init_.py", line 271, in < module>
> from ._minimize import *
> 
> File "C:\DEV\Python\lib\site-packages\scipy\optimize\_minimize.py", line 21, in < module>
> from scipy.sparse.linalg import LinearOperator
> 
> File "C\DEV\Python\lib\site-packages\scipy\parse\_init_.py", line 241, in < module>
> from . import csgraph
> 
> File "C\DEV\Python\lib\site-packages\scipstparse\csgraphLinit_.py", line 165, in < module>
> from ._shortest_path import shortest_path, floyd_warshall, dijkstraA
> 
> ImportError: cannot import name 'shortest_path'

(Converted this traceback from image with ocr so it can contain some typos. Anyone encountered this problem and knows how to solve it? I would be really thankfull.

![traceback](https://user-images.githubusercontent.com/33962400/40969991-966c27ce-68b9-11e8-85f5-207de173cd6b.png)

I can provide more information if needed.
Im using newest version of wntr, python 3.6.5. 64 bit.

**Comment by michaelbynum** [comment]
I am not familiar with cx_Freeze, but the error appears to come from scipy. Can you try:

from spicy.optimize import fsolve

Without importing wntr?

Michael

On Jun 5, 2018, at 6:12 AM, Skulldron <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello.
While freezing code with cx_Freeze I encountered problem with WNTR and SciPy . While trying to launch windows returns traceback:

Traceback (most recent call last):
0 File "C:\DEV\Python\lib\site-packagesch_Freeze\initscripts_startup_.py", line 14, in run

module.run()

File "C:\DEV\Python\lib\site-packages\cx_Freeze\initscripts\ConsoIe.py", line 26, in run
e\ec(code, m.dict)

File "SampleAPP.py", line 18, in < module>

File "C:\DEV\Python\lib\site-packageszntrLinit_.py", line 1, in < module>
from wntr import epanet

File "C\DEV\Python\lib\site- packages\wntr\epanet_init_.py", line 4, in < module>
from .io import IoniIe #, BinFiIe, HydFile, RptFiIe

File "C:\DEV\Python\lib\site-packageszntr\epanet\io.py", line 32, in < module>
import wntr.network

File "C\DEV\Python\lib\site- packages\wntr\network_init_.py", line 6, in < module>
from .eIements import Junction, Reservoir, Tank, Pipe, Pump, Valve, Pattern, TimeSeries, Demands, Curve, Source

File "C\DEV\Python\lib\site- packages\wntr\network\elements.py", line 37, in < module>
from scipy.optimize import fsolve

File "C\DEV\Python\lib\site- packages\scipy\optimize_init_.py", line 271, in < module>
from ._minimize import *

File "C:\DEV\Python\lib\site-packages\scipy\optimize_minimize.py", line 21, in < module>
from scipy.sparse.linalg import LinearOperator

File "C\DEV\Python\lib\site-packages\scipy\parse_init_.py", line 241, in < module>
from . import csgraph

File "C\DEV\Python\lib\site-packages\scipstparse\csgraphLinit_.py", line 165, in < module>
from ._shortest_path import shortest_path, floyd_warshall, dijkstraA

ImportError: cannot import name 'shortest_path'

(Converted this traceback from image with ocr so it can contain some typos. Anyone encountered this problem and knows how to solve it? I would be really thankfull.

[traceback]<https://user-images.githubusercontent.com/33962400/40969991-966c27ce-68b9-11e8-85f5-207de173cd6b.png>

I can provide more information if needed.
Im using newest version of wntr, python 3.6.5. 64 bit.

**Comment by Skulldron** [comment]
Hello Michael. Thank you for your time.
I checked and tried to add **from scipy.optimize import fsolve** withou importing wntr in APP.py and build.py and cx_Freeze seems to have no problem with that - freezing the file properly. 
Meanwhile I was just trying to make this work even the dirty way, so I decided to add following lines to app.py and build.py file:

```
from scipy.sparse.csgraph import _validation
from scipy.sparse.csgraph import shortest_path
```
And it worked, but cx_Freeze found another error this time with scipy.spatial.ckdtree which cannot be fixed by adding

`from scipy.spatial import ckdtree` 

and throws following:
![trace](https://user-images.githubusercontent.com/33962400/40997228-3fb25de0-6904-11e8-85a4-9642835eb306.PNG)

I don't have idea how to fix this and what is the root of those problems

Also im not sure why even the PyCharm is suggesting following:
![ckd](https://user-images.githubusercontent.com/33962400/40997367-ad907ba8-6904-11e8-9e3e-95baa46bbbbb.png)

Sorry for long post and thank you for your time Michael, would be glad to hear your further advices.

**Comment by joskaaaa** [comment]
@Skulldron Not sure if you had resolved your issue, but (irrelevant as it may be to WNTR): 

When cx_Freeze copies the 'ckdtree.cp36-win_amd64.pyd' file from the lib into your new build folder (\build\exe.win-amd64-3.6\lib\scipy\spatial), it copies it as 'cKDTree.cp36-win_amd64.pyd'.

Simply changing the capitalization on the file should solve your import problem.

**Comment by Skulldron** [comment]
Thank you, @joskaaaa  I solved it but forgot to share it with others. As you said I just changed the filename and it worked like a charm.
