### ISSUE TITLE
Geopandas/fiona incompatibility

### ISSUE THREAD

**Issue by dbhart** [USEPA/WNTR#442]
**Summary**
Tests are failing due to changes in Fiona. We need to upgrade something.

**Example**

```
WARNING  fiona.ogrext:collection.py:541 Skipping field because of invalid value: key='overflow', value=False
WARNING  fiona.ogrext:collection.py:541 Skipping field because of invalid value: key='check_valve', value=False
```

**Environment**
Provide information on your computing environment.
 - Operating system: all
 - Python version: all
 - WNTR version: 1.2

@kaklise @kbonney

**Comment by kaklise** [comment]
Duplicated in #422
