### ISSUE TITLE
wntr.network.io.valid_gis_names(True) contains some values that are not valid GIS Names

### ISSUE THREAD

**Issue by angusmcb** [USEPA/WNTR#449]
**Summary**
`wntr.network.io.valid_gis_names(True) `contains some values that are not valid GIS Names.

Specifically:
- junctions, tanks, and reservoirs   contain `coordinates` which is not a valid GIS name - these are derived from the geometry
- pipes, pumps and valves contain  `vertices` , similarly this is derived from the geometry
- tanks contains `min_volvol_curve_name`  which I think is just a typo

**Environment**
Provide information on your computing environment.
 - WNTR version: 1.2.0

**Comment by angusmcb** [comment]
Also 'power' and 'base_speed' for pumps

**Comment by kaklise** [comment]
Closed by #452
