### ISSUE TITLE
some settable Pipe properties not documented

### ISSUE THREAD

**Issue by samhatchett** [USEPA/WNTR#45]
https://wntr.readthedocs.io/en/latest/apidoc/wntr.network.elements.html#wntr.network.elements.Pipe

not documented are most useful properties: length, diameter, roughness, minor_loss, and others

**Comment by michaelbynum** [comment]
Good point. Thanks for bringing this to our attention. I'll fix this shortly.

**Comment by dbhart** [comment]
@kaklise I believe this is ready to be closed.
