### ISSUE TITLE
Incorrect type on `efficiency` property in Pumps

### ISSUE THREAD

**Issue by smaspons** [USEPA/WNTR#457]
**Summary**
In the documentation, the property `efficiency` on pumps ([HeadPump](https://usepa.github.io/WNTR/apidoc/wntr.network.elements.HeadPump.html#wntr.network.elements.HeadPump.efficiency) & [PowerPump](https://usepa.github.io/WNTR/apidoc/wntr.network.elements.PowerPump.html#wntr.network.elements.PowerPump.efficiency)) states it is of type `float`, but is actually a Curve object (or None if not set).

**Example**
_Doesn't apply, documentation issue_

**Environment**
Documentation page

**Additional context**
![imatge](https://github.com/user-attachments/assets/4e754f43-5e21-48c5-af11-b17ac7e05de6)

**Comment by kbonney** [comment]
Hi @smaspons, thanks for finding this in the documentation. Are you interested in making a PR to address this issue?

**Comment by smaspons** [comment]
Of course, I'd love to. I wasn't sure how to do it since I saw the documentation [source](https://usepa.github.io/WNTR/_sources/apidoc/wntr.network.elements.HeadPump.rst.txt) was very automatic.

Now that I looked into it a bit more I saw this:
https://github.com/USEPA/WNTR/blob/104fc69cf66bfff308104d6b30da1e8ef517e459/wntr/network/elements.py#L1101-L1103

Is this it? Just changing this `float` to `Curve` would work?

I'm sorry, I'm not familiar at all with how this Sphinx documentation works.

I did make a PR if that is all it takes to change it. https://github.com/USEPA/WNTR/pull/459
Correct me if I'm wrong!
Thanks!

**Comment by kaklise** [comment]
Closed by #459
