### ISSUE TITLE
can not open an INP file

### ISSUE THREAD

**Issue by tortelee** [USEPA/WNTR#54]
I use  'wntr.network.WaterNetworkModel' to load an inf file,but occured the error:

  File "D:\anaconda\lib\site-packages\wntr\epanet\io.py", line 615, in _read_pipes
    if current[7].upper() == 'CV':

IndexError: list index out of range
why？

**Comment by tortelee** [comment]
I have found the reason. The file loses a key word

**Comment by qasimAde** [comment]
I am unable to open an inp file in Spyder.

My Error message


  File "C:\Users\qaadegbi\Anaconda3\lib\site-packages\wntr\epanet\io.py", line 289, in read
    for line in f:

  File "C:\Users\qaadegbi\Anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 12: invalid continuation byte

**Comment by qasimAde** [comment]
Please any help will be highly appreciated

**Comment by qasimAde** [comment]
Thanks , I figured it out.

**Comment by yesen001** [comment]
> Thanks , I figured it out.

Hi could you indicate how to figure out this issue? Thanks!

**Comment by kaklise** [comment]
See https://usepa.github.io/WNTR/model_io.html#epanet-inp-file for documentation on how to read an INP file in WNTR.
