### ISSUE TITLE
RuntimeError: networks/Net3.inp:9: Non-comment outside of valid section!

### ISSUE THREAD

**Issue by zizzipupp** [USEPA/WNTR#56]
I installed WNTR 0.1.5 and I am using the following version of Python in Spyder 3:
`3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]`

I re-created, without mistakes, the two scripts performing hydraulic simulations and the interaction with networkx, and have saved them in a folder. In the same folder, I created a sub-folder called "networks", where I saved the .inp files made available on GitHub. 

However, when I run either script, I get the following error:
`RuntimeError: networks/Net3.inp:9: Non-comment outside of valid section!`

This same error occurs when I change .inp file, so I am not sure what happens - never played with .inp files before. That number 9 may point at row 9 in the .inp file, but I could not spot anything weird or that could match the error description.

Any help would be much appreciated.

**Comment by kaklise** [comment]
The number does indicate a line number, but I'm unable to replicate the error.  I'll continue looking into it.

**Comment by michaelbynum** [comment]
@zizzipupp Just to be clear, you got the error without modifying the inp file at all?

**Comment by zizzipupp** [comment]
Exactly. From Chrome, I saved the inp files by right-clicking on the file
names and making sure that they were saved with the correct extension and
in the correct sub-folder.

**Comment by dbhart** [comment]
Is it possible that your browser is saving it in non-ASCII format? Latin-1 and UTF-8 should also be handled, but if there is something else, it’s possible that there is a character (even a blank) that is getting dropped into the INP file that isn’t right. We haven’t been able to reproduce, so it is difficult to think of any other possibilities.

**Comment by dbhart** [comment]
@kaklise I think this issue can be closed

**Comment by AlirezaArabani** [comment]
Actually I faced the same problem. this problem raises during the downloading. Firstly you need to download the file, in the next open the Net3.inp with TextEditor and again open the Net3.inp in Github. easliy copy the codes from Net3.inp in Github and paste then in the downloaded file. please let me know if this method works.
