### ISSUE TITLE
iCode

### ISSUE THREAD

**Issue by Pepukai** [USEPA/WNTR#57]
I am new in programming. trying to use wntr for my research. running
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32 .
and using Spyder to code.
I am trying to use the epanet.toolkit to get values from an inp file however the command requires enter an iCode for the components. How do I get this input.

```
import wntr

inp_file = "umee/hanoi.inp"
wn = wntr.network.WaterNetworkModel(inp_file)

wntr.graphics.plot_network(wn, title=wn)

wntr.epanet.toolkit.runepanet(inp_file)
wntr.epanet.toolkit.ENepanet(inpfile="umee/hanoi.inp",rptfile="umee/hanoi.rpt",binfile="umee/hanoi.bin")
wntr.epanet.toolkit.ENepanet.ENgetcount() # trying to get linkcount
```

**Comment by kaklise** [comment]
Thanks for the comment.  WNTR allows you to access the network using the WaterNetworkModel object, but you can use the EPANET toolkit from within WNTR if you'd like.  For example, you can print the number of links and run an EPANET simulation using the WaterNetworkModel:
```
wn = wntr.network.WaterNetworkModel(inpfile)
print(wn.num_links)
sim = wntr.sim.EpanetSimulator(wn)
results = sim.run_sim()
```
Or you can use the EPANET toolkit and then read simulation results from the EPANET bin file using the wntr.epanet.io.BinFile class:
```
EN = wntr.epanet.toolkit.ENepanet(inpfile, rptfile, binfile)
EN.ENopen()
print(EN.ENgetcount(2)) # 2 = LINKCOUNT
EN.ENsolveH()
EN.ENsolveQ()
EN.ENclose()
reader = wntr.epanet.io.BinFile()
results = reader.read(binfile)
```
The EN constants (iCode) used in the EPANET toolkit are listed in wntr.epanet.util.EN

**Comment by Pepukai** [comment]
Thank you for the response it has worked. maybe a follow up questions. How do I set an attribute value in an already existing inp file. For example I am trying to change the diameter of links/pipes.
I am able to do it with epanettools module however I would like to use wntr for this action.

```
from epanettools.epanettools import EPANetSimulation, Node, Link, Network 
from epanettools.epanettools import Nodes, Links, Pattern, Patterns, Controls, Control
inp_file = "hanoi.inp"
es=EPANetSimulation(inp_file)
d = Link.value_type["EN_DIAMETER"]
r = es.ENsetlinkvalue
s = es.ENsaveinpfile
dia = array("i",[305,406,508,610,762,1016])
for i in range (genes + 1):
        r(i,d,random.choice(dia)) #random allocation of pipesizes
    out_file = "hanoi.inp" 
    s(out_file)
```

**Comment by michaelbynum** [comment]
@Pepukai I think the following will do what you need. 
```
import wntr
inp_file = "hanoi.inp"
wn = wntr.network.WaterNetworkModel(inp_file)
link_names_to_modify = ['link1', 'link2', 'link3']
for link_name in link_names_to_modify:
    link = wn.get_link(link_name)
    link.diameter = 1.0
# Save a new inp file or run a simulation
```

**Comment by Pepukai** [comment]
thank you @michaelbynum 

I ran the code and want to save the file it gives a distorted inpfile  
[hanoi1.inp.txt](https://github.com/USEPA/WNTR/files/2490505/hanoi1.inp.txt)


```
import wntr
wn = wntr.network.WaterNetworkModel(inp_file)
link_name_to_modify = ["1","2","3"] 
for link_name in link_name_to_modify:
    link = wn.get_link(link_name)    
    link.diameter = 20
wn.write_inpfile('hanoi1.inp')
```

**Comment by michaelbynum** [comment]
@Pepukai Can you share the original inp file (offline - mlbynum@sandia.gov) so that I can compare the two?

**Comment by michaelbynum** [comment]
It seems we are not writing the BACKDROP section of inp files correctly. This should be an easy fix. I can take care of it in the morning.

**Comment by michaelbynum** [comment]
@Pepukai We have corrected the BACKDROP section of the inp file writer on master.

**Comment by Pepukai** [comment]
@michaelbynum Thank you.
How do I add the file to the module

**Comment by michaelbynum** [comment]
@Pepukai All you need to do is update to master. First uninstall the version of wntr you have. You can either clone the repository or download a zip file of the repo. Then just run "python setup.py install" from within the main wntr directory. If you have any trouble, let me know.
