### ISSUE TITLE
Step-wise WNTR simulation problem

### ISSUE THREAD

**Issue by dionikolop** [USEPA/WNTR#59]
Hello,
I am experiencing a strange issue when performing a step-wise simulation. The set-up: a) I import a .inp file like example Net1 b) I set the time options to time.duration = 1 hour and same for hydraulic timestep c) I use WNTRSimulator d) I loop for 24 hours running the sim again for the same water network, but advancing the time.start_clocktime by one hour.
The problem: At certain steps, the results are empty data frames. 
Strange behaviour: If you force the simulation to run again  when the results are an empty dataframe, then the new results are not an empty dataframe and also correct hydraulically speaking.
You can replicate the issue with the code below and you can note that at hour 12 and 23 (starting count from 0) the results are empty dataframes.  
I use Anaconda 5.1.0, python version 3.6 and I installed WNTR with pip.

```
import wntr
import pandas as pd

inp_file = 'C:/...../WNTR-master/examples/networks/Net1.inp'
wn.options.time.duration = 3600
wn.options.time.hydraulic_timestep = 3600
wn.options.time.pattern_timestep =7200

pres=pd.DataFrame()
stat=pd.DataFrame()

for hour in range(0,24):
     print(hour)
     sim = wntr.sim.WNTRSimulator(wn)
     results= sim.run_sim(solver_options=solv_opts, convergence_error=True)
     print(results.node["pressure"])
     pres=pres.append(results.node["pressure"],ignore_index = True)
     print(results.link["status"])
     stat=stat.append(results.link["status"],ignore_index = True)       
     wn.options.time.start_clocktime=wn.options.time.start_clocktime+3600
```

The strange solution is  to add this check inside the loop after results=sim.run_sim() command:
```
while results.node["pressure"].empty:
        print("empty")
        results=sim.run_sim()
```
Any help would be more than welcome!

**Comment by michaelbynum** [comment]
All you need to do is replace
```
wn.options.time.start_clocktime=wn.options.time.start_clocktime+3600
```
with
```
wn.options.time.duration += 3600
```

The ```start_clocktime``` should never change during a simulation. As the simulation progresses in time, the simulator will advance ```wn.sim_time``` as needed. The ```clocktime``` is simply ```wn.sim_time + wn.options.time.start_clocktime```. 

However, the simulator should never simulate past ```wn.options.time.duration```. This is a bug, and I will fix it. 

If you ever need to reset the network to its initial conditions, just use ```wn.reset_initial_values()```. This will set ```wn.sim_time``` back to zero, change the tank levels back to their initial levels, etc. For example:

```
import wntr
import pandas as pd

solv_opts = {}

inp_file = 'Net1.inp'
wn = wntr.network.WaterNetworkModel(inp_file)
wn.options.time.duration = 3600*24
wn.options.time.hydraulic_timestep = 3600
wn.options.time.pattern_timestep =7200

sim = wntr.sim.WNTRSimulator(wn)
results_24= sim.run_sim(solver_options=solv_opts, convergence_error=True)

wn.reset_initial_values()

wn.options.time.duration = 0

pres=pd.DataFrame()
stat=pd.DataFrame()

for hour in range(0,25):
     sim = wntr.sim.WNTRSimulator(wn)
     results= sim.run_sim(solver_options=solv_opts, convergence_error=True)
     pres=pres.append(results.node["pressure"],ignore_index = False)
     stat=stat.append(results.link["status"],ignore_index = False)
     wn.options.time.duration += 3600

pres_24 = results_24.node["pressure"]
temp = pres-pres_24
print(temp)
```
Output:
```
        10   11   12   13   21   22   23   31   32    2    9
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3600   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7200   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10800  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14400  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
18000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
21600  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
25200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
28800  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
32400  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
36000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
39600  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
43200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
46800  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
50400  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
54000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
57600  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
61200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
64800  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
68400  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
72000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
75600  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
79200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
82800  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
86400  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
```

**Comment by dionikolop** [comment]
Thanks for your prompt reply! It works as it should now. By the way, the WNTRSimulator is a very good tool, do you plan to also add quality simulation?

**Comment by michaelbynum** [comment]
Thank you! We really appreciate that. You can run water quality simulations with the EpanetSimulator within WNTR. Given how well established, dependable, and efficient EPANET is, I think it is unlikely that we will implement our own water quality simulator. @kaklise Do you have anything to add?

**Comment by dionikolop** [comment]
I am asking because the WNTRSimulator also runs in  pressure dependent demand mode and I would like to experiment with a combination of quality and pressure dependent simulation.

**Comment by michaelbynum** [comment]
I think that is currently possible. I think you can use the EpanetSimulator with the hydraulics results from the WNTRSimulator. All we do is write an inp file with the demands modified to match the results of the pressure driven simulation from the WNTRSimulator. @dbhart Can you confirm that this has been implemented? Or did we just talk about it?

**Comment by kaklise** [comment]
The docs include an example at the top of https://wntr.readthedocs.io/en/latest/waterquality.html.
