### ISSUE TITLE
Pump Attribute Calling

### ISSUE THREAD

**Issue by TimMontgomery** [USEPA/WNTR#62]
Hello, I am new to coding and am trying to utilize WNTR for a project. I am having issues calling into the pumps to pull the "power" attribute and have it match the model. Both units are in HP. It is either prints out "1" or "None." 

`wntr.network.model.Pump('~@Pump-1','I-Pump-1','O-Pump-1', wn)._base_power`
 
`print(wntr.network.elements.Pump('~@Pump-1','I-Pump-1','O-Pump-1', wn)._base_power)`

I can have it call into the model for junction or pipe attributes and can modify those as desired. I am just unsure of the proper pathway to call for pumping power and how to modify it once I can call to it.

**Comment by michaelbynum** [comment]
WNTR is designed for network elements to be added/created through methods on the WaterNetworkModel object. For example:

```
>>> import wntr
>>> wn = wntr.network.WaterNetworkModel()
>>> wn.add_junction('a')
>>> wn.add_junction('b')
>>> wn.add_pump(name='pump', start_node_name='a', end_node_name='b', pump_type='POWER')
>>> p = wn.get_link('pump')
>>> p.power
50.0
>>> p.power = 10
>>> p.power
10
```
