### ISSUE TITLE
[DEMANDS] section does not replace demands in [JUNCTIONS]

### ISSUE THREAD

**Issue by balks** [USEPA/WNTR#68]
According to EPAnet INP-file specifications, the demands in section [DEMANDS] should replace the demands as specified in [JUNCTIONS]. In io.py there is a line (1347) that makes sure that this happens based on category 'EN2 base', but it is commented out. Hence any demands in the [DEMANDS] sections is added to the node. Can this line be activated again safely or does this affect anything else?

**Comment by dbhart** [comment]
It *should* be okay to remove. I have not tested it yet with the reactivation of that line to make sure it would behave correctly, but the only issue would be if you are trying to remove patterns – I haven’t checked to make sure that it would track properly that the pattern is/isn’t still being used.

**Comment by pshassett** [comment]
#70 does fix the issue of [DEMANDS] specifications not overwriting demands specified in the [JUNCTIONS} section, but `node.demand_timeseries_list.remove_category('EN2 base')`  results in the demand information that was stored in the [JUNCTIONS] section to be lost.  

If a user wanted to import an INP file, make some modifications to the network in WNTR, and then write/save the new network as a new INP file, any nodes with demands specified in both the [JUNCTIONS} and [DEMANDS] sections would lose the demand information defined in the [JUNCTIONS] section.  

A possible solution could be to add a condition in the simulation such that if there is more than one demand applied at a node, the demand with category 'EN2 base' is ignored.
