### ISSUE TITLE
EPANET i/o error when running EpanetSimulator in Parallel

### ISSUE THREAD

**Issue by tyjchen** [USEPA/WNTR#71]
i'm trying to run simulations using the wntr.EpanetSimulator() function in parallel and i keep getting back epanet errors "EPANET Error 200" or "EPANET Error 224". the error implies i do not have a supply nodes but I explicitly call wntr.add_reservoir()/wntr.add_tank() beforehand, it's unclear to me why this is happening. 
i also assert that the network is completely connected (using the wntr.to_undirected() function), and that there is at least one supply node (length of wntr.reservoir_name_list + wntr.tank_name_list).
the os im using is linux (ubuntu), any pointers as why this is happening? my hunch is the parallelization of writing and running multiple files at once

**Comment by kaklise** [comment]
It's possible that each process is pointing to the same INP file.  The EpanetSimulator writes an INP file called 'temp.inp' by default.   You can set a unique name for that file using `file_prefix` when you call `run_sim`.

**Comment by tyjchen** [comment]
that seems to have solved the problem, thank you!
