### ISSUE TITLE
WNTRSimulator not working for network with PSV valve

### ISSUE THREAD

**Issue by emmaliulu** [USEPA/WNTR#72]
Here's my script

inp_file = 'AvgDay_460MGD_March2018.inp'
wn_0 = wntr.network.WaterNetworkModel(inp_file)

sim_0 = wntr.sim.WNTRSimulator(wn_0)
results_0 = sim_0.run_sim()

I got the following error message 

"Traceback (most recent call last):

  File "<ipython-input-15-706536a93aeb>", line 13, in <module>
    results_0 = sim_0.run_sim()

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda2\lib\site-packages\wntr\sim\core.py", line 215, in run_sim
    model = HydraulicModel(self._wn, self.mode)

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda2\lib\site-packages\wntr\sim\hydraulics.py", line 70, in __init__
    self._set_link_attributes()

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda2\lib\site-packages\wntr\sim\hydraulics.py", line 383, in _set_link_attributes
    raise ValueError('Currently only PRVs, FCVs, and TCVs are supported.')

ValueError: Currently only PRVs, FCVs, and TCVs are supported."

I notice I have a number of PSV valves in my network. How should I go about avoiding this error message? Thank you.

**Comment by tyjchen** [comment]
you could try to replace PSV's with PRV's and rerun the simulation, ensuring all the same rules are carried over

**Comment by emmaliulu** [comment]
I replaced all PSV with PRV and rerun the simulation. I got this error message.

"RuntimeError: Simulation did not converge. Jacobian is singular at iteration 0"

**Comment by tyjchen** [comment]
hmm, it's implying that the initial hydraulics setting does not converge, you could try let the optimization just give you non-converged solutions and see how that looks like. rum.sim(convergence_error=False). or let it use a different solution method: rum.sim(solver_options={'BACKTRACKING' = False}) and see what happens. hope it helps-

**Comment by emmaliulu** [comment]
When I tried with "results_0 = sim_0.run_sim(solver_options={'BACKTRACKING'== False})", it gave me this error message "RuntimeError: Simulation did not converge. Jacobian is singular at iteration 0". 

When I tried with "results_0 = sim_0.run_sim(convergence_error=False)", it didn't show any errors, but the result data frame is empty.

I wonder if there is a way to solve the initial problem of "ValueError: Currently only PRVs, FCVs, and TCVs are supported." Could we model minor loss for PSV valve?

This is how WNTR simulate minor loss for other types of valves.
if link_id in self._tcv_ids:
                    """
                    The minor loss on a TCV is used when the valve is open; The setting is used when it is active.
                    The setting on a TCV appears to work just as the minor loss on a pipe. TCVs do allow reverse flow.
                    Thus, they act just like a pipe, but with only a minor loss - no Hazen-Williams, DW, CM.
                    """
                    self.pipe_resistance_coefficients[link_id] = 8.0*link.setting/(self._g*math.pi**2*link.diameter**4)
                elif link_id in self._prv_ids:
                    self.pipe_resistance_coefficients[link_id] = 0.0
                elif link_id in self._fcv_ids:
                    self.pipe_resistance_coefficients[link_id] = 0.0
                else:
                    raise ValueError('Currently only PRVs, FCVs, and TCVs are supported.')

**Comment by kaklise** [comment]
You can find a list of network options that are not currently supported by the WNTRSimulator at https://wntr.readthedocs.io/en/latest/framework.html#limitations.  We are working on software updates that will address these limitations and PSV is high on our list of priorities.  If you don't expect the system to be pressure deficient, you could use the EpanetSimulator, at least as a starting point.

**Comment by emmaliulu** [comment]
That's good to know. I wanted to use WNTRSimulator because I would like to use the Leak Model. If PSV is not yet simulated in WNTR, I suppose there are alternative ways to simulate leakage with EpanetSimulator?

**Comment by kaklise** [comment]
To model a leak using the EpanetSimulator, you could adjust demands or use emitters.

**Comment by emmaliulu** [comment]
Thank you. I will test it out.

**Comment by emmaliulu** [comment]
Hi again. I tried EpanetSimulator with emitter to simulate leakage and it worked well. I wonder if there is any way to capture demand deficit without WNTR pressure driven simulation. Or is there a way to represent pressure driven with EpanetSimulator?

**Comment by michaelbynum** [comment]
We will have support for PSV's in about a week if that helps.

**Comment by emmaliulu** [comment]
That's great to know! Thank you.

**Comment by emmaliulu** [comment]
Hi, I'd like to follow up on the support for PSV. Has the new version of WNTR with PSV capability ready for use?

**Comment by michaelbynum** [comment]
@emmaliulu Sorry for the delay. Support for PSVs have now been added in a branch called "psv_support" on my fork. Unfortunately, we will not be able to merge this branch into the main repository for a while.
