### ISSUE TITLE
what units are flows reported in?

### ISSUE THREAD

**Issue by tyjchen** [USEPA/WNTR#73]
the reference provides 5 different units of flow, how can we know which one is reported when we run the EPANET simulator?
https://wntr.readthedocs.io/en/latest/units.html

code: 
epanet_sim = wntr.sim.EpanetSimulator(wntr_object)
results = epanet_sim.run_sim()
flows = results.link['flowrate']

**Comment by kaklise** [comment]
The table references unit conversions for EPANET INP files.  Data that is stored in a WNTR water network model and the results from a simulation (EpanetSimulator or WNTRSimulator) are all in SI units.  Flowrate is in m^3/s.  I see that flowrate is not listed at the top of that page, we'll fix that.

**Comment by tyjchen** [comment]
sorry i just had a follow up question, you mention all data is in SI units. so should I be writing my pipe diameters in M? and not mm as shown in the conversion table?

https://wntr.readthedocs.io/en/latest/units.html

**Comment by michaelbynum** [comment]
@tyjchen Good catch. There is a typo in that table. Diameter should be in meters. We will get that fixed.

**Comment by michaelbynum** [comment]
@tyjchen Please disregard my last comment. I spoke too quickly. There is not a typo. The table you are referencing specifies units for Epanet inp files. Pipe diameters should indeed be specified in mm. However, once the model is loaded into a WaterNetworkModel object, pipe diameters are all in meters as specified here https://wntr.readthedocs.io/en/latest/units.html#units. Does that make sense?

**Comment by tyjchen** [comment]
@michaelbynum thanks for the response, i'm still a little unsure of what the "right" units are. just to make sure: when an existing .inp file is read the diameters are converted automatically from from inches to meters. if i want to add say a new pipe of 10 inches to the model (using wntr.add_pipe()), i should also use meters? 
or should i convert the diameters in the existing model from M to mm?

**Comment by michaelbynum** [comment]
When using ```wn.add_pipe()```, diameter should be specified in meters. At the very top of the previously mentioned webpage (https://wntr.readthedocs.io/en/latest/units.html#units), there is a bulleted list of units. These are the units used in WNTR. Anytime you interact with WNTR python objects, you should use these units. Table 4 on the same page is only for inp files.

**Comment by tyjchen** [comment]
@michaelbynum thank you!
