### ISSUE TITLE
value error when reading existing .inp file

### ISSUE THREAD

**Issue by tyjchen** [USEPA/WNTR#74]
i try to run the following code
input = wntr.network.WaterNetworkModel("model.inp")
and get the resulting error
-packages/wntr/epanet/io.py", line 1680, in _read_options
    setattr(opts, words[0].lower(), float(words[1]))
ValueError: could not convert string to float: 'psi'

any suggestions on how to resolve the error? should i be making changes to the .inp file?

**Comment by dbhart** [comment]
EPANET 2 does not allow the “psi” unit designation anywhere in the input file, according to the specifications in the user manual. However, some older inp-files still have this element in there. If you search for “psi” in your input file you can probably remove the word, or if you can reply with the inp-file line in question I may be able to suggest if the line is even necessary in EPANET 2.

The other option is to load the inp file in the EPANET GUI (if available) and then export it to an inp file again. This converts older files to the correct EPANET 2 standard format.

-dh

**Comment by tyjchen** [comment]
the export and re-read solution worked, thank you!
