### ISSUE TITLE
Calling Reservoir Attributes

### ISSUE THREAD

**Issue by Mattii1994** [USEPA/WNTR#76]
Helo,
is possible to get atribute of reservoir e.g. elevation from imported WDS model? I can't use `query_node_attribute` because reservoir isn't a node in WNTR. Is any method to get this attribute?

**Comment by Mattii1994** [comment]
Ok, i find solution

`wn.query_node_attribute('elevation', node_type=wntr.network.model.Reservoir)`

**Comment by kaklise** [comment]
Reservoirs are not assigned an elevation, but if you added an attribute called elevation to a reservoir, then you should be able to call `wn.query_node_attribute('elevation')`.  This will return the elevation of all Nodes (Junctions, Tanks, and Reservoirs).  Your solution will also work, to return elevations of just Reservoirs.
