### ISSUE TITLE
travis-ci, coveralls and readthedocs is not working

### ISSUE THREAD

**Issue by rachmadaniHaryono** [USEPA/WNTR#8]

**Comment by kaklise** [comment]
We are not able to connect to Travis-CI and Coveralls from the USEPA GitHub page.  We are working on a solution.  The code is tested on team member forks, see <https://travis-ci.org/kaklise/WNTR> and <https://coveralls.io/github/kaklise/WNTR>.  A draft version of the documentation will be made available soon.

**Comment by kaklise** [comment]
Documentation is now available at <http://wntr.readthedocs.io>.  The badges at the top of the README page link to the kaklise/wntr test results on Travis-CI and Coveralls.  The test results links will be updated to use the USEPA site at a later date.

**Comment by kaklise** [comment]
The badges on USEPA/WNTR now point to sandialabs/WNTR for testing and documentation.

**Comment by rachmadaniHaryono** [comment]
i think change the link on the badge is good enough to close this issue
