### ISSUE TITLE
Zero Demand causes Jacobian to be singular

### ISSUE THREAD

**Issue by dionikolop** [USEPA/WNTR#81]
Hello,
I came across a "Simulation did not converge. Jacobian is singular at iteration 0". I added a node with zero demand, and this occurs only in PDD mode and WNTR simulator. Changing the node's demand to something small e.g. 0.001 m3/s or 0.1 m3/s does not solve the problem. However, when I use the WNTR simulator or Epanet Simulator in Demand-driven mode no error occurs. Any known remedies to this issue?
I must clarify that the network i use is a modified Net1.inp.
This is my code:
```
wn=wntr.network.WaterNetworkModel('Net1.inp')
negative_demand=-0.005
wn.add_junction('10IN',base_demand=negative_demand,
                        demand_pattern=None, elevation=cpmodel.wn.get_node('10').elevation+1,
                        coordinates=(cpmodel.wn.get_node('10').coordinates[0]+0.5,cpmodel.wn.get_node('10').coordinates[1]+0.5))
wn.get_node('10IN').nominal_pressure=0
wn.get_node('10IN').minimum_pressure=1
wn.add_pipe('pipe1','10IN','10',length=1.225)
wn.add_junction('10F',base_demand=0,
                        demand_pattern=None, elevation=cpmodel.wn.get_node('10').elevation-0.5,
                        coordinates=(cpmodel.wn.get_node('10').coordinates[0]-0.5,cpmodel.wn.get_node('10').coordinates[1]-0.5))
wn.get_node('10F').nominal_pressure=0
wn.get_node('10F').minimum_pressure=1
wn.add_pipe('pipe2','10F','10',length=1.225)
```

Adding the following produces the problem

```
wn.add_junction('32F',base_demand=0.1,
                        demand_pattern=None, elevation=cpmodel.wn.get_node('32').elevation+0.5,
                        coordinates=(cpmodel.wn.get_node('32').coordinates[0]-0.5,cpmodel.wn.get_node('32').coordinates[1]-0.5))
wn.get_node('32F').nominal_pressure=0
wn.get_node('32F').minimum_pressure=1
wn.add_pipe('pipe3','32F','32',length=1.225)

sim = wntr.sim.WNTRSimulator(wn, mode='PDD')
results= sim.run_sim()
```
Also, when i remove the nominal and minimum pressure declarations it runs without problem.
Thanks in advance!

**Comment by kaklise** [comment]
Nominal pressure should be greater than minimum pressure.  When I changed nominal pressure to 1 and minimal pressure to 0, the PDD simulation runs.

**Comment by dionikolop** [comment]
I can't believe I overlooked it. Thanks.
