### ISSUE TITLE
Skeletonized demands are not written to inp files

### ISSUE THREAD

**Issue by pshassett** [USEPA/WNTR#82]
After running `wn_skel wntr.morph.skeletonize(wn)`, the new demands are not written to the .inp file using `wn_skel.write_inpfile` or the `wntr.epanet.io.InpFIle.write` class method.  See attached script.
[net3skel.py.txt](https://github.com/USEPA/WNTR/files/3030966/net3skel.py.txt)
[Net3.inp.txt](https://github.com/USEPA/WNTR/files/3030968/Net3.inp.txt)

**Comment by kaklise** [comment]
I think we need to change the demand category name when merging demands.  I'll look into it and see if that solves the issue.

**Comment by pshassett** [comment]
Issue resolved by PR #83

**Comment by pshassett** [comment]
Setting reallocated demands category to `None` ensures that base demand for reallocated nodes is moved to [DEMANDS] section of the inp but the base demand for `neigh_junc` or `closest_junc` must also be assigned a category other than 'EN2-base' in order to move the base demand to the [DEMANDS] section of the inp file. Maybe instead of a `None` category these reallocated/moved demands can have a category such as 'skeletonize'.

**Comment by pshassett** [comment]
[bwsntest.zip](https://github.com/USEPA/WNTR/files/3065604/bwsntest.zip)

**Comment by pshassett** [comment]
[BWSN1_skel.zip](https://github.com/USEPA/WNTR/files/3069519/BWSN1_skel.zip)
Sorry, uploaded the wrong script.
