### ISSUE TITLE
WNTR-psv_support installation issue

### ISSUE THREAD

**Issue by emmaliulu** [USEPA/WNTR#91]
@michaelbynum I downloaded psv_support from your folk. When I tried to install it. I got this error message

D:\Research_Y2\WNTR-psv_support>python setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to wntr.egg-info\top_level.txt
writing wntr.egg-info\PKG-INFO
writing dependency_links to wntr.egg-info\dependency_links.txt
reading manifest file 'wntr.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'LICENSE.txt'
writing manifest file 'wntr.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying wntr\sim\aml\evaluator.cpp -> build\lib.win32-3.5\wntr\sim\aml
copying wntr\sim\aml\evaluator_wrap.cpp -> build\lib.win32-3.5\wntr\sim\aml
copying wntr\sim\network_isolation\network_isolation.cpp -> build\lib.win32-3.5\wntr\sim\network_isolation
copying wntr\sim\network_isolation\network_isolation_wrap.cpp -> build\lib.win32-3.5\wntr\sim\network_isolation
running build_ext
building 'wntr.sim.aml._evaluator' extension
error: [WinError 2] The system cannot find the file specified

Could you help me identify the problem?

**Comment by michaelbynum** [comment]
@emmaliulu What happens when you run ```python setup.py develop```?

**Comment by emmaliulu** [comment]
@michaelbynum Same thing happened.

D:\Research_Y2\WNTR-psv_support>python setup.py develop
running develop
running egg_info
writing top-level names to wntr.egg-info\top_level.txt
writing dependency_links to wntr.egg-info\dependency_links.txt
writing wntr.egg-info\PKG-INFO
reading manifest file 'wntr.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'LICENSE.txt'
writing manifest file 'wntr.egg-info\SOURCES.txt'
running build_ext
building 'wntr.sim.aml._evaluator' extension
error: [WinError 2] The system cannot find the file specified

**Comment by michaelbynum** [comment]
@emmaliulu Are you using a 32-bit machine?

**Comment by emmaliulu** [comment]
I just checked. It is a 64-bit machine.

**Comment by michaelbynum** [comment]
@emmaliulu What version of python?

**Comment by michaelbynum** [comment]
@emmaliulu Also, how did you install python?

**Comment by emmaliulu** [comment]
@michaelbynum I just checked my python is 32-bit. Could this be the problem? I use Anaconda to run python.

**Comment by michaelbynum** [comment]
@emmaliulu Yes, I believe this is the problem. Conda-forge does not support 32-bit builds, so we don't have any pre-compiled binaries for 32-bit systems right now. My advice would be to download the 64-bit version of anaconda. I know that is annoying, and I apologize. Alternatively, if you have a c++ compiler, you could change the ```build``` flag in ```setup.py``` to ```True```, and then run ```python setup.py install```.

**Comment by emmaliulu** [comment]
@michaelbynum Problem solved! Thank you for your help.

**Comment by michaelbynum** [comment]
@emmaliulu Great! For future reference, what was your fix? Did you use a 64-bit version of anaconda?

**Comment by emmaliulu** [comment]
I did a couple things. First, I installed 64-bit version of Anaconda, I also updated my Python to the same version. Second, I installed Visual Studio C++ build tool as required in the command window. After that, the installation went through without any problem.

**Comment by michaelbynum** [comment]
@emmaliulu I was hoping that you would not have to compile anything once you updated to the 64-bit version of Anaconda/Python. Did you actually compile anything? Did you change the ```build``` flag in ```setup.py``` to ```True``` or did you leave it as ```False```?

I apologize for the many questions. I just want to make sure the install process is easy in the future.

**Comment by emmaliulu** [comment]
@michaelbynum No, I did not compile anything. I just installed the VS build tool, and then the installation went through.

**Comment by michaelbynum** [comment]
@emmaliulu Oh, okay. Great! Thanks.
