### ISSUE TITLE
WNTR-psv WNTRSimulator issue

### ISSUE THREAD

**Issue by emmaliulu** [USEPA/WNTR#92]
I successfully installed WNTR-psv and loaded WNTR-psv into python.

Here's my code

> inp_file = 'AvgDay_460MGD_March2018_original.inp'

> wn_0 = wntr.network.WaterNetworkModel(inp_file)

> sim_0 = wntr.sim.WNTRSimulator(wn_0)

> results_0 = sim_0.run_sim()

Here's what the screen shows

> Traceback (most recent call last):

  File "<ipython-input-11-c23e687c17ae>", line 2, in <module>
    results_0 = sim_0.run_sim()

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\core.py", line 463, in run_sim
    solver_status, mesg = _solver_helper(model, solver, solver_options)

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\core.py", line 732, in _solver_helper
    sol = _solver.solve(model)

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\solvers.py", line 99, in solve
    J = model.evaluate_jacobian(x=None)

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\aml\aml.py", line 336, in evaluate_jacobian
    raise ValueError('The number of constraints and variables must be equal.')

ValueError: The number of constraints and variables must be equal.

I don't quite understand what this error means. The INP file is based on a real drinking water distribution network that runs well with EpanetSimulator.

**Comment by michaelbynum** [comment]
@emmaliulu I think I know what the problem is. To verify, can you try running the simulation in PDD mode?

```
sim_0 = wntr.sim.WNTRSimulator(wn_0, mode='PDD')
```

**Comment by emmaliulu** [comment]
@michaelbynum Here's what I get

> sim_0 = wntr.sim.WNTRSimulator(wn_0, mode='PDD')

> results_0 = sim_0.run_sim()

Traceback (most recent call last):

  File "<ipython-input-21-658b9468b050>", line 1, in <module>
    results_0 = sim_0.run_sim()

  File "C:\Users\ll69\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\core.py", line 469, in run_sim
    raise RuntimeError('Simulation did not converge. ' + mesg)

RuntimeError: Simulation did not converge. Jacobian is singular at iteration 0

**Comment by emmaliulu** [comment]
@michaelbynum I tested with example INP file and WNTRSimulator went through without any issue. I think it might have something to do with my INP file. Here's what I get when I read in the file.

> inp_file =  'AvgDay_460MGD_March2018_original.inp'

> wn_0 = wntr.network.WaterNetworkModel(inp_file)

C:\Users\ll69\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\epanet\io.py:2072: UserWarning: Not all curves were used in "AvgDay_460MGD_March2018_original.inp"; added with type None, units conversion left to user
  warnings.warn('Not all curves were used in "{}"; added with type None, units conversion left to user'.format(self.wn.name))

Do you think the warnings may indicate the problem?

**Comment by kaklise** [comment]
Some INP files contain curves that are not used.  All the curves are retained in the WNTR WaterNetworkModel and the warning message is just letting you know some are not needed. If you can share the INP file you're using, that would be helpful.  Otherwise, please email me at kaklise@sandia.gov and we can discuss further.

**Comment by dbhart** [comment]
In particular, energy cost curves are not used by the WNTR model at this time. This tends to be quite a few of the cases where you will get this warning. I would suggest you email one of the core developers with the model rather than attaching it to an issue unless it is a completely non-sensitive network you are okay with anyone having.

-dave h

**Comment by emmaliulu** [comment]
Thank you. I just emailed my INP files to @kaklise.
