### ISSUE TITLE
Shape of passed values is (x, 1), indices imply (y, 25)

### ISSUE THREAD

**Issue by saramille** [USEPA/WNTR#94]
Hi,

I have successfully imported the network file (i.e. *.inp). However running the wntr simulator I keep on getting the following error:

Error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1650                 blocks = [make_block(values=blocks[0],
-> 1651                                      placement=slice(0, len(axes[0])))]
   1652 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   3094 
-> 3095     return klass(values, ndim=ndim, placement=placement)
   3096 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py in __init__(self, values, placement, ndim)
     86                 'Wrong number of items passed {val}, placement implies '
---> 87                 '{mgr}'.format(val=len(self.values), mgr=len(self.mgr_locs)))
     88 

ValueError: Wrong number of items passed 1, placement implies 25

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-7c7f47682be3> in <module>
      1 # Simulate hydraulics
      2 sim = wntr.sim.EpanetSimulator(wn)
----> 3 results = sim.run_sim()
      
C:\ProgramData\Anaconda3\lib\site-packages\wntr\sim\epanet.py in run_sim(self, file_prefix, save_hyd, use_hyd, hydfile)
     96         logger.debug('Completed run')
     97         #os.sys.stderr.write('Finished Closing\n')
---> 98         return self.reader.read(outfile)
     99 

C:\ProgramData\Anaconda3\lib\site-packages\wntr\epanet\io.py in read(self, filename, custom_handlers)
   2761                     logger.exception('Failed to process file: %s', e)
   2762 
-> 2763                 df = pd.DataFrame(data.transpose(), index =index, columns = reporttimes)
   2764                 df = df.transpose()
   2765 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    422             else:
    423                 mgr = init_ndarray(data, index, columns, dtype=dtype,
--> 424                                    copy=copy)
    425 
    426         # For data is list-like, or Iterable (will consume into list)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_ndarray(values, index, columns, dtype, copy)
    165         values = maybe_infer_to_datetimelike(values)
    166 
--> 167     return create_block_manager_from_blocks([values], [columns, index])
    168 
    169 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1658         blocks = [getattr(b, 'values', b) for b in blocks]
   1659         tot_items = sum(b.shape[0] for b in blocks)
-> 1660         construction_error(tot_items, blocks[0].shape[1:], axes, e)
   1661 
   1662 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in construction_error(tot_items, block_shape, axes, e)
   1689         raise ValueError("Empty data passed with indices specified.")
   1690     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 1691         passed, implied))
   1692 
   1693 

ValueError: Shape of passed values is (1515727, 1), indices imply (151572, 25)
--------------------------------------------------------------------------------------------

**Comment by michaelbynum** [comment]
@saramille What versions of WNTR and Pandas are you using? Do you get a similar error with the WNTRSimulator (as opposed to the EpanetSimulator)?

**Comment by kaklise** [comment]
After talking to @saramille, it appears that the simulation does not run to completion in WNTR or in the EPANET GUI.  This issue was resolved by modifying the damping limit in the INP file.  We will try to replicate this error in WNTR and generate a better error message.

**Comment by saramille** [comment]
I installed the recent version of Anaconda distribution with all the python packages uptodate. I don't recall the version of pandas right now but both WNTR and EPANET simulators were giving me some errors-- the running time on WNTR is a bit longer.

As Kate mentioned, what worked for me was increasing the damping effect from 0 (default value) to 0.1. This might relate to accuracy of the iterations...with larger values being less accurate.

**Comment by kalebsm** [comment]
I have am currently getting a similar ValueError as described above. I do not have a damping limit in my INP file, and would probably prefer to keep the damping effect at its default. Is there any other reason why I might be getting this error? Here is my Traceback:

File … \Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File …\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File …pds_LbLcode.py", line 572, in <module>
    pressure_output = run_pressure_simulations(wn_copy, 27, 1, 3, process_id_num)

  File …pds_LbLcode.py", line 47, in run_pressure_simulations
    results = epanet_sim.run_sim(file_prefix = "process_temp" + str(process_number))

  File …\Anaconda3\lib\site-packages\wntr\sim\epanet.py", line 98, in run_sim
    return self.reader.read(outfile)

  File …\Anaconda3\lib\site-packages\wntr\epanet\io.py", line 2792, in read
    df = pd.DataFrame(data.transpose(), index =index, columns = reporttimes)

  File …\Anaconda3\lib\site-packages\pandas\core\frame.py", line 440, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)

  File …\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 213, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])

  File …\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1688, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)

  File …\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1719, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)

**ValueError: Shape of passed values is (565279, 1), indices imply (31404, 25)**

**Comment by kalebsm** [comment]
Since this is a similar question to the one already closed, I wasn't sure whether or not to create a new issue or attach to this one, so I will wait a day and then create a new issue if I don't hear anything.
