### ISSUE TITLE
write_inpfile() does not write pipe status; instead writes pipe.initial_status

### ISSUE THREAD

**Issue by david-dj-taylor** [USEPA/WNTR#95]
The difference between pipe.status and pipe.initial_status is not well documented. 
I had thought pipe.status would be written as "Status" in the .INP file. Instead the pipe.initial_status is written as "Status".  After tracing this issue, I understand why this difference exists.

**Comment by michaelbynum** [comment]
@david-dj-taylor Good point. This will probably cause lots of people trouble in the future. @kaklise Should we consider renaming "status" to "current_status"?

**Comment by kaklise** [comment]
The write_inpfile method creates an INP file with initial conditions, we will update the documentation to reflect this and explain the differences between initial and current attributes of the model.

**Comment by david-dj-taylor** [comment]
Many thanks for your helpful attention! I really love the work you guys have done and are doing!!
