### ISSUE TITLE
RuntimeError: Hydraulic_metrics

### ISSUE THREAD

**Issue by jeongsoo0908** [USEPA/WNTR#98]
Hello. I want to inquire about error while studying WNTR Simulator.
An error occurs during the calculation of 'Compute water service availability, for each operation' in the hydraulics.

Warning (from warnings module):
  File "C:\Users\syste\AppData\Local\Programs\Python\Python36\lib\site-packages\wntr\sim\hydraulics.py", line 713
    last_segment = (-0.5)*j_d/(nomP-minP)*((P-minP)/(nomP-minP))**(-0.5)
RuntimeWarning: divide by zero encountered in power

Warning (from warnings module):
  File "C:\Users\syste\AppData\Local\Programs\Python\Python36\lib\site-packages\wntr\sim\hydraulics.py", line 713
    last_segment = (-0.5)*j_d/(nomP-minP)*((P-minP)/(nomP-minP))**(-0.5)
RuntimeWarning: invalid value encountered in multiply

I hope you will let me know the solution to this.
Thank you.

**Comment by michaelbynum** [comment]
This is actually not a problem. These warnings come from numpy. They are expected, but difficult to suppress. We are working on a refactor of the hydraulics model that should be available in a few weeks. One of the benefits of th refactor is that these warnings will not be encountered.
